import { useState } from 'react'
import { useQueryClient } from '@tanstack/react-query'
import { useOutletContext } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { apiRequest } from '../../api/client'
import { usePlanProgress, usePlans } from '../../api/queries'
import type { Plan } from '../../api/types'
import type { DashboardContext } from '../../app/AppShell'
import { Badge, Button, EmptyState, ErrorState, Progress, Skeleton } from '../../shared/components/ui'
import { planStatusKey, progressMessageKey, riskKey } from '../../localization/presentation'
import { useLocale } from '../../localization/runtime'

export function PlansScreen() {
  const { t } = useTranslation(); const { locale } = useLocale(); const { me, guild } = useOutletContext<DashboardContext>(); const query = usePlans(me.user.discord_user_id, guild.guild_id); const [selected,setSelected] = useState<Plan|null>(null); const progress = usePlanProgress(me.user.discord_user_id, guild.guild_id, selected?.id); const client = useQueryClient()
  async function command(path:string,body?:unknown) { if (!selected) return; const options:Parameters<typeof apiRequest>[1]={method:'POST'}; if(path==='confirm')options.headers={'Idempotency-Key':crypto.randomUUID()}; if(body!==undefined)options.body=body; await apiRequest(`/api/v1/guilds/${guild.guild_id}/plans/${selected.id}/${path}`,options); await client.invalidateQueries({queryKey:['did',me.user.discord_user_id,guild.guild_id,'plans']}); const current = query.data?.plans.find((plan) => plan.id === selected.id); if (current) setSelected(current) }
  if(query.isLoading)return <Skeleton/>; if(query.isError)return <ErrorState retry={()=>void query.refetch()}/>
  const events = progress.data?.events ?? []; const latest = events.at(-1); const total = latest?.total_operations; const completed = latest?.completed_operations ?? 0; const ratio = total && total > 0 ? completed / total : undefined; const percentage = ratio === undefined ? undefined : Math.round(ratio * 100); const numbers = new Intl.NumberFormat(locale); const percent = new Intl.NumberFormat(locale, { style: 'percent', maximumFractionDigits: 0 })
  return <section><h1>{t('plans.title')}</h1>{query.data?.plans.length===0&&<EmptyState messageKey="plans.empty"/>}<div className="card-grid">{query.data?.plans.map((plan)=><button type="button" className="plan-card" key={plan.id} onClick={()=>setSelected(plan)}><strong>{plan.id.slice(0,8)}</strong><Badge tone={plan.status==='SUCCEEDED'?'ok':plan.status==='FAILED'?'danger':'neutral'}>{t(planStatusKey(plan.status))}</Badge><span>{t('plans.risk',{value:t(riskKey(plan.risk_level))})}</span></button>)}</div>{selected&&<article className="detail-panel"><h2>{t('plans.progress')}</h2><Progress labelKey="plans.progress" value={percentage}/>{ratio!==undefined&&<p>{t('plans.progress.counts',{completed:numbers.format(completed),total:numbers.format(total??0),percent:percent.format(ratio)})}</p>}{progress.isError&&<ErrorState retry={()=>void progress.refetch()}/>}<div className="button-row"><Button labelKey="plans.preflight" onClick={()=>void command('validate',{expected_version:selected.state_version})}/><Button labelKey="plans.confirm" onClick={()=>void command('confirm',{expected_version:selected.state_version,plan_hash:selected.plan_hash,acknowledgement:selected.reinforced_confirmation_required?`CONFIRM DESTRUCTIVE ${selected.plan_hash}`:null})}/><Button labelKey="plans.apply" variant="primary" onClick={()=>void command('apply')}/><Button labelKey="plans.cancel" variant="danger" onClick={()=>void command('cancel')}/></div><ol aria-live="polite">{events.map((event)=><li key={event.sequence}><Badge>{t(planStatusKey(event.plan_status))}</Badge> {t(progressMessageKey(event.message_key),event.params??{})}</li>)}</ol></article>}</section>
}
