import { phase4PoliciesPacks } from './phase4PoliciesCatalog'

const rebrand = (pack: Record<string, string>) => Object.fromEntries(
  Object.entries(pack).map(([key, value]) => [key, value.replaceAll('DID', 'Bunny')]),
)

export const bunnyAccessPacks: Record<'en' | 'fr' | 'de' | 'es', Record<string, string>> = {
  en: {
    ...rebrand(phase4PoliciesPacks.en),
    'policies.subtitle': 'Choose a clear rule, select the people concerned, and preview the result before anything changes.',
    'policies.native.title': 'Suggested intentions',
    'policies.origin.did': 'Bunny suggestion',
    'policies.editor.empty': 'Choose an intention on the left to configure access in plain language.',
    'policies.intent.search': 'Search an access intention',
    'policies.roles.search': 'Search roles',
    'policies.roles.selected': 'Selected roles',
    'policies.roles.more': 'Show all roles',
    'policies.roles.less': 'Show fewer roles',
    'policies.roles.empty': 'No matching role',
    'policies.result.everyoneExcept': 'Everyone except {{roles}}',
    'policies.result.noRoles': 'No role selected yet',
    'policies.result.noAction': 'use this access',
    'policies.result.thisServer': 'this server',
    'policies.result.sentence': '{{actors}} can {{actions}} in {{target}}.',
  },
  fr: {
    ...rebrand(phase4PoliciesPacks.fr),
    'policies.subtitle': 'Choisissez une règle claire, sélectionnez les personnes concernées et vérifiez le résultat avant tout changement.',
    'policies.native.title': 'Intentions suggérées',
    'policies.origin.did': 'Suggestion Bunny',
    'policies.editor.empty': 'Choisissez une intention à gauche pour configurer les accès en langage simple.',
    'policies.intent.search': 'Rechercher une intention d’accès',
    'policies.roles.search': 'Rechercher des rôles',
    'policies.roles.selected': 'Rôles sélectionnés',
    'policies.roles.more': 'Afficher tous les rôles',
    'policies.roles.less': 'Afficher moins de rôles',
    'policies.roles.empty': 'Aucun rôle correspondant',
    'policies.result.everyoneExcept': 'Tout le monde sauf {{roles}}',
    'policies.result.noRoles': 'Aucun rôle sélectionné',
    'policies.result.noAction': 'utiliser cet accès',
    'policies.result.thisServer': 'ce serveur',
    'policies.result.sentence': '{{actors}} peut {{actions}} dans {{target}}.',
  },
  de: {
    ...rebrand(phase4PoliciesPacks.de),
    'policies.subtitle': 'Wählen Sie eine klare Regel und die betroffenen Personen. Prüfen Sie das Ergebnis, bevor sich etwas ändert.',
    'policies.native.title': 'Vorgeschlagene Absichten',
    'policies.origin.did': 'Bunny-Vorschlag',
    'policies.editor.empty': 'Wählen Sie links eine Absicht, um den Zugriff in einfacher Sprache einzurichten.',
    'policies.intent.search': 'Zugriffsabsicht suchen',
    'policies.roles.search': 'Rollen suchen',
    'policies.roles.selected': 'Ausgewählte Rollen',
    'policies.roles.more': 'Alle Rollen anzeigen',
    'policies.roles.less': 'Weniger Rollen anzeigen',
    'policies.roles.empty': 'Keine passende Rolle',
    'policies.result.everyoneExcept': 'Alle außer {{roles}}',
    'policies.result.noRoles': 'Noch keine Rolle ausgewählt',
    'policies.result.noAction': 'diesen Zugriff nutzen',
    'policies.result.thisServer': 'diesem Server',
    'policies.result.sentence': '{{actors}} kann in {{target}} {{actions}}.',
  },
  es: {
    ...rebrand(phase4PoliciesPacks.es),
    'policies.subtitle': 'Elige una regla clara, selecciona a las personas y revisa el resultado antes de realizar cambios.',
    'policies.native.title': 'Intenciones sugeridas',
    'policies.origin.did': 'Sugerencia de Bunny',
    'policies.editor.empty': 'Elige una intención a la izquierda para configurar el acceso con palabras sencillas.',
    'policies.intent.search': 'Buscar una intención de acceso',
    'policies.roles.search': 'Buscar roles',
    'policies.roles.selected': 'Roles seleccionados',
    'policies.roles.more': 'Mostrar todos los roles',
    'policies.roles.less': 'Mostrar menos roles',
    'policies.roles.empty': 'Ningún rol coincide',
    'policies.result.everyoneExcept': 'Todos excepto {{roles}}',
    'policies.result.noRoles': 'Ningún rol seleccionado',
    'policies.result.noAction': 'usar este acceso',
    'policies.result.thisServer': 'este servidor',
    'policies.result.sentence': '{{actors}} puede {{actions}} en {{target}}.',
  },
}
