export const bunnyRolesPacks = {
  en: {
    'roles.eyebrow': 'Access management', 'roles.subtitle': 'Organize your community with clear, easy-to-understand roles.', 'roles.filters': 'Filter roles', 'roles.search': 'Search for a role', 'roles.group.all': 'All',
    'roles.group.administration': 'Administration', 'roles.group.administration.copy': 'Server management and full access', 'roles.group.moderation': 'Moderation', 'roles.group.moderation.copy': 'A safe and welcoming space', 'roles.group.community': 'Community', 'roles.group.community.copy': 'Members and community groups', 'roles.group.automation': 'Bots', 'roles.group.automation.copy': 'Automations and integrations',
    'roles.count': '{{count}} roles', 'roles.permissionsShort': '{{count}} abilities', 'roles.bunnyRole': 'Bunny', 'roles.system': 'System role',
    'roles.summary.managed': 'Managed automatically by Discord or an integration.', 'roles.summary.administration': 'Full access to the server and its settings.', 'roles.summary.moderation': 'Helps keep the community safe and welcoming.', 'roles.summary.organization': 'Organizes roles, channels and important settings.', 'roles.summary.participation': 'Can take part in community conversations.', 'roles.summary.visibility': 'Can see the spaces shared with this role.', 'roles.summary.identity': 'Identifies a group without additional base access.',
    'roles.capability.visibility': 'Visibility', 'roles.capability.visibility.copy': 'See server spaces at role level.', 'roles.capability.publication': 'Participation', 'roles.capability.publication.copy': 'Send messages or speak in permitted spaces.', 'roles.capability.moderation': 'Moderation', 'roles.capability.moderation.copy': 'Keep members and conversations safe.', 'roles.capability.administration': 'Administration', 'roles.capability.administration.copy': 'Manage the server, roles or channels.',
    'roles.status.enabled': 'Included', 'roles.status.notGranted': 'Not included', 'roles.capabilityState.loading': 'Bunny is checking this role', 'roles.capabilityState.error': 'The check could not be completed', 'roles.capabilityState.cannot': 'This role is protected', 'roles.capabilityState.unknown': 'A check is needed before editing', 'roles.discordDetails': 'Discord details',
  },
  fr: {
    'roles.eyebrow': 'Gestion des accès', 'roles.subtitle': 'Organisez votre communauté avec des rôles clairs et faciles à comprendre.', 'roles.filters': 'Filtrer les rôles', 'roles.search': 'Rechercher un rôle', 'roles.group.all': 'Tous',
    'roles.group.administration': 'Administration', 'roles.group.administration.copy': 'Gestion du serveur et accès complets', 'roles.group.moderation': 'Modération', 'roles.group.moderation.copy': 'Un espace sûr et bienveillant', 'roles.group.community': 'Communauté', 'roles.group.community.copy': 'Membres et groupes de la communauté', 'roles.group.automation': 'Bots', 'roles.group.automation.copy': 'Automatisations et intégrations',
    'roles.count': '{{count}} rôles', 'roles.permissionsShort': '{{count}} capacités', 'roles.bunnyRole': 'Bunny', 'roles.system': 'Rôle système',
    'roles.summary.managed': 'Géré automatiquement par Discord ou une intégration.', 'roles.summary.administration': 'Accès complet au serveur et à ses réglages.', 'roles.summary.moderation': 'Aide à garder une communauté sûre et bienveillante.', 'roles.summary.organization': 'Organise les rôles, les salons et les réglages importants.', 'roles.summary.participation': 'Peut participer aux échanges de la communauté.', 'roles.summary.visibility': 'Peut voir les espaces partagés avec ce rôle.', 'roles.summary.identity': 'Identifie un groupe sans accès de base supplémentaire.',
    'roles.capability.visibility': 'Visibilité', 'roles.capability.visibility.copy': 'Voir les espaces du serveur au niveau du rôle.', 'roles.capability.publication': 'Participation', 'roles.capability.publication.copy': 'Écrire ou parler dans les espaces autorisés.', 'roles.capability.moderation': 'Modération', 'roles.capability.moderation.copy': 'Veiller sur les membres et les échanges.', 'roles.capability.administration': 'Administration', 'roles.capability.administration.copy': 'Gérer le serveur, les rôles ou les salons.',
    'roles.status.enabled': 'Inclus', 'roles.status.notGranted': 'Non inclus', 'roles.capabilityState.loading': 'Bunny vérifie ce rôle', 'roles.capabilityState.error': 'La vérification n’a pas abouti', 'roles.capabilityState.cannot': 'Ce rôle est protégé', 'roles.capabilityState.unknown': 'Une vérification est nécessaire avant modification', 'roles.discordDetails': 'Détails Discord',
  },
  de: {
    'roles.eyebrow': 'Zugriffsverwaltung', 'roles.subtitle': 'Organisieren Sie Ihre Community mit klaren, leicht verständlichen Rollen.', 'roles.filters': 'Rollen filtern', 'roles.search': 'Rolle suchen', 'roles.group.all': 'Alle',
    'roles.group.administration': 'Administration', 'roles.group.administration.copy': 'Serververwaltung und vollständiger Zugriff', 'roles.group.moderation': 'Moderation', 'roles.group.moderation.copy': 'Ein sicherer und freundlicher Ort', 'roles.group.community': 'Community', 'roles.group.community.copy': 'Mitglieder und Community-Gruppen', 'roles.group.automation': 'Bots', 'roles.group.automation.copy': 'Automatisierungen und Integrationen',
    'roles.count': '{{count}} Rollen', 'roles.permissionsShort': '{{count}} Fähigkeiten', 'roles.bunnyRole': 'Bunny', 'roles.system': 'Systemrolle',
    'roles.summary.managed': 'Wird automatisch von Discord oder einer Integration verwaltet.', 'roles.summary.administration': 'Vollständiger Zugriff auf Server und Einstellungen.', 'roles.summary.moderation': 'Hilft, die Community sicher und freundlich zu halten.', 'roles.summary.organization': 'Organisiert Rollen, Kanäle und wichtige Einstellungen.', 'roles.summary.participation': 'Kann an Gesprächen der Community teilnehmen.', 'roles.summary.visibility': 'Kann die für diese Rolle freigegebenen Bereiche sehen.', 'roles.summary.identity': 'Kennzeichnet eine Gruppe ohne zusätzlichen Basiszugriff.',
    'roles.capability.visibility': 'Sichtbarkeit', 'roles.capability.visibility.copy': 'Serverbereiche auf Rollenebene sehen.', 'roles.capability.publication': 'Teilnahme', 'roles.capability.publication.copy': 'In erlaubten Bereichen schreiben oder sprechen.', 'roles.capability.moderation': 'Moderation', 'roles.capability.moderation.copy': 'Mitglieder und Gespräche schützen.', 'roles.capability.administration': 'Administration', 'roles.capability.administration.copy': 'Server, Rollen oder Kanäle verwalten.',
    'roles.status.enabled': 'Enthalten', 'roles.status.notGranted': 'Nicht enthalten', 'roles.capabilityState.loading': 'Bunny prüft diese Rolle', 'roles.capabilityState.error': 'Die Prüfung konnte nicht abgeschlossen werden', 'roles.capabilityState.cannot': 'Diese Rolle ist geschützt', 'roles.capabilityState.unknown': 'Vor der Bearbeitung ist eine Prüfung nötig', 'roles.discordDetails': 'Discord-Details',
  },
  es: {
    'roles.eyebrow': 'Gestión de accesos', 'roles.subtitle': 'Organiza tu comunidad con roles claros y fáciles de entender.', 'roles.filters': 'Filtrar roles', 'roles.search': 'Buscar un rol', 'roles.group.all': 'Todos',
    'roles.group.administration': 'Administración', 'roles.group.administration.copy': 'Gestión del servidor y acceso completo', 'roles.group.moderation': 'Moderación', 'roles.group.moderation.copy': 'Un espacio seguro y acogedor', 'roles.group.community': 'Comunidad', 'roles.group.community.copy': 'Miembros y grupos de la comunidad', 'roles.group.automation': 'Bots', 'roles.group.automation.copy': 'Automatizaciones e integraciones',
    'roles.count': '{{count}} roles', 'roles.permissionsShort': '{{count}} capacidades', 'roles.bunnyRole': 'Bunny', 'roles.system': 'Rol del sistema',
    'roles.summary.managed': 'Gestionado automáticamente por Discord o una integración.', 'roles.summary.administration': 'Acceso completo al servidor y sus ajustes.', 'roles.summary.moderation': 'Ayuda a mantener la comunidad segura y acogedora.', 'roles.summary.organization': 'Organiza roles, canales y ajustes importantes.', 'roles.summary.participation': 'Puede participar en las conversaciones de la comunidad.', 'roles.summary.visibility': 'Puede ver los espacios compartidos con este rol.', 'roles.summary.identity': 'Identifica un grupo sin acceso base adicional.',
    'roles.capability.visibility': 'Visibilidad', 'roles.capability.visibility.copy': 'Ver espacios del servidor a nivel de rol.', 'roles.capability.publication': 'Participación', 'roles.capability.publication.copy': 'Escribir o hablar en espacios permitidos.', 'roles.capability.moderation': 'Moderación', 'roles.capability.moderation.copy': 'Cuidar a los miembros y las conversaciones.', 'roles.capability.administration': 'Administración', 'roles.capability.administration.copy': 'Gestionar el servidor, los roles o los canales.',
    'roles.status.enabled': 'Incluido', 'roles.status.notGranted': 'No incluido', 'roles.capabilityState.loading': 'Bunny está comprobando este rol', 'roles.capabilityState.error': 'No se pudo completar la comprobación', 'roles.capabilityState.cannot': 'Este rol está protegido', 'roles.capabilityState.unknown': 'Es necesario comprobar antes de editar', 'roles.discordDetails': 'Detalles de Discord',
  },
} as const
