export const en = {
  'app.title': 'Discord Infrastructure Designer',
  'app.skip': 'Skip to main content',
  'auth.loading': 'Checking your session…',
  'auth.login': 'Continue with Discord',
  'auth.logout': 'Sign out',
  'auth.error': 'Authentication is unavailable. Please try again.',
  'auth.welcome': 'Design and operate your Discord infrastructure safely.',
  'guilds.title': 'Choose a server',
  'guilds.empty': 'No eligible Discord server was found.',
  'guilds.select': 'Open server',
  'guilds.pending': 'Setup required',
  'guilds.active': 'Active',
  'guilds.switch': 'Active server',
  'guilds.browser': 'Cross-server browser',
  'nav.structure': 'Structure',
  'nav.roles': 'Roles',
  'nav.permissions': 'Permissions',
  'nav.plans': 'Plans',
  'nav.diagnostics': 'Diagnostics',
  'nav.audit': 'Audit',
  'nav.templates': 'Templates',
  'nav.library': 'My library',
  'nav.clone': 'Clone',
  'nav.commands': 'Command palette',
  'common.loading': 'Loading…',
  'common.retry': 'Try again',
  'common.close': 'Close',
  'common.cancel': 'Cancel',
  'common.confirm': 'Confirm',
  'common.preview': 'Preview',
  'common.search': 'Search this server',
  'common.noResults': 'No matching item.',
  'common.selectedCount': '{{count}} selected',
  'common.unknown': 'Unknown',
  'common.stale': 'Stale data',
  'common.readOnly': 'Read only',
  'resource.guild': 'Server',
  'resource.category': 'Category',
  'resource.channel': 'Channel',
  'resource.thread': 'Thread',
  'resource.role': 'Role',
  'resource.artifact': 'Portable artifact',
  'resource.template': 'Template',
  'locale.label': 'Interface language',
  'locale.auto': 'Automatic (browser language)',
  'locale.en': 'English',
  'locale.fr': 'French',
  'locale.de': 'German',
  'locale.es': 'Spanish',
  'locale.flag.en': 'United Kingdom flag',
  'locale.flag.fr': 'France flag',
  'locale.flag.de': 'Germany flag',
  'locale.flag.es': 'Spain flag',
  'connection.live': 'Live updates connected',
  'connection.reconnecting': 'Reconnecting live updates',
  'structure.title': 'Discord structure',
  'structure.empty': 'No visible category or channel.',
  'structure.root': 'Uncategorized channels',
  'structure.category': 'Category',
  'structure.channel': 'Channel',
  'structure.thread': 'Thread',
  'structure.logical': 'DID logical group',
  'structure.hidden': 'Show hidden or deleted resources',
  'structure.properties': 'Properties',
  'structure.freshness': 'Freshness: {{value}}',
  'roles.title': 'Role hierarchy',
  'roles.empty': 'No cached role.',
  'roles.managed': 'Managed role',
  'roles.permissions': 'Permission bits: {{value}}',
  'roles.knownPermissions': '{{count}} recognized permissions',
  'roles.knownPermissions_one': '{{count}} recognized permission',
  'roles.knownPermissions_other': '{{count}} recognized permissions',
  'permissions.title': 'Permission explorer',
  'permissions.simple': 'Simple mode',
  'permissions.expert': 'Expert mode',
  'permissions.viewAs': 'View as',
  'permissions.member': 'Member',
  'permissions.role': 'Role',
  'permissions.newcomer': 'New member',
  'permissions.subject': 'Discord subject ID',
  'permissions.resource': 'Discord resource ID',
  'permissions.explain': 'Why access?',
  'permissions.result': 'Effective permissions: {{value}}',
  'permissions.adminWarning': 'ADMINISTRATOR bypasses channel overwrites.',
  'permissions.warning.generic': 'A permission caveat applies to this result.',
  'permissions.trace.generic': 'A permission rule was evaluated.',
  'permissions.trace.baseEveryone': 'Base permissions from the everyone role.',
  'permissions.trace.baseRole': 'Base permissions from the selected role.',
  'permissions.trace.baseRolesOr': 'Member role permissions were combined.',
  'permissions.trace.ownerBypass': 'The server owner bypass applies.',
  'permissions.trace.administratorBypass': 'The administrator bypass applies.',
  'permissions.trace.everyoneDeny': 'The everyone overwrite denied permissions.',
  'permissions.trace.roleDeniesAggregate': 'Role overwrites denied permissions.',
  'permissions.trace.memberDeny': 'The member overwrite denied permissions.',
  'permissions.trace.everyoneAllow': 'The everyone overwrite allowed permissions.',
  'permissions.trace.roleAllowsAggregate': 'Role overwrites allowed permissions.',
  'permissions.trace.memberAllow': 'The member overwrite allowed permissions.',
  'permissions.trace.threadInheritance': 'Thread permissions inherited from the parent channel.',
  'permissions.trace.implicitDenial': 'Discord implicit-denial rules were applied.',
  'permissions.trace.coverageIncomplete': 'The cached permission evidence is incomplete.',
  'plans.title': 'Plans and jobs',
  'plans.empty': 'No plan exists for this server.',
  'plans.risk': 'Risk: {{value}}',
  'plans.impact': 'Impact',
  'plans.preflight': 'Run preflight',
  'plans.confirm': 'Confirm plan',
  'plans.apply': 'Queue apply',
  'plans.cancel': 'Cancel plan',
  'plans.progress': 'Plan progress',
  'plans.progress.indeterminate': 'Progress is being updated.',
  'plans.progress.counts': '{{completed}} of {{total}} operations ({{percent}})',
  'plans.progress.created': 'Plan created.',
  'plans.progress.validated': 'Preflight passed.',
  'plans.progress.confirmed': 'Plan confirmed.',
  'plans.progress.applying': 'Applying plan.',
  'plans.progress.cancel_requested': 'Cancellation requested.',
  'plans.progress.cancelled': 'Plan cancelled.',
  'plans.progress.stale': 'Plan is stale.',
  'plans.progress.succeeded': 'Plan applied and verified.',
  'plans.progress.failed': 'Plan failed.',
  'plans.progress.partially_applied': 'Plan was partially applied.',
  'plans.progress.verification_failed': 'Verification failed.',
  'plans.progress.intervention_required': 'Manual intervention is required.',
  'plans.progress.preconditionRejected': 'A precondition rejected the operation.',
  'plans.progress.operationSucceeded': 'Operation succeeded.',
  'plans.progress.operationUnknown': 'Operation outcome is unknown.',
  'plans.progress.operationRetryScheduled': 'Operation retry scheduled.',
  'plans.progress.operationFailed': 'Operation failed.',
  'plans.status.draft': 'Draft',
  'plans.status.validated': 'Validated',
  'plans.status.confirmed': 'Confirmed',
  'plans.status.applying': 'Applying',
  'plans.status.cancel_requested': 'Cancellation requested',
  'plans.status.cancelled': 'Cancelled',
  'plans.status.stale': 'Stale',
  'plans.status.succeeded': 'Succeeded',
  'plans.status.failed': 'Failed',
  'plans.status.partially_applied': 'Partially applied',
  'plans.status.verification_failed': 'Verification failed',
  'plans.status.intervention_required': 'Intervention required',
  'risk.low': 'Low',
  'risk.medium': 'Medium',
  'risk.high': 'High',
  'plans.status': 'Status: {{value}}',
  'plans.queued': 'Queued; Discord has not yet been changed.',
  'plans.verified': 'Applied and verified.',
  'diagnostics.title': 'Diagnostics',
  'diagnostics.coverage': 'Cache coverage',
  'diagnostics.capabilities': 'Bot capabilities',
  'diagnostics.source': 'Source: local DID cache',
  'diagnostics.mode': 'Coverage',
  'diagnostics.freshness': 'Freshness',
  'diagnostics.state.full': 'Complete',
  'diagnostics.state.partial': 'Partial',
  'diagnostics.state.unknown': 'Unknown',
  'diagnostics.state.fresh': 'Current',
  'diagnostics.state.stale': 'Stale',
  'audit.title': 'Internal audit',
  'audit.empty': 'No audit event.',
  'audit.event.installation': 'Bot installation changed',
  'audit.event.plan': 'Plan state changed',
  'audit.event.portability': 'Portable resource operation',
  'audit.event.role': 'Role structure changed',
  'audit.event.structure': 'Server structure changed',
  'audit.event.generic': 'Infrastructure event',
  'audit.result.succeeded': 'Succeeded',
  'audit.result.observed': 'Observed',
  'audit.result.failed': 'Failed',
  'audit.result.stale': 'Stale',
  'audit.result.intervention': 'Intervention required',
  'artifact.channel': 'Channel',
  'artifact.category': 'Category',
  'artifact.logicalGroup': 'Logical group',
  'artifact.guildConfig': 'Server configuration',
  'artifact.customBundle': 'Custom bundle',
  'artifact.unknown': 'Portable resource',
  'templates.title': 'Templates',
  'templates.empty': 'No template for this server.',
  'library.title': 'Personal portable library',
  'library.empty': 'Your library is empty.',
  'library.export': 'Download portable file',
  'clone.title': 'Cross-server copy and clone',
  'clone.destination': 'Destination server',
  'clone.copy': 'Copy as new',
  'clone.merge': 'Merge compatible resources',
  'clone.reconcile': 'Reconcile clone',
  'clone.neverMove': 'The source is never moved or deleted.',
  'clone.mapping': 'Review destination mappings',
  'clone.previewReady': 'Transfer preview created.',
  'actions.open': 'Open details',
  'actions.open.description': 'Inspect the selected resource.',
  'actions.open.tooltip': 'Open the properties panel',
  'actions.move': 'Propose move',
  'actions.move.description': 'Create a same-server move proposal.',
  'actions.move.tooltip': 'Preview a move plan',
  'actions.copy': 'Copy as new',
  'actions.copy.description': 'Copy to an authorized destination server.',
  'actions.copy.tooltip': 'Preview a portable copy',
  'actions.clone': 'Clone with dependencies',
  'actions.clone.description': 'Clone supported dependencies through the portable pipeline.',
  'actions.clone.tooltip': 'Preview a dependency-aware clone',
  'actions.export': 'Save to my library',
  'actions.export.description': 'Create a private portable artifact.',
  'actions.export.tooltip': 'Export the selection',
  'actions.explain': 'Explain access',
  'actions.explain.description': 'Open the permission explanation.',
  'actions.explain.tooltip': 'Show why access is granted',
  'actions.bulk': 'Bulk preview',
  'actions.bulk.description': 'Preview one safe operation for the selection.',
  'actions.bulk.tooltip': 'Open bulk action preview',
  'actions.disabled.capability': 'Required capability is missing.',
  'actions.disabled.unknown': 'Capability cannot currently be verified.',
  'actions.disabled.target': 'This destination is not compatible.',
  'context.title': 'Available actions',
  'context.dropTitle': 'Choose a drop action',
  'commands.title': 'Command palette',
  'commands.placeholder': 'Search actions and pages',
  'commands.empty': 'No available command.',
  'gesture.movePreview': 'Move proposal ready.',
  'gesture.copyPreview': 'Cross-server copy preview ready.',
  'gesture.cancelled': 'Drag cancelled.',
  'gesture.invalid': 'Invalid drop target.',
  'dialog.previewTitle': 'Review proposed action',
  'dialog.noMutation': 'No Discord mutation occurs until a plan is confirmed and applied.',
  'errors.auth.required': 'Your session expired. Sign in again.',
  'errors.auth.csrf': 'The security token is invalid. Refresh your session.',
  'errors.authorization.denied': 'You are not allowed to perform this action.',
  'errors.resource.notFound': 'The requested resource was not found.',
  'errors.plans.notFound': 'The requested plan was not found.',
  'errors.plans.conflict': 'The plan changed. Reload its current version.',
  'errors.input.invalid': 'The submitted data is invalid.',
  'errors.network.offline': 'The service is unreachable. Check your connection.',
  'errors.generic': 'The operation could not be completed. Request: {{requestId}}',
  'a11y.openNavigation': 'Open navigation',
  'a11y.closeDialog': 'Close dialog',
  'a11y.tree': 'Discord resource tree',
  'a11y.contextMenu': 'Application context menu',
  'a11y.dragStarted': 'Drag started for {{name}}.',
  'a11y.dragTarget': 'Drop target {{name}}.',
} as const

export type MessageKey = keyof typeof en
export type BootstrapLocaleCode = 'en' | 'fr' | 'de' | 'es'
export type LocaleCode = string
export type MessagePack = Record<MessageKey, string>

const translated = (values: MessagePack): MessagePack => values

export const fr = translated({
  'app.skip': 'Aller au contenu principal', 'auth.loading': 'Vérification de votre session…',
  'auth.login': 'Continuer avec Discord', 'auth.logout': 'Se déconnecter',
  'auth.error': "L’authentification est indisponible. Réessayez.",
  'auth.welcome': 'Concevez et exploitez votre infrastructure Discord en toute sécurité.',
  'guilds.title': 'Choisir un serveur', 'guilds.empty': 'Àucun serveur Discord admissible trouvé.',
  'guilds.select': 'Ouvrir le serveur', 'guilds.pending': 'Configuration requise',
  'guilds.active': 'Actif', 'guilds.switch': 'Serveur actif', 'guilds.browser': 'Explorateur inter-serveurs',
  'nav.structure': 'Structure', 'nav.roles': 'Rôles', 'nav.permissions': 'Permissions',
  'nav.plans': 'Plans', 'nav.diagnostics': 'Diagnostics', 'nav.audit': 'Audit',
  'nav.templates': 'Modèles', 'nav.library': 'Ma bibliothèque', 'nav.clone': 'Cloner',
  'nav.commands': 'Palette de commandes', 'common.loading': 'Chargement…',
  'common.retry': 'Réessayer', 'common.close': 'Fermer', 'common.cancel': 'Annuler',
  'common.confirm': 'Confirmer', 'common.preview': 'Prévisualiser', 'common.search': 'Rechercher dans ce serveur',
  'common.noResults': 'Aucun élément correspondant.', 'common.selectedCount': '{{count}} sélectionné(s)',
  'common.unknown': 'Inconnu', 'common.stale': 'Données obsolètes', 'common.readOnly': 'Lecture seule',
  'resource.guild': 'Serveur', 'resource.category': 'Catégorie', 'resource.channel': 'Salon', 'resource.thread': 'Thread',
  'resource.role': 'Rôle', 'resource.artifact': 'Artifact portable', 'resource.template': 'Modèle',
  'locale.label': "Langue de l’interface", 'locale.auto': 'Automatique (langue du navigateur)',
  'locale.en': 'Anglais', 'locale.fr': 'Français', 'locale.de': 'Allemand', 'locale.es': 'Espagnol',
  'locale.flag.en': 'Drapeau du Royaume-Uni', 'locale.flag.fr': 'Drapeau de la France',
  'locale.flag.de': "Drapeau de l’Allemagne", 'locale.flag.es': "Drapeau de l’Espagne",
  'connection.live': 'Mises à jour en direct connectées', 'connection.reconnecting': 'Reconnexion aux mises à jour',
  'structure.title': 'Structure Discord', 'structure.empty': 'Aucune catégorie ou salon visible.',
  'structure.root': 'Salons sans catégorie', 'structure.category': 'Catégorie', 'structure.channel': 'Salon',
  'structure.thread': 'Thread', 'structure.logical': 'Groupe logique DID',
  'structure.hidden': 'Afficher les ressources masquées ou supprimées', 'structure.properties': 'Propriétés',
  'structure.freshness': 'Fraîcheur : {{value}}', 'roles.title': 'Hiérarchie des rôles',
  'roles.empty': 'Aucun rôle en cache.', 'roles.managed': 'Rôle géré', 'roles.permissions': 'Bits de permission : {{value}}',
  'roles.knownPermissions': '{{count}} permissions reconnues', 'permissions.warning.generic': 'Une réserve de permission s’applique à ce résultat.',
  'roles.knownPermissions_one': '{{count}} permission reconnue', 'roles.knownPermissions_other': '{{count}} permissions reconnues',
  'permissions.trace.generic': 'Une règle de permission a été évaluée.',
  'permissions.title': 'Explorateur de permissions', 'permissions.simple': 'Mode simple',
  'permissions.expert': 'Mode expert', 'permissions.viewAs': 'Voir comme', 'permissions.member': 'Membre',
  'permissions.role': 'Rôle', 'permissions.newcomer': 'Nouveau membre',
  'permissions.subject': 'ID Discord du sujet', 'permissions.resource': 'ID Discord de la ressource',
  'permissions.explain': "Pourquoi cet accès ?", 'permissions.result': 'Permissions effectives : {{value}}',
  'permissions.adminWarning': 'ADMINISTRATOR contourne les overwrites des salons.',
  'plans.title': 'Plans et jobs', 'plans.empty': "Aucun plan n’existe pour ce serveur.",
  'plans.risk': 'Risque : {{value}}', 'plans.impact': 'Impact', 'plans.preflight': 'Lancer le preflight',
  'plans.confirm': 'Confirmer le plan', 'plans.apply': "Mettre l’application en file", 'plans.cancel': 'Annuler le plan',
  'plans.progress': 'Progression du plan', 'plans.status': 'Statut : {{value}}',
  'plans.progress.indeterminate': 'La progression est en cours de mise à jour.', 'plans.progress.applying': 'Application du plan.',
  'plans.progress.counts': '{{completed}} opérations sur {{total}} ({{percent}})',
  'plans.progress.succeeded': 'Plan appliqué et vérifié.', 'plans.progress.failed': 'Échec du plan.',
  'plans.progress.verification_failed': 'Échec de la vérification.', 'plans.progress.intervention_required': 'Une intervention manuelle est requise.',
  'plans.status.applying': 'Application', 'plans.status.succeeded': 'Réussi', 'plans.status.failed': 'Échoué',
  'plans.status.verification_failed': 'Échec de la vérification', 'risk.low': 'Faible', 'risk.medium': 'Moyen', 'risk.high': 'Élevé',
  'plans.queued': "En file ; Discord n’a pas encore été modifié.", 'plans.verified': 'Appliqué et vérifié.',
  'diagnostics.title': 'Diagnostics', 'diagnostics.coverage': 'Couverture du cache',
  'diagnostics.capabilities': 'Capacités du bot', 'diagnostics.source': 'Source : cache local DID',
  'diagnostics.mode': 'Couverture', 'diagnostics.freshness': 'Fraîcheur', 'diagnostics.state.full': 'Complète',
  'diagnostics.state.partial': 'Partielle', 'diagnostics.state.unknown': 'Inconnue', 'diagnostics.state.fresh': 'À jour', 'diagnostics.state.stale': 'Obsolète',
  'audit.title': 'Audit interne', 'audit.empty': "Aucun événement d’audit.",
  'audit.event.installation': 'Installation du bot modifiée', 'audit.event.plan': 'État du plan modifié',
  'audit.event.portability': 'Opération sur une ressource portable', 'audit.event.role': 'Structure des rôles modifiée',
  'audit.event.structure': 'Structure du serveur modifiée', 'audit.event.generic': 'Événement d’infrastructure',
  'audit.result.succeeded': 'Réussi', 'audit.result.observed': 'Observé', 'audit.result.failed': 'Échoué',
  'audit.result.stale': 'Obsolète', 'audit.result.intervention': 'Intervention requise',
  'artifact.channel': 'Salon', 'artifact.category': 'Catégorie', 'artifact.logicalGroup': 'Groupe logique',
  'artifact.guildConfig': 'Configuration du serveur', 'artifact.customBundle': 'Ensemble personnalisé', 'artifact.unknown': 'Ressource portable',
  'templates.title': 'Modèles', 'templates.empty': 'Aucun modèle pour ce serveur.',
  'library.title': 'Bibliothèque portable personnelle', 'library.empty': 'Votre bibliothèque est vide.',
  'library.export': 'Télécharger le fichier portable', 'clone.title': 'Copie et clonage inter-serveurs',
  'clone.destination': 'Serveur de destination', 'clone.copy': 'Copier comme nouveau',
  'clone.merge': 'Fusionner les ressources compatibles', 'clone.reconcile': 'Réconcilier le clone',
  'clone.neverMove': "La source n’est jamais déplacée ni supprimée.", 'clone.mapping': 'Vérifier les mappings destination',
  'clone.previewReady': 'Prévisualisation du transfert créée.',
  'actions.open': 'Ouvrir les détails', 'actions.open.description': 'Examiner la ressource sélectionnée.',
  'actions.open.tooltip': 'Ouvrir le panneau de propriétés', 'actions.move': 'Proposer un déplacement',
  'actions.move.description': 'Créer une proposition de déplacement dans le même serveur.',
  'actions.move.tooltip': 'Prévisualiser un plan de déplacement', 'actions.copy': 'Copier comme nouveau',
  'actions.copy.description': 'Copier vers un serveur de destination autorisé.',
  'actions.copy.tooltip': 'Prévisualiser une copie portable', 'actions.clone': 'Cloner avec les dépendances',
  'actions.clone.description': 'Cloner les dépendances supportées par le pipeline portable.',
  'actions.clone.tooltip': 'Prévisualiser un clone avec dépendances', 'actions.export': 'Enregistrer dans ma bibliothèque',
  'actions.export.description': 'Créer un artifact portable privé.', 'actions.export.tooltip': 'Exporter la sélection',
  'actions.explain': "Expliquer l’accès", 'actions.explain.description': "Ouvrir l’explication des permissions.",
  'actions.explain.tooltip': "Montrer pourquoi l’accès est accordé", 'actions.bulk': 'Prévisualisation groupée',
  'actions.bulk.description': 'Prévisualiser une opération sûre pour la sélection.',
  'actions.bulk.tooltip': "Ouvrir la prévisualisation de l’action groupée",
  'actions.disabled.capability': 'La capacité requise est absente.', 'actions.disabled.unknown': 'La capacité ne peut pas être vérifiée actuellement.', 'actions.disabled.target': "Cette destination n’est pas compatible.",
  'context.title': 'Actions disponibles', 'context.dropTitle': 'Choisir une action de dépôt',
  'commands.title': 'Palette de commandes', 'commands.placeholder': 'Rechercher des actions et pages',
  'commands.empty': 'Aucune commande disponible.', 'gesture.movePreview': 'Proposition de déplacement prête.',
  'gesture.copyPreview': 'Prévisualisation de copie inter-serveurs prête.', 'gesture.cancelled': 'Glisser annulé.',
  'gesture.invalid': 'Cible de dépôt invalide.', 'dialog.previewTitle': "Vérifier l’action proposée",
  'dialog.noMutation': "Aucune mutation Discord avant confirmation et application d’un plan.",
  'errors.auth.required': 'Votre session a expiré. Reconnectez-vous.',
  'errors.auth.csrf': 'Le jeton de sécurité est invalide. Actualisez votre session.',
  'errors.authorization.denied': "Vous n’êtes pas autorisé à effectuer cette action.",
  'errors.resource.notFound': 'La ressource demandée est introuvable.',
  'errors.plans.notFound': 'Le plan demandé est introuvable.', 'errors.plans.conflict': 'Le plan a changé. Rechargez sa version actuelle.',
  'errors.input.invalid': 'Les données envoyées sont invalides.', 'errors.network.offline': 'Le service est inaccessible. Vérifiez votre connexion.',
  'errors.generic': "L’opération a échoué. Requête : {{requestId}}",
  'a11y.openNavigation': 'Ouvrir la navigation', 'a11y.closeDialog': 'Fermer la boîte de dialogue',
  'a11y.tree': 'Arbre des ressources Discord', 'a11y.contextMenu': "Menu contextuel de l’application",
  'a11y.dragStarted': 'Glisser commencé pour {{name}}.', 'a11y.dragTarget': 'Cible de dépôt {{name}}.',
  'app.title': 'Discord Infrastructure Designer',
  'permissions.trace.baseEveryone': 'Permissions de base du rôle tout le monde.', 'permissions.trace.baseRole': 'Permissions de base du rôle sélectionné.',
  'permissions.trace.baseRolesOr': 'Les permissions des rôles du membre ont été combinées.', 'permissions.trace.ownerBypass': 'Le contournement du propriétaire du serveur s’applique.',
  'permissions.trace.administratorBypass': 'Le contournement administrateur s’applique.', 'permissions.trace.everyoneDeny': 'L’overwrite tout le monde a refusé des permissions.',
  'permissions.trace.roleDeniesAggregate': 'Les overwrites de rôles ont refusé des permissions.', 'permissions.trace.memberDeny': 'L’overwrite du membre a refusé des permissions.',
  'permissions.trace.everyoneAllow': 'L’overwrite tout le monde a autorisé des permissions.', 'permissions.trace.roleAllowsAggregate': 'Les overwrites de rôles ont autorisé des permissions.',
  'permissions.trace.memberAllow': 'L’overwrite du membre a autorisé des permissions.', 'permissions.trace.threadInheritance': 'Les permissions du thread proviennent du salon parent.',
  'permissions.trace.implicitDenial': 'Les règles de refus implicite de Discord ont été appliquées.', 'permissions.trace.coverageIncomplete': 'Les preuves de permission en cache sont incomplètes.',
  'plans.progress.created': 'Plan créé.', 'plans.progress.validated': 'Preflight validé.', 'plans.progress.confirmed': 'Plan confirmé.',
  'plans.progress.cancel_requested': 'Annulation demandée.', 'plans.progress.cancelled': 'Plan annulé.', 'plans.progress.stale': 'Le plan est obsolète.',
  'plans.progress.partially_applied': 'Le plan a été partiellement appliqué.', 'plans.progress.preconditionRejected': 'Une précondition a refusé l’opération.',
  'plans.progress.operationSucceeded': 'Opération réussie.', 'plans.progress.operationUnknown': 'Le résultat de l’opération est inconnu.',
  'plans.progress.operationRetryScheduled': 'Nouvelle tentative de l’opération planifiée.', 'plans.progress.operationFailed': 'Échec de l’opération.',
  'plans.status.draft': 'Brouillon', 'plans.status.validated': 'Validé', 'plans.status.confirmed': 'Confirmé',
  'plans.status.cancel_requested': 'Annulation demandée', 'plans.status.cancelled': 'Annulé', 'plans.status.stale': 'Obsolète',
  'plans.status.partially_applied': 'Partiellement appliqué', 'plans.status.intervention_required': 'Intervention requise',
})

export const de = translated({
  'app.skip': 'Zum Hauptinhalt springen', 'auth.loading': 'Sitzung wird geprüft…',
  'auth.login': 'Mit Discord fortfahren', 'auth.logout': 'Abmelden',
  'auth.error': 'Die Anmeldung ist nicht verfügbar. Bitte erneut versuchen.',
  'auth.welcome': 'Discord-Infrastruktur sicher entwerfen und betreiben.',
  'guilds.title': 'Server auswählen', 'guilds.empty': 'Kein geeigneter Discord-Server gefunden.',
  'guilds.select': 'Server öffnen', 'guilds.pending': 'Einrichtung erforderlich', 'guilds.active': 'Aktiv',
  'guilds.switch': 'Aktiver Server', 'guilds.browser': 'Serverübergreifender Browser',
  'nav.roles': 'Rollen', 'nav.permissions': 'Berechtigungen', 'nav.plans': 'Pläne',
  'nav.diagnostics': 'Diagnose', 'nav.audit': 'Prüfprotokoll', 'nav.templates': 'Vorlagen',
  'nav.library': 'Meine Bibliothek', 'nav.clone': 'Klonen', 'nav.commands': 'Befehlspalette',
  'common.loading': 'Wird geladen…', 'common.retry': 'Erneut versuchen', 'common.close': 'Schließen',
  'common.cancel': 'Abbrechen', 'common.confirm': 'Bestätigen', 'common.preview': 'Vorschau',
  'common.search': 'Diesen Server durchsuchen', 'common.noResults': 'Kein passender Eintrag.',
  'common.selectedCount': '{{count}} ausgewählt', 'common.unknown': 'Unbekannt',
  'common.stale': 'Veraltete Daten', 'common.readOnly': 'Nur lesen',
  'resource.guild': 'Server', 'resource.category': 'Kategorie', 'resource.channel': 'Kanal', 'resource.thread': 'Thread',
  'resource.role': 'Rolle', 'resource.artifact': 'Portables Artefakt', 'resource.template': 'Vorlage',
  'locale.label': 'Oberflächensprache', 'locale.auto': 'Automatisch (Browsersprache)',
  'locale.en': 'Englisch', 'locale.fr': 'Französisch', 'locale.de': 'Deutsch', 'locale.es': 'Spanisch',
  'locale.flag.en': 'Flagge des Vereinigten Königreichs', 'locale.flag.fr': 'Flagge Frankreichs',
  'locale.flag.de': 'Flagge Deutschlands', 'locale.flag.es': 'Flagge Spaniens',
  'connection.live': 'Live-Aktualisierungen verbunden', 'connection.reconnecting': 'Live-Aktualisierungen werden neu verbunden',
  'structure.title': 'Discord-Struktur', 'structure.empty': 'Keine sichtbare Kategorie oder kein sichtbarer Kanal.',
  'structure.root': 'Kanäle ohne Kategorie', 'structure.category': 'Kategorie', 'structure.channel': 'Kanal',
  'structure.thread': 'Thread', 'structure.logical': 'Logische DID-Gruppe',
  'structure.hidden': 'Ausgeblendete oder gelöschte Ressourcen anzeigen', 'structure.properties': 'Eigenschaften',
  'structure.freshness': 'Aktualität: {{value}}', 'roles.title': 'Rollenhierarchie',
  'roles.empty': 'Keine Rolle im Cache.', 'roles.managed': 'Verwaltete Rolle', 'roles.permissions': 'Berechtigungsbits: {{value}}',
  'roles.knownPermissions': '{{count}} erkannte Berechtigungen', 'permissions.warning.generic': 'Für dieses Ergebnis gilt ein Berechtigungshinweis.',
  'roles.knownPermissions_one': '{{count}} erkannte Berechtigung', 'roles.knownPermissions_other': '{{count}} erkannte Berechtigungen',
  'permissions.trace.generic': 'Eine Berechtigungsregel wurde ausgewertet.',
  'permissions.title': 'Berechtigungs-Explorer', 'permissions.simple': 'Einfacher Modus',
  'permissions.expert': 'Expertenmodus', 'permissions.viewAs': 'Anzeigen als', 'permissions.member': 'Mitglied',
  'permissions.role': 'Rolle', 'permissions.newcomer': 'Neues Mitglied',
  'permissions.subject': 'Discord-Subjekt-ID', 'permissions.resource': 'Discord-Ressourcen-ID',
  'permissions.explain': 'Warum Zugriff?', 'permissions.result': 'Effektive Berechtigungen: {{value}}',
  'permissions.adminWarning': 'ADMINISTRATOR umgeht Kanalüberschreibungen.',
  'plans.title': 'Pläne und Jobs', 'plans.empty': 'Für diesen Server ist kein Plan vorhanden.',
  'plans.risk': 'Risiko: {{value}}', 'plans.impact': 'Auswirkung', 'plans.preflight': 'Vorprüfung starten',
  'plans.confirm': 'Plan bestätigen', 'plans.apply': 'Anwendung einreihen', 'plans.cancel': 'Plan abbrechen',
  'plans.progress': 'Planfortschritt', 'plans.status': 'Status: {{value}}',
  'plans.progress.indeterminate': 'Der Fortschritt wird aktualisiert.', 'plans.progress.applying': 'Plan wird angewendet.',
  'plans.progress.counts': '{{completed}} von {{total}} Vorgängen ({{percent}})',
  'plans.progress.succeeded': 'Plan angewendet und verifiziert.', 'plans.progress.failed': 'Plan fehlgeschlagen.',
  'plans.progress.verification_failed': 'Verifizierung fehlgeschlagen.', 'plans.progress.intervention_required': 'Manuelles Eingreifen ist erforderlich.',
  'plans.status.applying': 'Wird angewendet', 'plans.status.succeeded': 'Erfolgreich', 'plans.status.failed': 'Fehlgeschlagen',
  'plans.status.verification_failed': 'Verifizierung fehlgeschlagen', 'risk.low': 'Niedrig', 'risk.medium': 'Mittel', 'risk.high': 'Hoch',
  'plans.queued': 'Eingereiht; Discord wurde noch nicht geändert.', 'plans.verified': 'Angewendet und verifiziert.',
  'diagnostics.title': 'Diagnose', 'diagnostics.coverage': 'Cache-Abdeckung',
  'diagnostics.capabilities': 'Bot-Fähigkeiten', 'diagnostics.source': 'Quelle: lokaler DID-Cache',
  'diagnostics.mode': 'Abdeckung', 'diagnostics.freshness': 'Aktualität', 'diagnostics.state.full': 'Vollständig',
  'diagnostics.state.partial': 'Teilweise', 'diagnostics.state.unknown': 'Unbekannt', 'diagnostics.state.fresh': 'Aktuell', 'diagnostics.state.stale': 'Veraltet',
  'audit.title': 'Internes Prüfprotokoll', 'audit.empty': 'Kein Prüfereignis.',
  'audit.event.installation': 'Bot-Installation geändert', 'audit.event.plan': 'Planstatus geändert',
  'audit.event.portability': 'Vorgang mit portabler Ressource', 'audit.event.role': 'Rollenstruktur geändert',
  'audit.event.structure': 'Serverstruktur geändert', 'audit.event.generic': 'Infrastrukturereignis',
  'audit.result.succeeded': 'Erfolgreich', 'audit.result.observed': 'Beobachtet', 'audit.result.failed': 'Fehlgeschlagen',
  'audit.result.stale': 'Veraltet', 'audit.result.intervention': 'Eingreifen erforderlich',
  'artifact.channel': 'Kanal', 'artifact.category': 'Kategorie', 'artifact.logicalGroup': 'Logische Gruppe',
  'artifact.guildConfig': 'Serverkonfiguration', 'artifact.customBundle': 'Benutzerdefiniertes Paket', 'artifact.unknown': 'Portable Ressource',
  'templates.title': 'Vorlagen', 'templates.empty': 'Keine Vorlage für diesen Server.',
  'library.title': 'Persönliche portable Bibliothek', 'library.empty': 'Ihre Bibliothek ist leer.',
  'library.export': 'Portable Datei herunterladen', 'clone.title': 'Serverübergreifend kopieren und klonen',
  'clone.destination': 'Zielserver', 'clone.copy': 'Als neu kopieren', 'clone.merge': 'Kompatible Ressourcen zusammenführen',
  'clone.reconcile': 'Klon abgleichen', 'clone.neverMove': 'Die Quelle wird niemals verschoben oder gelöscht.',
  'clone.mapping': 'Zielzuordnungen prüfen', 'context.title': 'Verfügbare Aktionen',
  'clone.previewReady': 'Transfervorschau erstellt.',
  'actions.open': 'Details öffnen', 'actions.open.description': 'Die ausgewählte Ressource untersuchen.',
  'actions.open.tooltip': 'Eigenschaften öffnen', 'actions.move': 'Verschiebung vorschlagen',
  'actions.move.description': 'Einen Verschiebevorschlag auf demselben Server erstellen.',
  'actions.move.tooltip': 'Verschiebeplan anzeigen', 'actions.copy': 'Als neu kopieren',
  'actions.copy.description': 'Auf einen autorisierten Zielserver kopieren.', 'actions.copy.tooltip': 'Portable Kopie anzeigen',
  'actions.clone': 'Mit Abhängigkeiten klonen', 'actions.clone.description': 'Unterstützte Abhängigkeiten über die portable Pipeline klonen.',
  'actions.clone.tooltip': 'Abhängigkeitsbewussten Klon anzeigen', 'actions.export': 'In meiner Bibliothek speichern',
  'actions.export.description': 'Ein privates portables Artefakt erstellen.', 'actions.export.tooltip': 'Auswahl exportieren',
  'actions.explain': 'Zugriff erklären', 'actions.explain.description': 'Die Berechtigungserklärung öffnen.',
  'actions.explain.tooltip': 'Grund für den Zugriff anzeigen', 'actions.bulk': 'Sammelvorschau',
  'actions.bulk.description': 'Einen sicheren Vorgang für die Auswahl anzeigen.',
  'actions.bulk.tooltip': 'Sammelaktionsvorschau öffnen', 'actions.disabled.capability': 'Die erforderliche Fähigkeit fehlt.',
  'actions.disabled.unknown': 'Die Fähigkeit kann derzeit nicht überprüft werden.',
  'actions.disabled.target': 'Dieses Ziel ist nicht kompatibel.',
  'context.dropTitle': 'Ablageaktion auswählen', 'commands.title': 'Befehlspalette',
  'commands.placeholder': 'Aktionen und Seiten durchsuchen', 'commands.empty': 'Kein Befehl verfügbar.',
  'gesture.movePreview': 'Verschiebevorschlag bereit.', 'gesture.copyPreview': 'Serverübergreifende Kopiervorschau bereit.',
  'gesture.cancelled': 'Ziehen abgebrochen.', 'gesture.invalid': 'Ungültiges Ablageziel.',
  'dialog.previewTitle': 'Vorgeschlagene Aktion prüfen',
  'dialog.noMutation': 'Discord wird erst nach Bestätigung und Anwendung eines Plans geändert.',
  'errors.auth.required': 'Ihre Sitzung ist abgelaufen. Bitte erneut anmelden.',
  'errors.auth.csrf': 'Das Sicherheitstoken ist ungültig. Aktualisieren Sie die Sitzung.',
  'errors.authorization.denied': 'Sie dürfen diese Aktion nicht ausführen.',
  'errors.resource.notFound': 'Die angeforderte Ressource wurde nicht gefunden.',
  'errors.plans.notFound': 'Der angeforderte Plan wurde nicht gefunden.',
  'errors.plans.conflict': 'Der Plan wurde geändert. Laden Sie die aktuelle Version.',
  'errors.input.invalid': 'Die gesendeten Daten sind ungültig.', 'errors.network.offline': 'Der Dienst ist nicht erreichbar.',
  'errors.generic': 'Der Vorgang konnte nicht abgeschlossen werden. Anfrage: {{requestId}}',
  'a11y.openNavigation': 'Navigation öffnen', 'a11y.closeDialog': 'Dialog schließen',
  'a11y.tree': 'Discord-Ressourcenbaum', 'a11y.contextMenu': 'Kontextmenü der Anwendung',
  'a11y.dragStarted': 'Ziehen für {{name}} gestartet.', 'a11y.dragTarget': 'Ablageziel {{name}}.',
  'app.title': 'Discord Infrastructure Designer', 'nav.structure': 'Struktur',
  'permissions.trace.baseEveryone': 'Basisberechtigungen der Jeder-Rolle.', 'permissions.trace.baseRole': 'Basisberechtigungen der ausgewählten Rolle.',
  'permissions.trace.baseRolesOr': 'Die Rollenberechtigungen des Mitglieds wurden kombiniert.', 'permissions.trace.ownerBypass': 'Die Umgehung für den Serverbesitzer gilt.',
  'permissions.trace.administratorBypass': 'Die Administrator-Umgehung gilt.', 'permissions.trace.everyoneDeny': 'Der Jeder-Overwrite hat Berechtigungen verweigert.',
  'permissions.trace.roleDeniesAggregate': 'Rollen-Overwrites haben Berechtigungen verweigert.', 'permissions.trace.memberDeny': 'Der Mitglied-Overwrite hat Berechtigungen verweigert.',
  'permissions.trace.everyoneAllow': 'Der Jeder-Overwrite hat Berechtigungen erlaubt.', 'permissions.trace.roleAllowsAggregate': 'Rollen-Overwrites haben Berechtigungen erlaubt.',
  'permissions.trace.memberAllow': 'Der Mitglied-Overwrite hat Berechtigungen erlaubt.', 'permissions.trace.threadInheritance': 'Thread-Berechtigungen wurden vom übergeordneten Kanal geerbt.',
  'permissions.trace.implicitDenial': 'Die impliziten Discord-Verweigerungsregeln wurden angewendet.', 'permissions.trace.coverageIncomplete': 'Die zwischengespeicherten Berechtigungsnachweise sind unvollständig.',
  'plans.progress.created': 'Plan erstellt.', 'plans.progress.validated': 'Vorprüfung bestanden.', 'plans.progress.confirmed': 'Plan bestätigt.',
  'plans.progress.cancel_requested': 'Abbruch angefordert.', 'plans.progress.cancelled': 'Plan abgebrochen.', 'plans.progress.stale': 'Plan ist veraltet.',
  'plans.progress.partially_applied': 'Plan wurde teilweise angewendet.', 'plans.progress.preconditionRejected': 'Eine Vorbedingung hat den Vorgang abgelehnt.',
  'plans.progress.operationSucceeded': 'Vorgang erfolgreich.', 'plans.progress.operationUnknown': 'Das Vorgangsergebnis ist unbekannt.',
  'plans.progress.operationRetryScheduled': 'Wiederholung des Vorgangs geplant.', 'plans.progress.operationFailed': 'Vorgang fehlgeschlagen.',
  'plans.status.draft': 'Entwurf', 'plans.status.validated': 'Validiert', 'plans.status.confirmed': 'Bestätigt',
  'plans.status.cancel_requested': 'Abbruch angefordert', 'plans.status.cancelled': 'Abgebrochen', 'plans.status.stale': 'Veraltet',
  'plans.status.partially_applied': 'Teilweise angewendet', 'plans.status.intervention_required': 'Eingreifen erforderlich',
})

export const es = translated({
  'app.skip': 'Saltar al contenido principal', 'auth.loading': 'Comprobando tu sesión…',
  'auth.login': 'Continuar con Discord', 'auth.logout': 'Cerrar sesión',
  'auth.error': 'La autenticación no está disponible. Inténtalo de nuevo.',
  'auth.welcome': 'Diseña y opera tu infraestructura de Discord de forma segura.',
  'guilds.title': 'Elegir un servidor', 'guilds.empty': 'No se encontró ningún servidor de Discord apto.',
  'guilds.select': 'Abrir servidor', 'guilds.pending': 'Configuración necesaria', 'guilds.active': 'Activo',
  'guilds.switch': 'Servidor activo', 'guilds.browser': 'Explorador entre servidores',
  'nav.roles': 'Roles', 'nav.permissions': 'Permisos', 'nav.plans': 'Planes',
  'nav.diagnostics': 'Diagnósticos', 'nav.audit': 'Auditoría', 'nav.templates': 'Plantillas',
  'nav.library': 'Mi biblioteca', 'nav.clone': 'Clonar', 'nav.commands': 'Paleta de comandos',
  'common.loading': 'Cargando…', 'common.retry': 'Reintentar', 'common.close': 'Cerrar',
  'common.cancel': 'Cancelar', 'common.confirm': 'Confirmar', 'common.preview': 'Vista previa',
  'common.search': 'Buscar en este servidor', 'common.noResults': 'No hay elementos coincidentes.',
  'common.selectedCount': '{{count}} seleccionados', 'common.unknown': 'Desconocido',
  'common.stale': 'Datos obsoletos', 'common.readOnly': 'Solo lectura',
  'resource.guild': 'Servidor', 'resource.category': 'Categoría', 'resource.channel': 'Canal', 'resource.thread': 'Hilo',
  'resource.role': 'Rol', 'resource.artifact': 'Artefacto portátil', 'resource.template': 'Plantilla',
  'locale.label': 'Idioma de la interfaz', 'locale.auto': 'Automático (idioma del navegador)',
  'locale.en': 'Inglés', 'locale.fr': 'Francés', 'locale.de': 'Alemán', 'locale.es': 'Español',
  'locale.flag.en': 'Bandera del Reino Unido', 'locale.flag.fr': 'Bandera de Francia',
  'locale.flag.de': 'Bandera de Alemania', 'locale.flag.es': 'Bandera de España',
  'connection.live': 'Actualizaciones en vivo conectadas', 'connection.reconnecting': 'Reconectando las actualizaciones en vivo',
  'structure.title': 'Estructura de Discord', 'structure.empty': 'No hay categorías ni canales visibles.',
  'structure.root': 'Canales sin categoría', 'structure.category': 'Categoría', 'structure.channel': 'Canal',
  'structure.thread': 'Hilo', 'structure.logical': 'Grupo lógico DID',
  'structure.hidden': 'Mostrar recursos ocultos o eliminados', 'structure.properties': 'Propiedades',
  'structure.freshness': 'Actualización: {{value}}', 'roles.title': 'Jerarquía de roles',
  'roles.empty': 'No hay roles en caché.', 'roles.managed': 'Rol gestionado', 'roles.permissions': 'Bits de permiso: {{value}}',
  'roles.knownPermissions': '{{count}} permisos reconocidos', 'permissions.warning.generic': 'Se aplica una advertencia de permisos a este resultado.',
  'roles.knownPermissions_one': '{{count}} permiso reconocido', 'roles.knownPermissions_other': '{{count}} permisos reconocidos',
  'permissions.trace.generic': 'Se evaluó una regla de permisos.',
  'permissions.title': 'Explorador de permisos', 'permissions.simple': 'Modo simple',
  'permissions.expert': 'Modo experto', 'permissions.viewAs': 'Ver como', 'permissions.member': 'Miembro',
  'permissions.role': 'Rol', 'permissions.newcomer': 'Miembro nuevo',
  'permissions.subject': 'ID del sujeto de Discord', 'permissions.resource': 'ID del recurso de Discord',
  'permissions.explain': '¿Por qué tiene acceso?', 'permissions.result': 'Permisos efectivos: {{value}}',
  'permissions.adminWarning': 'ADMINISTRATOR omite las sobrescrituras del canal.',
  'plans.title': 'Planes y trabajos', 'plans.empty': 'No existe ningún plan para este servidor.',
  'plans.risk': 'Riesgo: {{value}}', 'plans.impact': 'Impacto', 'plans.preflight': 'Ejecutar comprobación previa',
  'plans.confirm': 'Confirmar plan', 'plans.apply': 'Encolar aplicación', 'plans.cancel': 'Cancelar plan',
  'plans.progress': 'Progreso del plan', 'plans.status': 'Estado: {{value}}',
  'plans.progress.indeterminate': 'El progreso se está actualizando.', 'plans.progress.applying': 'Aplicando el plan.',
  'plans.progress.counts': '{{completed}} de {{total}} operaciones ({{percent}})',
  'plans.progress.succeeded': 'Plan aplicado y verificado.', 'plans.progress.failed': 'El plan falló.',
  'plans.progress.verification_failed': 'La verificación falló.', 'plans.progress.intervention_required': 'Se requiere intervención manual.',
  'plans.status.applying': 'Aplicando', 'plans.status.succeeded': 'Correcto', 'plans.status.failed': 'Fallido',
  'plans.status.verification_failed': 'Verificación fallida', 'risk.low': 'Bajo', 'risk.medium': 'Medio', 'risk.high': 'Alto',
  'plans.queued': 'En cola; Discord aún no ha cambiado.', 'plans.verified': 'Aplicado y verificado.',
  'diagnostics.title': 'Diagnósticos', 'diagnostics.coverage': 'Cobertura de caché',
  'diagnostics.capabilities': 'Capacidades del bot', 'diagnostics.source': 'Fuente: caché local de DID',
  'diagnostics.mode': 'Cobertura', 'diagnostics.freshness': 'Actualización', 'diagnostics.state.full': 'Completa',
  'diagnostics.state.partial': 'Parcial', 'diagnostics.state.unknown': 'Desconocida', 'diagnostics.state.fresh': 'Actual', 'diagnostics.state.stale': 'Obsoleta',
  'audit.title': 'Auditoría interna', 'audit.empty': 'No hay eventos de auditoría.',
  'audit.event.installation': 'Instalación del bot modificada', 'audit.event.plan': 'Estado del plan modificado',
  'audit.event.portability': 'Operación de recurso portátil', 'audit.event.role': 'Estructura de roles modificada',
  'audit.event.structure': 'Estructura del servidor modificada', 'audit.event.generic': 'Evento de infraestructura',
  'audit.result.succeeded': 'Correcto', 'audit.result.observed': 'Observado', 'audit.result.failed': 'Fallido',
  'audit.result.stale': 'Obsoleto', 'audit.result.intervention': 'Intervención necesaria',
  'artifact.channel': 'Canal', 'artifact.category': 'Categoría', 'artifact.logicalGroup': 'Grupo lógico',
  'artifact.guildConfig': 'Configuración del servidor', 'artifact.customBundle': 'Paquete personalizado', 'artifact.unknown': 'Recurso portátil',
  'templates.title': 'Plantillas', 'templates.empty': 'No hay plantillas para este servidor.',
  'library.title': 'Biblioteca portátil personal', 'library.empty': 'Tu biblioteca está vacía.',
  'library.export': 'Descargar archivo portátil', 'clone.title': 'Copia y clonación entre servidores',
  'clone.destination': 'Servidor de destino', 'clone.copy': 'Copiar como nuevo',
  'clone.merge': 'Combinar recursos compatibles', 'clone.reconcile': 'Reconciliar clon',
  'clone.neverMove': 'La fuente nunca se mueve ni se elimina.', 'clone.mapping': 'Revisar asignaciones de destino',
  'clone.previewReady': 'Vista previa de transferencia creada.',
  'actions.open': 'Abrir detalles', 'actions.open.description': 'Inspeccionar el recurso seleccionado.',
  'actions.open.tooltip': 'Abrir el panel de propiedades', 'actions.move': 'Proponer movimiento',
  'actions.move.description': 'Crear una propuesta de movimiento en el mismo servidor.',
  'actions.move.tooltip': 'Previsualizar un plan de movimiento', 'actions.copy': 'Copiar como nuevo',
  'actions.copy.description': 'Copiar a un servidor de destino autorizado.', 'actions.copy.tooltip': 'Previsualizar una copia portátil',
  'actions.clone': 'Clonar con dependencias', 'actions.clone.description': 'Clonar dependencias compatibles mediante el flujo portátil.',
  'actions.clone.tooltip': 'Previsualizar clon con dependencias', 'actions.export': 'Guardar en mi biblioteca',
  'actions.export.description': 'Crear un artefacto portátil privado.', 'actions.export.tooltip': 'Exportar la selección',
  'actions.explain': 'Explicar acceso', 'actions.explain.description': 'Abrir la explicación de permisos.',
  'actions.explain.tooltip': 'Mostrar por qué se concede acceso', 'actions.bulk': 'Vista previa masiva',
  'actions.bulk.description': 'Previsualizar una operación segura para la selección.',
  'actions.bulk.tooltip': 'Abrir la vista previa de acciones masivas', 'actions.disabled.capability': 'Falta la capacidad necesaria.',
  'actions.disabled.unknown': 'La capacidad no se puede verificar ahora.',
  'actions.disabled.target': 'Este destino no es compatible.',
  'context.title': 'Acciones disponibles', 'context.dropTitle': 'Elegir una acción de colocación',
  'commands.title': 'Paleta de comandos', 'commands.placeholder': 'Buscar acciones y páginas',
  'commands.empty': 'No hay comandos disponibles.', 'gesture.movePreview': 'Propuesta de movimiento lista.',
  'gesture.copyPreview': 'Vista previa de copia entre servidores lista.', 'gesture.cancelled': 'Arrastre cancelado.',
  'gesture.invalid': 'Destino no válido.', 'dialog.previewTitle': 'Revisar la acción propuesta',
  'dialog.noMutation': 'Discord no cambia hasta confirmar y aplicar un plan.',
  'errors.auth.required': 'Tu sesión caducó. Inicia sesión de nuevo.',
  'errors.auth.csrf': 'El token de seguridad no es válido. Actualiza la sesión.',
  'errors.authorization.denied': 'No tienes permiso para realizar esta acción.',
  'errors.resource.notFound': 'No se encontró el recurso solicitado.',
  'errors.plans.notFound': 'No se encontró el plan solicitado.',
  'errors.plans.conflict': 'El plan cambió. Carga su versión actual.',
  'errors.input.invalid': 'Los datos enviados no son válidos.', 'errors.network.offline': 'No se puede acceder al servicio.',
  'errors.generic': 'No se pudo completar la operación. Solicitud: {{requestId}}',
  'a11y.openNavigation': 'Abrir navegación', 'a11y.closeDialog': 'Cerrar diálogo',
  'a11y.tree': 'Árbol de recursos de Discord', 'a11y.contextMenu': 'Menú contextual de la aplicación',
  'a11y.dragStarted': 'Arrastre iniciado para {{name}}.', 'a11y.dragTarget': 'Destino {{name}}.',
  'app.title': 'Discord Infrastructure Designer', 'nav.structure': 'Estructura',
  'permissions.trace.baseEveryone': 'Permisos base del rol todos.', 'permissions.trace.baseRole': 'Permisos base del rol seleccionado.',
  'permissions.trace.baseRolesOr': 'Se combinaron los permisos de los roles del miembro.', 'permissions.trace.ownerBypass': 'Se aplica la omisión del propietario del servidor.',
  'permissions.trace.administratorBypass': 'Se aplica la omisión de administrador.', 'permissions.trace.everyoneDeny': 'La sobrescritura de todos denegó permisos.',
  'permissions.trace.roleDeniesAggregate': 'Las sobrescrituras de roles denegaron permisos.', 'permissions.trace.memberDeny': 'La sobrescritura del miembro denegó permisos.',
  'permissions.trace.everyoneAllow': 'La sobrescritura de todos permitió permisos.', 'permissions.trace.roleAllowsAggregate': 'Las sobrescrituras de roles permitieron permisos.',
  'permissions.trace.memberAllow': 'La sobrescritura del miembro permitió permisos.', 'permissions.trace.threadInheritance': 'Los permisos del hilo se heredaron del canal superior.',
  'permissions.trace.implicitDenial': 'Se aplicaron las reglas de denegación implícita de Discord.', 'permissions.trace.coverageIncomplete': 'Las pruebas de permisos en caché están incompletas.',
  'plans.progress.created': 'Plan creado.', 'plans.progress.validated': 'Comprobación previa superada.', 'plans.progress.confirmed': 'Plan confirmado.',
  'plans.progress.cancel_requested': 'Cancelación solicitada.', 'plans.progress.cancelled': 'Plan cancelado.', 'plans.progress.stale': 'El plan está obsoleto.',
  'plans.progress.partially_applied': 'El plan se aplicó parcialmente.', 'plans.progress.preconditionRejected': 'Una precondición rechazó la operación.',
  'plans.progress.operationSucceeded': 'Operación correcta.', 'plans.progress.operationUnknown': 'El resultado de la operación es desconocido.',
  'plans.progress.operationRetryScheduled': 'Reintento de la operación programado.', 'plans.progress.operationFailed': 'La operación falló.',
  'plans.status.draft': 'Borrador', 'plans.status.validated': 'Validado', 'plans.status.confirmed': 'Confirmado',
  'plans.status.cancel_requested': 'Cancelación solicitada', 'plans.status.cancelled': 'Cancelado', 'plans.status.stale': 'Obsoleto',
  'plans.status.partially_applied': 'Aplicado parcialmente', 'plans.status.intervention_required': 'Intervención necesaria',
})

export const bootstrapPacks = { en, fr, de, es } satisfies Record<BootstrapLocaleCode, MessagePack>
