const en = {
  'nav.matrix': 'Access matrix',
  'matrix.title': 'Access matrix',
  'matrix.subtitle': 'Compare effective Discord access with Policy intent, then edit one cell or prepare a safe bulk change.',
  'matrix.denied': 'You cannot read both access Policies and effective permissions for this server.',
  'matrix.refresh': 'Refresh data',
  'matrix.empty': 'No compatible roles or resources are available in the local read model.',
  'matrix.limit': 'This bounded view shows the first {{roles}} roles and {{resources}} resources. Refine the server structure to inspect the remainder.',
  'matrix.filters.label': 'Matrix filters',
  'matrix.filters.ALL': 'All',
  'matrix.filters.CONFLICTS': 'Conflicts',
  'matrix.filters.EXCEPTIONS': 'Exceptions',
  'matrix.filters.PRIVATE': 'Private zones',
  'matrix.selection.count': '{{count}} selected',
  'matrix.grid.label': 'Roles by categories and channels',
  'matrix.roles': 'Roles / audiences',
  'matrix.cell.label': '{{role}} and {{resource}}: {{access}}',
  'matrix.access.none': 'No access',
  'matrix.access.unknown': 'Unknown',
  'matrix.marker.conflict': 'Conflict',
  'matrix.marker.exception': 'Local exception',
  'matrix.marker.inherited': 'Inherited',
  'matrix.cell.edit': 'Change the intended access',
  'matrix.cell.current': 'Effective access now: {{access}}',
  'matrix.cell.intent': 'Human intention',
  'matrix.cell.draftReady': 'A Policy DRAFT and its Preview are ready. Discord was not changed.',
  'matrix.preview.create': 'Create DRAFT and preview',
  'matrix.preview.refresh': 'Refresh preview',
  'matrix.discordDetails': 'Discord details',
  'matrix.before': 'Before:',
  'matrix.after': 'After:',
  'matrix.plan.prepare': 'Prepare plan(s)',
  'matrix.plansPrepared': '{{count}} plan(s) prepared',
  'matrix.bulk.eyebrow': 'Bulk edit',
  'matrix.bulk.title': 'Apply a Policy…',
  'matrix.bulk.policy': 'Compatible Policy',
  'matrix.bulk.audience': 'Roles / audience',
  'matrix.bulk.selected': '{{count}} selected',
  'matrix.bulk.compatible': '{{count}} compatible',
  'matrix.bulk.excluded': '{{count}} excluded',
  'matrix.bulk.reason.voice': 'This Policy does not support voice channels.',
  'matrix.bulk.reason.resourceType': 'This Policy does not support this resource type.',
  'matrix.bulk.reason.inheritedByCategory': 'Already covered by the selected parent category.',
  'matrix.bulk.preview': 'Create DRAFTs and preview',
  'matrix.bulk.drafts': '{{count}} DRAFT(s)',
  'matrix.bulk.differences': '{{count}} before/after difference(s)',
  'matrix.bulk.conflicts': '{{count}} conflict(s)',
  'matrix.bulk.blocked': '{{count}} BLOCKED',
  'matrix.bulk.unknown': '{{count}} UNKNOWN',
  'matrix.bulk.accuracy': 'Analysis: {{accuracy}}',
  'matrix.bulk.resolveFirst': 'Resolve BLOCKED/UNKNOWN results and require an exact analysis before preparing Plans.',
  'matrix.bulk.noCompatible': 'No selected resource is compatible with this Policy.',
} as const

const fr: Record<keyof typeof en, string> = {
  'nav.matrix': 'Matrice d’accès',
  'matrix.title': 'Matrice d’accès',
  'matrix.subtitle': 'Comparez les accès Discord effectifs à l’intention des Policies, puis modifiez une cellule ou préparez une édition massive sûre.',
  'matrix.denied': 'Vous ne pouvez pas lire à la fois les Policies d’accès et les permissions effectives de ce serveur.',
  'matrix.refresh': 'Actualiser les données',
  'matrix.empty': 'Aucun rôle ou aucune ressource compatible n’est disponible dans le read model local.',
  'matrix.limit': 'Cette vue bornée affiche les {{roles}} premiers rôles et {{resources}} premières ressources. Affinez la structure du serveur pour inspecter le reste.',
  'matrix.filters.label': 'Filtres de la matrice',
  'matrix.filters.ALL': 'Tous',
  'matrix.filters.CONFLICTS': 'Conflits',
  'matrix.filters.EXCEPTIONS': 'Exceptions',
  'matrix.filters.PRIVATE': 'Zones privées',
  'matrix.selection.count': '{{count}} sélectionné(s)',
  'matrix.grid.label': 'Rôles par catégories et salons',
  'matrix.roles': 'Rôles / audiences',
  'matrix.cell.label': '{{role}} et {{resource}} : {{access}}',
  'matrix.access.none': 'Aucun accès',
  'matrix.access.unknown': 'Inconnu',
  'matrix.marker.conflict': 'Conflit',
  'matrix.marker.exception': 'Exception locale',
  'matrix.marker.inherited': 'Hérité',
  'matrix.cell.edit': 'Modifier l’intention d’accès',
  'matrix.cell.current': 'Accès effectif actuel : {{access}}',
  'matrix.cell.intent': 'Intention humaine',
  'matrix.cell.draftReady': 'Une Policy DRAFT et sa Preview sont prêtes. Discord n’a pas été modifié.',
  'matrix.preview.create': 'Créer le DRAFT et prévisualiser',
  'matrix.preview.refresh': 'Actualiser la preview',
  'matrix.discordDetails': 'Détails Discord',
  'matrix.before': 'Avant :',
  'matrix.after': 'Après :',
  'matrix.plan.prepare': 'Préparer le ou les plans',
  'matrix.plansPrepared': '{{count}} plan(s) préparé(s)',
  'matrix.bulk.eyebrow': 'Édition massive',
  'matrix.bulk.title': 'Appliquer une Policy…',
  'matrix.bulk.policy': 'Policy compatible',
  'matrix.bulk.audience': 'Rôles / audience',
  'matrix.bulk.selected': '{{count}} sélectionné(s)',
  'matrix.bulk.compatible': '{{count}} compatible(s)',
  'matrix.bulk.excluded': '{{count}} exclu(s)',
  'matrix.bulk.reason.voice': 'Cette Policy ne prend pas en charge les salons vocaux.',
  'matrix.bulk.reason.resourceType': 'Cette Policy ne prend pas en charge ce type de ressource.',
  'matrix.bulk.reason.inheritedByCategory': 'Déjà couvert par la catégorie parente sélectionnée.',
  'matrix.bulk.preview': 'Créer les DRAFTs et prévisualiser',
  'matrix.bulk.drafts': '{{count}} DRAFT(s)',
  'matrix.bulk.differences': '{{count}} différence(s) avant/après',
  'matrix.bulk.conflicts': '{{count}} conflit(s)',
  'matrix.bulk.blocked': '{{count}} BLOCKED',
  'matrix.bulk.unknown': '{{count}} UNKNOWN',
  'matrix.bulk.accuracy': 'Analyse : {{accuracy}}',
  'matrix.bulk.resolveFirst': 'Résolvez les résultats BLOCKED/UNKNOWN et exigez une analyse exacte avant de préparer les Plans.',
  'matrix.bulk.noCompatible': 'Aucune ressource sélectionnée n’est compatible avec cette Policy.',
}

const de: Record<keyof typeof en, string> = {
  'nav.matrix': 'Zugriffsmatrix',
  'matrix.title': 'Zugriffsmatrix',
  'matrix.subtitle': 'Vergleichen Sie den effektiven Discord-Zugriff mit der Policy-Absicht und bearbeiten Sie eine Zelle oder eine sichere Sammeländerung.',
  'matrix.denied': 'Sie können nicht sowohl Zugriffs-Policies als auch effektive Berechtigungen dieses Servers lesen.',
  'matrix.refresh': 'Daten aktualisieren',
  'matrix.empty': 'Im lokalen Lesemodell sind keine kompatiblen Rollen oder Ressourcen verfügbar.',
  'matrix.limit': 'Diese begrenzte Ansicht zeigt die ersten {{roles}} Rollen und {{resources}} Ressourcen. Verfeinern Sie die Serverstruktur, um den Rest zu prüfen.',
  'matrix.filters.label': 'Matrixfilter',
  'matrix.filters.ALL': 'Alle',
  'matrix.filters.CONFLICTS': 'Konflikte',
  'matrix.filters.EXCEPTIONS': 'Ausnahmen',
  'matrix.filters.PRIVATE': 'Private Bereiche',
  'matrix.selection.count': '{{count}} ausgewählt',
  'matrix.grid.label': 'Rollen nach Kategorien und Kanälen',
  'matrix.roles': 'Rollen / Zielgruppen',
  'matrix.cell.label': '{{role}} und {{resource}}: {{access}}',
  'matrix.access.none': 'Kein Zugriff',
  'matrix.access.unknown': 'Unbekannt',
  'matrix.marker.conflict': 'Konflikt',
  'matrix.marker.exception': 'Lokale Ausnahme',
  'matrix.marker.inherited': 'Geerbt',
  'matrix.cell.edit': 'Beabsichtigten Zugriff ändern',
  'matrix.cell.current': 'Aktueller effektiver Zugriff: {{access}}',
  'matrix.cell.intent': 'Menschliche Absicht',
  'matrix.cell.draftReady': 'Ein Policy-Entwurf und seine Vorschau sind bereit. Discord wurde nicht geändert.',
  'matrix.preview.create': 'Entwurf erstellen und ansehen',
  'matrix.preview.refresh': 'Vorschau aktualisieren',
  'matrix.discordDetails': 'Discord-Details',
  'matrix.before': 'Vorher:',
  'matrix.after': 'Nachher:',
  'matrix.plan.prepare': 'Plan/Pläne vorbereiten',
  'matrix.plansPrepared': '{{count}} Plan/Pläne vorbereitet',
  'matrix.bulk.eyebrow': 'Sammelbearbeitung',
  'matrix.bulk.title': 'Policy anwenden…',
  'matrix.bulk.policy': 'Kompatible Policy',
  'matrix.bulk.audience': 'Rollen / Zielgruppe',
  'matrix.bulk.selected': '{{count}} ausgewählt',
  'matrix.bulk.compatible': '{{count}} kompatibel',
  'matrix.bulk.excluded': '{{count}} ausgeschlossen',
  'matrix.bulk.reason.voice': 'Diese Policy unterstützt keine Sprachkanäle.',
  'matrix.bulk.reason.resourceType': 'Diese Policy unterstützt diesen Ressourcentyp nicht.',
  'matrix.bulk.reason.inheritedByCategory': 'Bereits durch die ausgewählte übergeordnete Kategorie abgedeckt.',
  'matrix.bulk.preview': 'Entwürfe erstellen und ansehen',
  'matrix.bulk.drafts': '{{count}} Entwurf/Entwürfe',
  'matrix.bulk.differences': '{{count}} Vorher/Nachher-Unterschied(e)',
  'matrix.bulk.conflicts': '{{count}} Konflikt(e)',
  'matrix.bulk.blocked': '{{count}} BLOCKED',
  'matrix.bulk.unknown': '{{count}} UNKNOWN',
  'matrix.bulk.accuracy': 'Analyse: {{accuracy}}',
  'matrix.bulk.resolveFirst': 'Lösen Sie BLOCKED/UNKNOWN-Ergebnisse und verlangen Sie eine exakte Analyse, bevor Pläne vorbereitet werden.',
  'matrix.bulk.noCompatible': 'Keine ausgewählte Ressource ist mit dieser Policy kompatibel.',
}

const es: Record<keyof typeof en, string> = {
  'nav.matrix': 'Matriz de acceso',
  'matrix.title': 'Matriz de acceso',
  'matrix.subtitle': 'Compara el acceso efectivo de Discord con la intención de las Policies y edita una celda o prepara un cambio masivo seguro.',
  'matrix.denied': 'No puedes leer a la vez las Policies de acceso y los permisos efectivos de este servidor.',
  'matrix.refresh': 'Actualizar datos',
  'matrix.empty': 'No hay roles ni recursos compatibles en el modelo de lectura local.',
  'matrix.limit': 'Esta vista limitada muestra los primeros {{roles}} roles y {{resources}} recursos. Refina la estructura del servidor para revisar el resto.',
  'matrix.filters.label': 'Filtros de la matriz',
  'matrix.filters.ALL': 'Todos',
  'matrix.filters.CONFLICTS': 'Conflictos',
  'matrix.filters.EXCEPTIONS': 'Excepciones',
  'matrix.filters.PRIVATE': 'Zonas privadas',
  'matrix.selection.count': '{{count}} seleccionado(s)',
  'matrix.grid.label': 'Roles por categorías y canales',
  'matrix.roles': 'Roles / audiencias',
  'matrix.cell.label': '{{role}} y {{resource}}: {{access}}',
  'matrix.access.none': 'Sin acceso',
  'matrix.access.unknown': 'Desconocido',
  'matrix.marker.conflict': 'Conflicto',
  'matrix.marker.exception': 'Excepción local',
  'matrix.marker.inherited': 'Heredado',
  'matrix.cell.edit': 'Cambiar la intención de acceso',
  'matrix.cell.current': 'Acceso efectivo actual: {{access}}',
  'matrix.cell.intent': 'Intención humana',
  'matrix.cell.draftReady': 'Una Policy en borrador y su vista previa están listas. Discord no se modificó.',
  'matrix.preview.create': 'Crear borrador y previsualizar',
  'matrix.preview.refresh': 'Actualizar vista previa',
  'matrix.discordDetails': 'Detalles de Discord',
  'matrix.before': 'Antes:',
  'matrix.after': 'Después:',
  'matrix.plan.prepare': 'Preparar plan(es)',
  'matrix.plansPrepared': '{{count}} plan(es) preparado(s)',
  'matrix.bulk.eyebrow': 'Edición masiva',
  'matrix.bulk.title': 'Aplicar una Policy…',
  'matrix.bulk.policy': 'Policy compatible',
  'matrix.bulk.audience': 'Roles / audiencia',
  'matrix.bulk.selected': '{{count}} seleccionado(s)',
  'matrix.bulk.compatible': '{{count}} compatible(s)',
  'matrix.bulk.excluded': '{{count}} excluido(s)',
  'matrix.bulk.reason.voice': 'Esta Policy no admite canales de voz.',
  'matrix.bulk.reason.resourceType': 'Esta Policy no admite este tipo de recurso.',
  'matrix.bulk.reason.inheritedByCategory': 'Ya está cubierto por la categoría principal seleccionada.',
  'matrix.bulk.preview': 'Crear borradores y previsualizar',
  'matrix.bulk.drafts': '{{count}} borrador(es)',
  'matrix.bulk.differences': '{{count}} diferencia(s) antes/después',
  'matrix.bulk.conflicts': '{{count}} conflicto(s)',
  'matrix.bulk.blocked': '{{count}} BLOCKED',
  'matrix.bulk.unknown': '{{count}} UNKNOWN',
  'matrix.bulk.accuracy': 'Análisis: {{accuracy}}',
  'matrix.bulk.resolveFirst': 'Resuelve los resultados BLOCKED/UNKNOWN y exige un análisis exacto antes de preparar Planes.',
  'matrix.bulk.noCompatible': 'Ningún recurso seleccionado es compatible con esta Policy.',
}

export const phase4MatrixPacks = { en, fr, de, es }
