export const phase2Packs = {
  en: {
    'nav.overview': 'Overview',
    'guilds.empty': 'No eligible Discord server was found.',
    'guilds.subtitle': 'Servers where Discord Infrastructure Designer is installed are shown here.',
    'guilds.setup': 'Configure',
    'guilds.blocked': 'Setup requires the server owner or a Discord administrator.',
    'guilds.noAccess': 'The bot is installed, but your dashboard account has no access.',
    'shell.recentServers': 'Recent servers',
    'shell.workspace': 'Workspace',
    'shell.searchHint': 'Search or run a command',
    'overview.title': 'Server overview',
    'overview.subtitle': 'A live operational view of this Discord server.',
    'overview.structure': 'Structure',
    'overview.roles': 'Roles',
    'overview.coverage': 'Cache coverage',
    'overview.connection': 'Live connection',
    'overview.openStructure': 'Open structure',
    'overview.openDiagnostics': 'Open diagnostics',
    'onboarding.title': 'First server setup',
    'onboarding.subtitle': 'DID verifies Discord, imports the real structure, audits bot capabilities, then activates the tenant.',
    'onboarding.bot': 'Bot detected in this server',
    'onboarding.identity': 'Configurator identity verified',
    'onboarding.configurator': 'Configurator is owner or Discord administrator',
    'onboarding.permissions': 'Bot permissions audited',
    'onboarding.structure': 'Initial structure imported',
    'onboarding.audit': 'Initial capability audit complete',
    'onboarding.constraints': 'Applicable limits and constraints reviewed',
    'onboarding.constraintsCount': '{{count}} limited functions',
    'onboarding.configuration': 'Dashboard defaults prepared',
    'onboarding.activation': 'Tenant activated',
    'onboarding.import': 'Import and verify structure',
    'onboarding.importing': 'Initial sync queued. Waiting for the Discord worker…',
    'onboarding.activate': 'Activate this server',
    'onboarding.refresh': 'Refresh checks',
    'onboarding.done': 'Ready',
    'onboarding.waiting': 'Waiting',
    'onboarding.blocked': 'Blocked',
    'onboarding.counts': '{{channels}} channels / threads · {{roles}} roles',
    'onboarding.limited': 'Some bot operations are unavailable. DID will block impossible mutations and show the exact missing permission.',
    'onboarding.permissionDetails': 'Bot capabilities and permissions',
    'onboarding.leastPrivilege': 'DID requests only the permissions needed by each function. ADMINISTRATOR is never required for convenience.',
    'onboarding.requiredPermissions': 'Required permissions and purpose',
    'onboarding.permission.none': 'No additional Discord permission is required for this check.',
    'onboarding.permission.manageChannels': 'Create, rename, move and configure Discord channels and categories.',
    'onboarding.permission.manageRoles': 'Create roles and manage permission overwrites without requesting ADMINISTRATOR.',
    'onboarding.permission.viewAuditLog': 'Correlate Discord changes with the DID audit trail.',
    'onboarding.permission.manageWebhooks': 'Manage webhooks only when a webhook feature is enabled.',
    'onboarding.permission.viewChannel': 'Observe the target channel before acting.',
    'onboarding.permission.sendMessages': 'Publish a message in the selected channel.',
    'onboarding.permission.sendThreads': 'Publish inside a selected thread.',
    'onboarding.permission.manageThreads': 'Manage the selected thread.',
    'onboarding.permission.generic': 'Required by Discord for this operation: {{permission}}.',
    'onboarding.operation.createChannel': 'Create a channel', 'onboarding.operation.manageChannel': 'Manage a channel', 'onboarding.operation.reorderChannels': 'Reorder channels',
    'onboarding.operation.manageOverwrites': 'Manage channel access', 'onboarding.operation.createRole': 'Create a role', 'onboarding.operation.manageRole': 'Manage a role',
    'onboarding.operation.reorderRoles': 'Reorder roles', 'onboarding.operation.assignRole': 'Assign a role', 'onboarding.operation.sendMessage': 'Send a message', 'onboarding.operation.manageThread': 'Manage a thread',
    'onboarding.outcome.can': 'Available with the currently observed permissions.', 'onboarding.outcome.cannot': 'Unavailable until the listed permission is granted.', 'onboarding.outcome.unknown': 'Not globally decidable: DID will verify the selected resource before enabling the function.',
    'onboarding.cause.missingPermission': 'Missing Discord permission: {{permission}}.', 'onboarding.cause.channelContext': 'A target channel is required for an exact decision.', 'onboarding.cause.roleContext': 'A target role is required to check the role hierarchy.',
    'onboarding.cause.intentMissing': 'A required Gateway intent is unavailable.', 'onboarding.cause.inactive': 'The tenant is not active yet.', 'onboarding.cause.incomplete': 'The cached Discord evidence is incomplete; refresh the import before acting.',
    'onboarding.remediation': 'Grant only the listed permission for this function, then refresh the checks.',
    'onboarding.notAdmin': 'Only the server owner or a member with Discord ADMINISTRATOR can perform the initial setup.',
    'onboarding.gatewayMissing': 'The bot Gateway has not observed this server yet. Check that the bot process is running and installed on this server.',
    'onboarding.importRequired': 'Run the initial import to establish a complete local snapshot.',
    'onboarding.permissionsPending': 'Bot permission evidence is not complete yet.',
    'onboarding.active': 'This server is active. Opening the dashboard…',
    'errors.onboarding.notReady': 'Setup is not ready yet. Refresh the checks and resolve the blocking item.',
  },
  fr: {
    'nav.overview': 'Vue d’ensemble',
    'guilds.empty': 'Aucun serveur Discord admissible trouvé.',
    'guilds.subtitle': 'Les serveurs sur lesquels Discord Infrastructure Designer est installé apparaissent ici.',
    'guilds.setup': 'Configurer',
    'guilds.blocked': 'La configuration initiale exige le propriétaire du serveur ou un administrateur Discord.',
    'guilds.noAccess': 'Le bot est installé, mais votre compte n’a pas accès au dashboard.',
    'shell.recentServers': 'Serveurs récents',
    'shell.workspace': 'Espace de travail',
    'shell.searchHint': 'Rechercher ou lancer une commande',
    'overview.title': 'Vue d’ensemble du serveur',
    'overview.subtitle': 'Une vue opérationnelle en temps réel de ce serveur Discord.',
    'overview.structure': 'Structure',
    'overview.roles': 'Rôles',
    'overview.coverage': 'Couverture du cache',
    'overview.connection': 'Connexion temps réel',
    'overview.openStructure': 'Ouvrir la structure',
    'overview.openDiagnostics': 'Ouvrir les diagnostics',
    'onboarding.title': 'Première configuration du serveur',
    'onboarding.subtitle': 'DID vérifie Discord, importe la structure réelle, audite les capacités du bot puis active le tenant.',
    'onboarding.bot': 'Bot détecté dans ce serveur',
    'onboarding.identity': 'Identité du configurateur vérifiée',
    'onboarding.configurator': 'Configurateur propriétaire ou administrateur Discord',
    'onboarding.permissions': 'Permissions du bot auditées',
    'onboarding.structure': 'Structure initiale importée',
    'onboarding.audit': 'Audit initial des capacités terminé',
    'onboarding.constraints': 'Limites et contraintes applicables vérifiées',
    'onboarding.constraintsCount': '{{count}} fonctions limitées',
    'onboarding.configuration': 'Configuration par défaut du dashboard prête',
    'onboarding.activation': 'Tenant activé',
    'onboarding.import': 'Importer et vérifier la structure',
    'onboarding.importing': 'Synchronisation initiale mise en file. Attente du worker Discord…',
    'onboarding.activate': 'Activer ce serveur',
    'onboarding.refresh': 'Actualiser les vérifications',
    'onboarding.done': 'Prêt',
    'onboarding.waiting': 'En attente',
    'onboarding.blocked': 'Bloqué',
    'onboarding.counts': '{{channels}} salons / threads · {{roles}} rôles',
    'onboarding.limited': 'Certaines opérations du bot sont indisponibles. DID bloquera les mutations impossibles et indiquera précisément la permission manquante.',
    'onboarding.permissionDetails': 'Capacités et permissions du bot',
    'onboarding.leastPrivilege': 'DID demande uniquement les permissions nécessaires à chaque fonction. ADMINISTRATOR n’est jamais exigé par commodité.',
    'onboarding.requiredPermissions': 'Permissions requises et justification',
    'onboarding.permission.none': 'Aucune permission Discord supplémentaire n’est requise pour ce contrôle.',
    'onboarding.permission.manageChannels': 'Créer, renommer, déplacer et configurer les salons et catégories Discord.',
    'onboarding.permission.manageRoles': 'Créer les rôles et gérer les overwrites sans demander ADMINISTRATOR.',
    'onboarding.permission.viewAuditLog': 'Rapprocher les changements Discord de la piste d’audit DID.',
    'onboarding.permission.manageWebhooks': 'Gérer les webhooks uniquement lorsqu’une fonction webhook est activée.',
    'onboarding.permission.viewChannel': 'Observer le salon cible avant d’agir.',
    'onboarding.permission.sendMessages': 'Publier un message dans le salon sélectionné.',
    'onboarding.permission.sendThreads': 'Publier dans le thread sélectionné.',
    'onboarding.permission.manageThreads': 'Gérer le thread sélectionné.',
    'onboarding.permission.generic': 'Permission exigée par Discord pour cette opération : {{permission}}.',
    'onboarding.operation.createChannel': 'Créer un salon', 'onboarding.operation.manageChannel': 'Gérer un salon', 'onboarding.operation.reorderChannels': 'Réordonner les salons',
    'onboarding.operation.manageOverwrites': 'Gérer les accès aux salons', 'onboarding.operation.createRole': 'Créer un rôle', 'onboarding.operation.manageRole': 'Gérer un rôle',
    'onboarding.operation.reorderRoles': 'Réordonner les rôles', 'onboarding.operation.assignRole': 'Attribuer un rôle', 'onboarding.operation.sendMessage': 'Envoyer un message', 'onboarding.operation.manageThread': 'Gérer un thread',
    'onboarding.outcome.can': 'Disponible avec les permissions actuellement observées.', 'onboarding.outcome.cannot': 'Indisponible tant que la permission indiquée n’est pas accordée.', 'onboarding.outcome.unknown': 'Décision impossible globalement : DID vérifiera la ressource sélectionnée avant d’activer la fonction.',
    'onboarding.cause.missingPermission': 'Permission Discord manquante : {{permission}}.', 'onboarding.cause.channelContext': 'Un salon cible est nécessaire pour une décision exacte.', 'onboarding.cause.roleContext': 'Un rôle cible est nécessaire pour vérifier la hiérarchie.',
    'onboarding.cause.intentMissing': 'Un intent Gateway requis est indisponible.', 'onboarding.cause.inactive': 'Le tenant n’est pas encore actif.', 'onboarding.cause.incomplete': 'Les preuves Discord en cache sont incomplètes ; actualisez l’import avant d’agir.',
    'onboarding.remediation': 'Accordez uniquement la permission indiquée pour cette fonction, puis actualisez les contrôles.',
    'onboarding.notAdmin': 'Seul le propriétaire du serveur ou un membre avec ADMINISTRATOR dans Discord peut effectuer la configuration initiale.',
    'onboarding.gatewayMissing': 'Le Gateway du bot n’a pas encore observé ce serveur. Vérifiez que le processus bot tourne et que le bot est installé sur ce serveur.',
    'onboarding.importRequired': 'Lancez l’import initial pour établir un snapshot local complet.',
    'onboarding.permissionsPending': 'Les preuves de permissions du bot ne sont pas encore complètes.',
    'onboarding.active': 'Ce serveur est actif. Ouverture du dashboard…',
    'errors.onboarding.notReady': 'La configuration n’est pas encore prête. Actualisez les contrôles et corrigez le point bloquant.',
  },
  de: {
    'nav.overview': 'Übersicht',
    'guilds.empty': 'Kein geeigneter Discord-Server gefunden.',
    'guilds.subtitle': 'Server, auf denen Discord Infrastructure Designer installiert ist, werden hier angezeigt.',
    'guilds.setup': 'Einrichten',
    'guilds.blocked': 'Die Ersteinrichtung erfordert den Serverbesitzer oder einen Discord-Administrator.',
    'guilds.noAccess': 'Der Bot ist installiert, aber Ihr Dashboard-Konto hat keinen Zugriff.',
    'shell.recentServers': 'Letzte Server',
    'shell.workspace': 'Arbeitsbereich',
    'shell.searchHint': 'Suchen oder Befehl ausführen',
    'overview.title': 'Serverübersicht',
    'overview.subtitle': 'Eine aktuelle Betriebsansicht dieses Discord-Servers.',
    'overview.structure': 'Struktur',
    'overview.roles': 'Rollen',
    'overview.coverage': 'Cache-Abdeckung',
    'overview.connection': 'Live-Verbindung',
    'overview.openStructure': 'Struktur öffnen',
    'overview.openDiagnostics': 'Diagnose öffnen',
    'onboarding.title': 'Erste Servereinrichtung',
    'onboarding.subtitle': 'DID prüft Discord, importiert die reale Struktur, auditiert Bot-Fähigkeiten und aktiviert dann den Tenant.',
    'onboarding.bot': 'Bot auf diesem Server erkannt',
    'onboarding.identity': 'Identität des Konfigurators bestätigt',
    'onboarding.configurator': 'Konfigurator ist Besitzer oder Discord-Administrator',
    'onboarding.permissions': 'Bot-Berechtigungen geprüft',
    'onboarding.structure': 'Anfangsstruktur importiert',
    'onboarding.audit': 'Erstes Fähigkeitsaudit abgeschlossen',
    'onboarding.constraints': 'Anwendbare Grenzen und Einschränkungen geprüft',
    'onboarding.constraintsCount': '{{count}} eingeschränkte Funktionen',
    'onboarding.configuration': 'Dashboard-Standardwerte vorbereitet',
    'onboarding.activation': 'Tenant aktiviert',
    'onboarding.import': 'Struktur importieren und prüfen',
    'onboarding.importing': 'Initiale Synchronisierung eingereiht. Warten auf den Discord-Worker…',
    'onboarding.activate': 'Diesen Server aktivieren',
    'onboarding.refresh': 'Prüfungen aktualisieren',
    'onboarding.done': 'Bereit',
    'onboarding.waiting': 'Wartet',
    'onboarding.blocked': 'Blockiert',
    'onboarding.counts': '{{channels}} Kanäle / Threads · {{roles}} Rollen',
    'onboarding.limited': 'Einige Bot-Operationen sind nicht verfügbar. DID blockiert unmögliche Änderungen und zeigt die fehlende Berechtigung an.',
    'onboarding.permissionDetails': 'Bot-Fähigkeiten und Berechtigungen',
    'onboarding.leastPrivilege': 'DID fordert nur die je Funktion nötigen Rechte an. ADMINISTRATOR wird nie aus Bequemlichkeit verlangt.',
    'onboarding.requiredPermissions': 'Erforderliche Berechtigungen und Zweck',
    'onboarding.permission.none': 'Für diese Prüfung ist keine zusätzliche Discord-Berechtigung nötig.',
    'onboarding.permission.manageChannels': 'Discord-Kanäle und Kategorien erstellen, umbenennen, verschieben und konfigurieren.',
    'onboarding.permission.manageRoles': 'Rollen erstellen und Overwrites verwalten, ohne ADMINISTRATOR anzufordern.',
    'onboarding.permission.viewAuditLog': 'Discord-Änderungen mit dem DID-Audit abgleichen.',
    'onboarding.permission.manageWebhooks': 'Webhooks nur bei aktivierter Webhook-Funktion verwalten.',
    'onboarding.permission.viewChannel': 'Den Zielkanal vor einer Aktion beobachten.',
    'onboarding.permission.sendMessages': 'Eine Nachricht im ausgewählten Kanal veröffentlichen.',
    'onboarding.permission.sendThreads': 'In einem ausgewählten Thread veröffentlichen.',
    'onboarding.permission.manageThreads': 'Den ausgewählten Thread verwalten.',
    'onboarding.permission.generic': 'Von Discord für diese Aktion benötigt: {{permission}}.',
    'onboarding.operation.createChannel': 'Kanal erstellen', 'onboarding.operation.manageChannel': 'Kanal verwalten', 'onboarding.operation.reorderChannels': 'Kanäle sortieren',
    'onboarding.operation.manageOverwrites': 'Kanalzugriff verwalten', 'onboarding.operation.createRole': 'Rolle erstellen', 'onboarding.operation.manageRole': 'Rolle verwalten',
    'onboarding.operation.reorderRoles': 'Rollen sortieren', 'onboarding.operation.assignRole': 'Rolle zuweisen', 'onboarding.operation.sendMessage': 'Nachricht senden', 'onboarding.operation.manageThread': 'Thread verwalten',
    'onboarding.outcome.can': 'Mit den aktuell beobachteten Berechtigungen verfügbar.', 'onboarding.outcome.cannot': 'Nicht verfügbar, bis die genannte Berechtigung erteilt wird.', 'onboarding.outcome.unknown': 'Global nicht entscheidbar: DID prüft die gewählte Ressource vor der Freigabe.',
    'onboarding.cause.missingPermission': 'Fehlende Discord-Berechtigung: {{permission}}.', 'onboarding.cause.channelContext': 'Für eine genaue Entscheidung ist ein Zielkanal nötig.', 'onboarding.cause.roleContext': 'Zur Hierarchieprüfung ist eine Zielrolle nötig.',
    'onboarding.cause.intentMissing': 'Ein erforderlicher Gateway-Intent fehlt.', 'onboarding.cause.inactive': 'Der Tenant ist noch nicht aktiv.', 'onboarding.cause.incomplete': 'Die Discord-Daten im Cache sind unvollständig; Import vor der Aktion aktualisieren.',
    'onboarding.remediation': 'Nur die genannte Berechtigung für diese Funktion erteilen und die Prüfungen aktualisieren.',
    'onboarding.notAdmin': 'Nur der Serverbesitzer oder ein Mitglied mit Discord-ADMINISTRATOR kann die Ersteinrichtung durchführen.',
    'onboarding.gatewayMissing': 'Der Bot-Gateway hat diesen Server noch nicht beobachtet. Prüfen Sie, ob der Bot-Prozess läuft und installiert ist.',
    'onboarding.importRequired': 'Starten Sie den Erstimport, um einen vollständigen lokalen Snapshot zu erstellen.',
    'onboarding.permissionsPending': 'Die Nachweise für Bot-Berechtigungen sind noch nicht vollständig.',
    'onboarding.active': 'Dieser Server ist aktiv. Dashboard wird geöffnet…',
    'errors.onboarding.notReady': 'Die Einrichtung ist noch nicht bereit. Aktualisieren Sie die Prüfungen und beheben Sie den blockierenden Punkt.',
  },
  es: {
    'nav.overview': 'Resumen',
    'guilds.empty': 'No se encontró ningún servidor de Discord elegible.',
    'guilds.subtitle': 'Aquí aparecen los servidores donde está instalado Discord Infrastructure Designer.',
    'guilds.setup': 'Configurar',
    'guilds.blocked': 'La configuración inicial requiere al propietario del servidor o a un administrador de Discord.',
    'guilds.noAccess': 'El bot está instalado, pero tu cuenta no tiene acceso al panel.',
    'shell.recentServers': 'Servidores recientes',
    'shell.workspace': 'Espacio de trabajo',
    'shell.searchHint': 'Buscar o ejecutar un comando',
    'overview.title': 'Resumen del servidor',
    'overview.subtitle': 'Una vista operativa en tiempo real de este servidor de Discord.',
    'overview.structure': 'Estructura',
    'overview.roles': 'Roles',
    'overview.coverage': 'Cobertura de caché',
    'overview.connection': 'Conexión en tiempo real',
    'overview.openStructure': 'Abrir estructura',
    'overview.openDiagnostics': 'Abrir diagnósticos',
    'onboarding.title': 'Configuración inicial del servidor',
    'onboarding.subtitle': 'DID verifica Discord, importa la estructura real, audita las capacidades del bot y activa el tenant.',
    'onboarding.bot': 'Bot detectado en este servidor',
    'onboarding.identity': 'Identidad del configurador verificada',
    'onboarding.configurator': 'El configurador es propietario o administrador de Discord',
    'onboarding.permissions': 'Permisos del bot auditados',
    'onboarding.structure': 'Estructura inicial importada',
    'onboarding.audit': 'Auditoría inicial de capacidades completada',
    'onboarding.constraints': 'Límites y restricciones aplicables revisados',
    'onboarding.constraintsCount': '{{count}} funciones limitadas',
    'onboarding.configuration': 'Valores predeterminados del panel preparados',
    'onboarding.activation': 'Tenant activado',
    'onboarding.import': 'Importar y verificar estructura',
    'onboarding.importing': 'Sincronización inicial en cola. Esperando al worker de Discord…',
    'onboarding.activate': 'Activar este servidor',
    'onboarding.refresh': 'Actualizar comprobaciones',
    'onboarding.done': 'Listo',
    'onboarding.waiting': 'En espera',
    'onboarding.blocked': 'Bloqueado',
    'onboarding.counts': '{{channels}} canales / hilos · {{roles}} roles',
    'onboarding.limited': 'Algunas operaciones del bot no están disponibles. DID bloqueará cambios imposibles y mostrará el permiso que falta.',
    'onboarding.permissionDetails': 'Capacidades y permisos del bot',
    'onboarding.leastPrivilege': 'DID solicita solo los permisos necesarios para cada función. ADMINISTRATOR nunca se exige por comodidad.',
    'onboarding.requiredPermissions': 'Permisos requeridos y finalidad',
    'onboarding.permission.none': 'Esta comprobación no requiere permisos adicionales de Discord.',
    'onboarding.permission.manageChannels': 'Crear, renombrar, mover y configurar canales y categorías de Discord.',
    'onboarding.permission.manageRoles': 'Crear roles y gestionar overwrites sin solicitar ADMINISTRATOR.',
    'onboarding.permission.viewAuditLog': 'Relacionar los cambios de Discord con la auditoría de DID.',
    'onboarding.permission.manageWebhooks': 'Gestionar webhooks solo cuando una función de webhook esté activada.',
    'onboarding.permission.viewChannel': 'Observar el canal de destino antes de actuar.',
    'onboarding.permission.sendMessages': 'Publicar un mensaje en el canal seleccionado.',
    'onboarding.permission.sendThreads': 'Publicar dentro del hilo seleccionado.',
    'onboarding.permission.manageThreads': 'Gestionar el hilo seleccionado.',
    'onboarding.permission.generic': 'Discord exige este permiso para la operación: {{permission}}.',
    'onboarding.operation.createChannel': 'Crear un canal', 'onboarding.operation.manageChannel': 'Gestionar un canal', 'onboarding.operation.reorderChannels': 'Reordenar canales',
    'onboarding.operation.manageOverwrites': 'Gestionar acceso a canales', 'onboarding.operation.createRole': 'Crear un rol', 'onboarding.operation.manageRole': 'Gestionar un rol',
    'onboarding.operation.reorderRoles': 'Reordenar roles', 'onboarding.operation.assignRole': 'Asignar un rol', 'onboarding.operation.sendMessage': 'Enviar un mensaje', 'onboarding.operation.manageThread': 'Gestionar un hilo',
    'onboarding.outcome.can': 'Disponible con los permisos observados actualmente.', 'onboarding.outcome.cannot': 'No disponible hasta que se conceda el permiso indicado.', 'onboarding.outcome.unknown': 'No se puede decidir globalmente: DID verificará el recurso seleccionado antes de habilitar la función.',
    'onboarding.cause.missingPermission': 'Permiso de Discord ausente: {{permission}}.', 'onboarding.cause.channelContext': 'Se necesita un canal de destino para una decisión exacta.', 'onboarding.cause.roleContext': 'Se necesita un rol de destino para comprobar la jerarquía.',
    'onboarding.cause.intentMissing': 'Falta un intent de Gateway requerido.', 'onboarding.cause.inactive': 'El tenant aún no está activo.', 'onboarding.cause.incomplete': 'La evidencia de Discord en caché está incompleta; actualiza la importación antes de actuar.',
    'onboarding.remediation': 'Concede solo el permiso indicado para esta función y actualiza las comprobaciones.',
    'onboarding.notAdmin': 'Solo el propietario del servidor o un miembro con ADMINISTRATOR en Discord puede realizar la configuración inicial.',
    'onboarding.gatewayMissing': 'El Gateway del bot aún no ha observado este servidor. Comprueba que el proceso del bot esté activo e instalado.',
    'onboarding.importRequired': 'Ejecuta la importación inicial para establecer un snapshot local completo.',
    'onboarding.permissionsPending': 'La evidencia de permisos del bot aún no está completa.',
    'onboarding.active': 'Este servidor está activo. Abriendo el panel…',
    'errors.onboarding.notReady': 'La configuración aún no está lista. Actualiza las comprobaciones y resuelve el bloqueo.',
  },
} as const

export type Phase2Locale = keyof typeof phase2Packs
export type Phase2MessageKey = keyof (typeof phase2Packs)['en']
