export const phase2Packs = {
  en: {
    'nav.overview': 'Overview',
    'guilds.empty': 'No eligible Discord server was found.',
    'guilds.subtitle': 'Servers where Bunny is installed are shown here.',
    'guilds.setup': 'Configure',
    'guilds.blocked': 'Setup requires the server owner or a Discord administrator.',
    'guilds.noAccess': 'The bot is installed, but your dashboard account has no access.',
    'shell.recentServers': 'Recent servers',
    'shell.brand': 'Bunny',
    'shell.brandInitial': 'B',
    'shell.tagline': 'Server Assistant',
    'shell.workspace': 'Workspace',
    'shell.searchHint': 'Search or run a command',
    'shell.openNavigation': 'Open navigation menu',
    'shell.closeNavigation': 'Close navigation menu',
    'shell.navigation': 'Main navigation',
    'shell.home': 'Home',
    'shell.build': 'Build',
    'shell.access': 'Access',
    'shell.automate': 'Automate',
    'shell.activity': 'Activity',
    'shell.expert': 'Advanced tools',
    'shell.helpTitle': 'Need help?',
    'shell.helpCopy': 'Let Bunny guide you',
    'shell.notifications': 'Notifications',
    'shell.account': 'Account and shortcuts',
    'overview.title': 'Server overview',
    'overview.subtitle': 'A live operational view of this Discord server.',
    'overview.structure': 'Structure',
    'overview.roles': 'Roles',
    'overview.coverage': 'Cache coverage',
    'overview.connection': 'Live connection',
    'overview.openStructure': 'Open structure',
    'overview.openDiagnostics': 'Open diagnostics',
    'home.title': 'Home', 'home.subtitle': 'Create and manage your Discord server with Bunny.',
    'home.welcome': 'Welcome, {{name}}', 'home.heroTitle': 'Build a community that feels like yours.',
    'home.heroCopy': 'Bunny brings your structure, access and next changes together in one friendly place.',
    'home.primaryAction': 'Build my server', 'home.secondaryAction': 'Manage access',
    'home.quickTitle': 'Quick actions', 'home.quickSubtitle': 'The most useful tasks, one click away.',
    'home.action.channel': 'Create a channel', 'home.action.channelCopy': 'Add a place for your community to talk.',
    'home.action.access': 'Manage access', 'home.action.accessCopy': 'Choose who can see and participate.',
    'home.action.roles': 'Organize roles', 'home.action.rolesCopy': 'Keep responsibilities clear and simple.',
    'home.action.automate': 'Start an assistant', 'home.action.automateCopy': 'Let Bunny guide your next setup.',
    'home.action.activity': 'See changes', 'home.action.activityCopy': 'Review what is ready or in progress.',
    'home.action.open': 'Open',
    'home.healthTitle': 'Your server at a glance', 'home.healthSubtitle': 'Only what needs your attention.',
    'home.health.good.title': 'Everything looks good!', 'home.health.good.copy': 'Your server is ready to welcome the community.',
    'home.health.checking.title': 'Bunny is checking a few details', 'home.health.checking.copy': 'You can keep working while the latest information arrives.',
    'home.health.attention.title': '{{count}} point needs your attention', 'home.health.attention.copy': 'Open the suggested area to see a clear next step.',
    'home.connection.online': 'Online', 'home.connection.action': 'Action needed', 'home.connection.checking': 'Checking',
    'home.stat.channels': 'channels', 'home.stat.categories': 'categories', 'home.stat.roles': 'roles', 'home.stat.connection': 'server status',
    'home.technicalDetails': 'Technical details', 'home.technicalSummary': 'Coverage: {{coverage}} · Freshness: {{freshness}}',
    'home.setupTitle': 'Get started', 'home.setupSubtitle': 'A short path to a welcoming server.',
    'home.setup.identity': 'Personalize your server', 'home.setup.identityCopy': 'Name, image and description.',
    'home.setup.structure': 'Create your first spaces', 'home.setup.structureCopy': 'Channels and categories for your community.',
    'home.setup.access': 'Configure access', 'home.setup.accessCopy': 'Decide who can see and participate.',
    'home.setup.automate': 'Add a helpful automation', 'home.setup.automateCopy': 'Optional assistants when you are ready.',
    'home.continue': 'Continue building',
    'onboarding.title': 'First server setup',
    'onboarding.subtitle': 'Bunny verifies Discord, imports the real structure and checks what the bot can safely do.',
    'onboarding.bot': 'Bot detected in this server',
    'onboarding.identity': 'Configurator identity verified',
    'onboarding.configurator': 'Configurator is owner or Discord administrator',
    'onboarding.permissions': 'Bot permissions audited',
    'onboarding.structure': 'Initial structure imported',
    'onboarding.audit': 'Initial capability audit complete',
    'onboarding.constraints': 'Applicable limits and constraints reviewed',
    'onboarding.constraintsCount': '{{count}} limited functions',
    'onboarding.configuration': 'Dashboard defaults prepared',
    'onboarding.activation': 'Tenant activated',
    'onboarding.import': 'Import and verify structure',
    'onboarding.importing': 'Initial sync queued. Waiting for the Discord worker…',
    'onboarding.activate': 'Activate this server',
    'onboarding.refresh': 'Refresh checks',
    'onboarding.done': 'Ready',
    'onboarding.waiting': 'Waiting',
    'onboarding.blocked': 'Blocked',
    'onboarding.counts': '{{channels}} channels / threads · {{roles}} roles',
    'onboarding.limited': 'Some bot operations are unavailable. Bunny will block impossible changes and show the exact missing permission.',
    'onboarding.permissionDetails': 'Bot capabilities and permissions',
    'onboarding.leastPrivilege': 'Bunny requests only the permissions needed by each function. ADMINISTRATOR is never required for convenience.',
    'onboarding.requiredPermissions': 'Required permissions and purpose',
    'onboarding.permission.none': 'No additional Discord permission is required for this check.',
    'onboarding.permission.manageChannels': 'Create, rename, move and configure Discord channels and categories.',
    'onboarding.permission.manageRoles': 'Create roles and manage permission overwrites without requesting ADMINISTRATOR.',
    'onboarding.permission.viewAuditLog': 'Correlate Discord changes with Bunny activity.',
    'onboarding.permission.manageWebhooks': 'Manage webhooks only when a webhook feature is enabled.',
    'onboarding.permission.viewChannel': 'Observe the target channel before acting.',
    'onboarding.permission.sendMessages': 'Publish a message in the selected channel.',
    'onboarding.permission.sendThreads': 'Publish inside a selected thread.',
    'onboarding.permission.manageThreads': 'Manage the selected thread.',
    'onboarding.permission.generic': 'Required by Discord for this operation: {{permission}}.',
    'onboarding.operation.createChannel': 'Create a channel', 'onboarding.operation.manageChannel': 'Manage a channel', 'onboarding.operation.reorderChannels': 'Reorder channels',
    'onboarding.operation.manageOverwrites': 'Manage channel access', 'onboarding.operation.createRole': 'Create a role', 'onboarding.operation.manageRole': 'Manage a role',
    'onboarding.operation.reorderRoles': 'Reorder roles', 'onboarding.operation.assignRole': 'Assign a role', 'onboarding.operation.sendMessage': 'Send a message', 'onboarding.operation.manageThread': 'Manage a thread',
    'onboarding.outcome.can': 'Available with the currently observed permissions.', 'onboarding.outcome.cannot': 'Unavailable until the listed permission is granted.', 'onboarding.outcome.unknown': 'Bunny needs a specific resource before it can verify this function.',
    'onboarding.cause.missingPermission': 'Missing Discord permission: {{permission}}.', 'onboarding.cause.channelContext': 'A target channel is required for an exact decision.', 'onboarding.cause.roleContext': 'A target role is required to check the role hierarchy.',
    'onboarding.cause.intentMissing': 'A required Gateway intent is unavailable.', 'onboarding.cause.inactive': 'The tenant is not active yet.', 'onboarding.cause.incomplete': 'The cached Discord evidence is incomplete; refresh the import before acting.',
    'onboarding.remediation': 'Grant only the listed permission for this function, then refresh the checks.',
    'onboarding.notAdmin': 'Only the server owner or a member with Discord ADMINISTRATOR can perform the initial setup.',
    'onboarding.gatewayMissing': 'The bot Gateway has not observed this server yet. Check that the bot process is running and installed on this server.',
    'onboarding.importRequired': 'Run the initial import to establish a complete local snapshot.',
    'onboarding.permissionsPending': 'Bot permission evidence is not complete yet.',
    'onboarding.active': 'This server is active. Opening the dashboard…',
    'errors.onboarding.notReady': 'Setup is not ready yet. Refresh the checks and resolve the blocking item.',
  },
  fr: {
    'nav.overview': 'Vue d’ensemble',
    'guilds.empty': 'Aucun serveur Discord admissible trouvé.',
    'guilds.subtitle': 'Les serveurs sur lesquels Bunny est installé apparaissent ici.',
    'guilds.setup': 'Configurer',
    'guilds.blocked': 'La configuration initiale exige le propriétaire du serveur ou un administrateur Discord.',
    'guilds.noAccess': 'Le bot est installé, mais votre compte n’a pas accès au dashboard.',
    'shell.recentServers': 'Serveurs récents',
    'shell.brand': 'Bunny',
    'shell.brandInitial': 'B',
    'shell.tagline': 'Server Assistant',
    'shell.workspace': 'Espace de travail',
    'shell.searchHint': 'Rechercher ou lancer une commande',
    'shell.openNavigation': 'Ouvrir le menu de navigation',
    'shell.closeNavigation': 'Fermer le menu de navigation',
    'shell.navigation': 'Navigation principale',
    'shell.home': 'Accueil',
    'shell.build': 'Construire',
    'shell.access': 'Accès',
    'shell.automate': 'Automatiser',
    'shell.activity': 'Activité',
    'shell.expert': 'Outils avancés',
    'shell.helpTitle': 'Besoin d’aide ?',
    'shell.helpCopy': 'Laissez Bunny vous guider',
    'shell.notifications': 'Notifications',
    'shell.account': 'Compte et raccourcis',
    'overview.title': 'Vue d’ensemble du serveur',
    'overview.subtitle': 'Une vue opérationnelle en temps réel de ce serveur Discord.',
    'overview.structure': 'Structure',
    'overview.roles': 'Rôles',
    'overview.coverage': 'Couverture du cache',
    'overview.connection': 'Connexion temps réel',
    'overview.openStructure': 'Ouvrir la structure',
    'overview.openDiagnostics': 'Ouvrir les diagnostics',
    'home.title': 'Accueil', 'home.subtitle': 'Créez et gérez votre serveur Discord simplement avec Bunny.',
    'home.welcome': 'Bienvenue, {{name}}', 'home.heroTitle': 'Construisez une communauté qui vous ressemble.',
    'home.heroCopy': 'Bunny réunit votre structure, vos accès et vos prochains changements dans un espace agréable.',
    'home.primaryAction': 'Construire mon serveur', 'home.secondaryAction': 'Gérer les accès',
    'home.quickTitle': 'Actions rapides', 'home.quickSubtitle': 'Les tâches les plus utiles, en un clic.',
    'home.action.channel': 'Créer un salon', 'home.action.channelCopy': 'Ajoutez un espace où votre communauté peut échanger.',
    'home.action.access': 'Gérer les accès', 'home.action.accessCopy': 'Choisissez qui peut voir et participer.',
    'home.action.roles': 'Organiser les rôles', 'home.action.rolesCopy': 'Gardez des responsabilités claires et simples.',
    'home.action.automate': 'Lancer un assistant', 'home.action.automateCopy': 'Laissez Bunny guider votre prochaine configuration.',
    'home.action.activity': 'Voir les changements', 'home.action.activityCopy': 'Consultez ce qui est prêt ou en cours.',
    'home.action.open': 'Ouvrir',
    'home.healthTitle': 'Votre serveur en un coup d’œil', 'home.healthSubtitle': 'Seulement ce qui mérite votre attention.',
    'home.health.good.title': 'Tout va bien !', 'home.health.good.copy': 'Votre serveur est prêt à accueillir votre communauté.',
    'home.health.checking.title': 'Bunny vérifie quelques détails', 'home.health.checking.copy': 'Vous pouvez continuer pendant l’arrivée des dernières informations.',
    'home.health.attention.title': '{{count}} point demande votre attention', 'home.health.attention.copy': 'Ouvrez la zone conseillée pour voir la prochaine action.',
    'home.connection.online': 'En ligne', 'home.connection.action': 'À corriger', 'home.connection.checking': 'Vérification',
    'home.stat.channels': 'salons', 'home.stat.categories': 'catégories', 'home.stat.roles': 'rôles', 'home.stat.connection': 'état du serveur',
    'home.technicalDetails': 'Détails techniques', 'home.technicalSummary': 'Couverture : {{coverage}} · Fraîcheur : {{freshness}}',
    'home.setupTitle': 'Bien démarrer', 'home.setupSubtitle': 'Un parcours court vers un serveur accueillant.',
    'home.setup.identity': 'Personnalisez votre serveur', 'home.setup.identityCopy': 'Nom, image et description.',
    'home.setup.structure': 'Créez vos premiers espaces', 'home.setup.structureCopy': 'Salons et catégories pour votre communauté.',
    'home.setup.access': 'Configurez les accès', 'home.setup.accessCopy': 'Décidez qui peut voir et participer.',
    'home.setup.automate': 'Ajoutez une automatisation utile', 'home.setup.automateCopy': 'Des assistants facultatifs quand vous êtes prêt.',
    'home.continue': 'Continuer à construire',
    'onboarding.title': 'Première configuration du serveur',
    'onboarding.subtitle': 'Bunny vérifie Discord, importe la structure réelle et contrôle ce que le bot peut faire en sécurité.',
    'onboarding.bot': 'Bot détecté dans ce serveur',
    'onboarding.identity': 'Identité du configurateur vérifiée',
    'onboarding.configurator': 'Configurateur propriétaire ou administrateur Discord',
    'onboarding.permissions': 'Permissions du bot auditées',
    'onboarding.structure': 'Structure initiale importée',
    'onboarding.audit': 'Audit initial des capacités terminé',
    'onboarding.constraints': 'Limites et contraintes applicables vérifiées',
    'onboarding.constraintsCount': '{{count}} fonctions limitées',
    'onboarding.configuration': 'Configuration par défaut du dashboard prête',
    'onboarding.activation': 'Tenant activé',
    'onboarding.import': 'Importer et vérifier la structure',
    'onboarding.importing': 'Synchronisation initiale mise en file. Attente du worker Discord…',
    'onboarding.activate': 'Activer ce serveur',
    'onboarding.refresh': 'Actualiser les vérifications',
    'onboarding.done': 'Prêt',
    'onboarding.waiting': 'En attente',
    'onboarding.blocked': 'Bloqué',
    'onboarding.counts': '{{channels}} salons / threads · {{roles}} rôles',
    'onboarding.limited': 'Certaines opérations du bot sont indisponibles. Bunny bloquera les changements impossibles et indiquera la permission manquante.',
    'onboarding.permissionDetails': 'Capacités et permissions du bot',
    'onboarding.leastPrivilege': 'Bunny demande uniquement les permissions nécessaires à chaque fonction. ADMINISTRATOR n’est jamais exigé par commodité.',
    'onboarding.requiredPermissions': 'Permissions requises et justification',
    'onboarding.permission.none': 'Aucune permission Discord supplémentaire n’est requise pour ce contrôle.',
    'onboarding.permission.manageChannels': 'Créer, renommer, déplacer et configurer les salons et catégories Discord.',
    'onboarding.permission.manageRoles': 'Créer les rôles et gérer les overwrites sans demander ADMINISTRATOR.',
    'onboarding.permission.viewAuditLog': 'Rapprocher les changements Discord de l’activité Bunny.',
    'onboarding.permission.manageWebhooks': 'Gérer les webhooks uniquement lorsqu’une fonction webhook est activée.',
    'onboarding.permission.viewChannel': 'Observer le salon cible avant d’agir.',
    'onboarding.permission.sendMessages': 'Publier un message dans le salon sélectionné.',
    'onboarding.permission.sendThreads': 'Publier dans le thread sélectionné.',
    'onboarding.permission.manageThreads': 'Gérer le thread sélectionné.',
    'onboarding.permission.generic': 'Permission exigée par Discord pour cette opération : {{permission}}.',
    'onboarding.operation.createChannel': 'Créer un salon', 'onboarding.operation.manageChannel': 'Gérer un salon', 'onboarding.operation.reorderChannels': 'Réordonner les salons',
    'onboarding.operation.manageOverwrites': 'Gérer les accès aux salons', 'onboarding.operation.createRole': 'Créer un rôle', 'onboarding.operation.manageRole': 'Gérer un rôle',
    'onboarding.operation.reorderRoles': 'Réordonner les rôles', 'onboarding.operation.assignRole': 'Attribuer un rôle', 'onboarding.operation.sendMessage': 'Envoyer un message', 'onboarding.operation.manageThread': 'Gérer un thread',
    'onboarding.outcome.can': 'Disponible avec les permissions actuellement observées.', 'onboarding.outcome.cannot': 'Indisponible tant que la permission indiquée n’est pas accordée.', 'onboarding.outcome.unknown': 'Bunny a besoin d’une ressource précise pour vérifier cette fonction.',
    'onboarding.cause.missingPermission': 'Permission Discord manquante : {{permission}}.', 'onboarding.cause.channelContext': 'Un salon cible est nécessaire pour une décision exacte.', 'onboarding.cause.roleContext': 'Un rôle cible est nécessaire pour vérifier la hiérarchie.',
    'onboarding.cause.intentMissing': 'Un intent Gateway requis est indisponible.', 'onboarding.cause.inactive': 'Le tenant n’est pas encore actif.', 'onboarding.cause.incomplete': 'Les preuves Discord en cache sont incomplètes ; actualisez l’import avant d’agir.',
    'onboarding.remediation': 'Accordez uniquement la permission indiquée pour cette fonction, puis actualisez les contrôles.',
    'onboarding.notAdmin': 'Seul le propriétaire du serveur ou un membre avec ADMINISTRATOR dans Discord peut effectuer la configuration initiale.',
    'onboarding.gatewayMissing': 'Le Gateway du bot n’a pas encore observé ce serveur. Vérifiez que le processus bot tourne et que le bot est installé sur ce serveur.',
    'onboarding.importRequired': 'Lancez l’import initial pour établir un snapshot local complet.',
    'onboarding.permissionsPending': 'Les preuves de permissions du bot ne sont pas encore complètes.',
    'onboarding.active': 'Ce serveur est actif. Ouverture du dashboard…',
    'errors.onboarding.notReady': 'La configuration n’est pas encore prête. Actualisez les contrôles et corrigez le point bloquant.',
  },
  de: {
    'nav.overview': 'Übersicht',
    'guilds.empty': 'Kein geeigneter Discord-Server gefunden.',
    'guilds.subtitle': 'Server, auf denen Bunny installiert ist, werden hier angezeigt.',
    'guilds.setup': 'Einrichten',
    'guilds.blocked': 'Die Ersteinrichtung erfordert den Serverbesitzer oder einen Discord-Administrator.',
    'guilds.noAccess': 'Der Bot ist installiert, aber Ihr Dashboard-Konto hat keinen Zugriff.',
    'shell.recentServers': 'Letzte Server',
    'shell.brand': 'Bunny',
    'shell.brandInitial': 'B',
    'shell.tagline': 'Server Assistant',
    'shell.workspace': 'Arbeitsbereich',
    'shell.searchHint': 'Suchen oder Befehl ausführen',
    'shell.openNavigation': 'Navigationsmenü öffnen',
    'shell.closeNavigation': 'Navigationsmenü schließen',
    'shell.navigation': 'Hauptnavigation',
    'shell.home': 'Start',
    'shell.build': 'Erstellen',
    'shell.access': 'Zugriff',
    'shell.automate': 'Automatisieren',
    'shell.activity': 'Aktivität',
    'shell.expert': 'Erweiterte Werkzeuge',
    'shell.helpTitle': 'Hilfe benötigt?',
    'shell.helpCopy': 'Bunny führt Sie durch',
    'shell.notifications': 'Benachrichtigungen',
    'shell.account': 'Konto und Kurzbefehle',
    'overview.title': 'Serverübersicht',
    'overview.subtitle': 'Eine aktuelle Betriebsansicht dieses Discord-Servers.',
    'overview.structure': 'Struktur',
    'overview.roles': 'Rollen',
    'overview.coverage': 'Cache-Abdeckung',
    'overview.connection': 'Live-Verbindung',
    'overview.openStructure': 'Struktur öffnen',
    'overview.openDiagnostics': 'Diagnose öffnen',
    'home.title': 'Start', 'home.subtitle': 'Erstellen und verwalten Sie Ihren Discord-Server einfach mit Bunny.',
    'home.welcome': 'Willkommen, {{name}}', 'home.heroTitle': 'Bauen Sie eine Community, die zu Ihnen passt.',
    'home.heroCopy': 'Bunny bringt Struktur, Zugriffe und nächste Änderungen an einem freundlichen Ort zusammen.',
    'home.primaryAction': 'Meinen Server bauen', 'home.secondaryAction': 'Zugriffe verwalten',
    'home.quickTitle': 'Schnellaktionen', 'home.quickSubtitle': 'Die wichtigsten Aufgaben mit einem Klick.',
    'home.action.channel': 'Kanal erstellen', 'home.action.channelCopy': 'Fügen Sie einen Ort für Gespräche hinzu.',
    'home.action.access': 'Zugriffe verwalten', 'home.action.accessCopy': 'Wählen Sie, wer sehen und teilnehmen darf.',
    'home.action.roles': 'Rollen organisieren', 'home.action.rolesCopy': 'Halten Sie Verantwortungen klar und einfach.',
    'home.action.automate': 'Assistent starten', 'home.action.automateCopy': 'Lassen Sie Bunny durch die Einrichtung führen.',
    'home.action.activity': 'Änderungen ansehen', 'home.action.activityCopy': 'Sehen Sie, was bereit ist oder läuft.',
    'home.action.open': 'Öffnen',
    'home.healthTitle': 'Ihr Server auf einen Blick', 'home.healthSubtitle': 'Nur das, was Ihre Aufmerksamkeit braucht.',
    'home.health.good.title': 'Alles sieht gut aus!', 'home.health.good.copy': 'Ihr Server ist bereit für Ihre Community.',
    'home.health.checking.title': 'Bunny prüft einige Details', 'home.health.checking.copy': 'Sie können weiterarbeiten, während Daten eintreffen.',
    'home.health.attention.title': '{{count}} Punkt braucht Ihre Aufmerksamkeit', 'home.health.attention.copy': 'Öffnen Sie den empfohlenen Bereich für den nächsten Schritt.',
    'home.connection.online': 'Online', 'home.connection.action': 'Aktion nötig', 'home.connection.checking': 'Prüfung',
    'home.stat.channels': 'Kanäle', 'home.stat.categories': 'Kategorien', 'home.stat.roles': 'Rollen', 'home.stat.connection': 'Serverstatus',
    'home.technicalDetails': 'Technische Details', 'home.technicalSummary': 'Abdeckung: {{coverage}} · Aktualität: {{freshness}}',
    'home.setupTitle': 'Gut starten', 'home.setupSubtitle': 'Ein kurzer Weg zu einem einladenden Server.',
    'home.setup.identity': 'Server personalisieren', 'home.setup.identityCopy': 'Name, Bild und Beschreibung.',
    'home.setup.structure': 'Erste Bereiche erstellen', 'home.setup.structureCopy': 'Kanäle und Kategorien für Ihre Community.',
    'home.setup.access': 'Zugriffe konfigurieren', 'home.setup.accessCopy': 'Bestimmen Sie, wer sehen und teilnehmen darf.',
    'home.setup.automate': 'Nützliche Automation hinzufügen', 'home.setup.automateCopy': 'Optionale Assistenten, wenn Sie bereit sind.',
    'home.continue': 'Weiterbauen',
    'onboarding.title': 'Erste Servereinrichtung',
    'onboarding.subtitle': 'Bunny prüft Discord, importiert die reale Struktur und kontrolliert die sicheren Bot-Funktionen.',
    'onboarding.bot': 'Bot auf diesem Server erkannt',
    'onboarding.identity': 'Identität des Konfigurators bestätigt',
    'onboarding.configurator': 'Konfigurator ist Besitzer oder Discord-Administrator',
    'onboarding.permissions': 'Bot-Berechtigungen geprüft',
    'onboarding.structure': 'Anfangsstruktur importiert',
    'onboarding.audit': 'Erstes Fähigkeitsaudit abgeschlossen',
    'onboarding.constraints': 'Anwendbare Grenzen und Einschränkungen geprüft',
    'onboarding.constraintsCount': '{{count}} eingeschränkte Funktionen',
    'onboarding.configuration': 'Dashboard-Standardwerte vorbereitet',
    'onboarding.activation': 'Tenant aktiviert',
    'onboarding.import': 'Struktur importieren und prüfen',
    'onboarding.importing': 'Initiale Synchronisierung eingereiht. Warten auf den Discord-Worker…',
    'onboarding.activate': 'Diesen Server aktivieren',
    'onboarding.refresh': 'Prüfungen aktualisieren',
    'onboarding.done': 'Bereit',
    'onboarding.waiting': 'Wartet',
    'onboarding.blocked': 'Blockiert',
    'onboarding.counts': '{{channels}} Kanäle / Threads · {{roles}} Rollen',
    'onboarding.limited': 'Einige Bot-Operationen sind nicht verfügbar. Bunny blockiert unmögliche Änderungen und zeigt die fehlende Berechtigung an.',
    'onboarding.permissionDetails': 'Bot-Fähigkeiten und Berechtigungen',
    'onboarding.leastPrivilege': 'Bunny fordert nur die je Funktion nötigen Rechte an. ADMINISTRATOR wird nie aus Bequemlichkeit verlangt.',
    'onboarding.requiredPermissions': 'Erforderliche Berechtigungen und Zweck',
    'onboarding.permission.none': 'Für diese Prüfung ist keine zusätzliche Discord-Berechtigung nötig.',
    'onboarding.permission.manageChannels': 'Discord-Kanäle und Kategorien erstellen, umbenennen, verschieben und konfigurieren.',
    'onboarding.permission.manageRoles': 'Rollen erstellen und Overwrites verwalten, ohne ADMINISTRATOR anzufordern.',
    'onboarding.permission.viewAuditLog': 'Discord-Änderungen mit der Bunny-Aktivität abgleichen.',
    'onboarding.permission.manageWebhooks': 'Webhooks nur bei aktivierter Webhook-Funktion verwalten.',
    'onboarding.permission.viewChannel': 'Den Zielkanal vor einer Aktion beobachten.',
    'onboarding.permission.sendMessages': 'Eine Nachricht im ausgewählten Kanal veröffentlichen.',
    'onboarding.permission.sendThreads': 'In einem ausgewählten Thread veröffentlichen.',
    'onboarding.permission.manageThreads': 'Den ausgewählten Thread verwalten.',
    'onboarding.permission.generic': 'Von Discord für diese Aktion benötigt: {{permission}}.',
    'onboarding.operation.createChannel': 'Kanal erstellen', 'onboarding.operation.manageChannel': 'Kanal verwalten', 'onboarding.operation.reorderChannels': 'Kanäle sortieren',
    'onboarding.operation.manageOverwrites': 'Kanalzugriff verwalten', 'onboarding.operation.createRole': 'Rolle erstellen', 'onboarding.operation.manageRole': 'Rolle verwalten',
    'onboarding.operation.reorderRoles': 'Rollen sortieren', 'onboarding.operation.assignRole': 'Rolle zuweisen', 'onboarding.operation.sendMessage': 'Nachricht senden', 'onboarding.operation.manageThread': 'Thread verwalten',
    'onboarding.outcome.can': 'Mit den aktuell beobachteten Berechtigungen verfügbar.', 'onboarding.outcome.cannot': 'Nicht verfügbar, bis die genannte Berechtigung erteilt wird.', 'onboarding.outcome.unknown': 'Bunny benötigt eine konkrete Ressource, um diese Funktion zu prüfen.',
    'onboarding.cause.missingPermission': 'Fehlende Discord-Berechtigung: {{permission}}.', 'onboarding.cause.channelContext': 'Für eine genaue Entscheidung ist ein Zielkanal nötig.', 'onboarding.cause.roleContext': 'Zur Hierarchieprüfung ist eine Zielrolle nötig.',
    'onboarding.cause.intentMissing': 'Ein erforderlicher Gateway-Intent fehlt.', 'onboarding.cause.inactive': 'Der Tenant ist noch nicht aktiv.', 'onboarding.cause.incomplete': 'Die Discord-Daten im Cache sind unvollständig; Import vor der Aktion aktualisieren.',
    'onboarding.remediation': 'Nur die genannte Berechtigung für diese Funktion erteilen und die Prüfungen aktualisieren.',
    'onboarding.notAdmin': 'Nur der Serverbesitzer oder ein Mitglied mit Discord-ADMINISTRATOR kann die Ersteinrichtung durchführen.',
    'onboarding.gatewayMissing': 'Der Bot-Gateway hat diesen Server noch nicht beobachtet. Prüfen Sie, ob der Bot-Prozess läuft und installiert ist.',
    'onboarding.importRequired': 'Starten Sie den Erstimport, um einen vollständigen lokalen Snapshot zu erstellen.',
    'onboarding.permissionsPending': 'Die Nachweise für Bot-Berechtigungen sind noch nicht vollständig.',
    'onboarding.active': 'Dieser Server ist aktiv. Dashboard wird geöffnet…',
    'errors.onboarding.notReady': 'Die Einrichtung ist noch nicht bereit. Aktualisieren Sie die Prüfungen und beheben Sie den blockierenden Punkt.',
  },
  es: {
    'nav.overview': 'Resumen',
    'guilds.empty': 'No se encontró ningún servidor de Discord elegible.',
    'guilds.subtitle': 'Aquí aparecen los servidores donde está instalado Bunny.',
    'guilds.setup': 'Configurar',
    'guilds.blocked': 'La configuración inicial requiere al propietario del servidor o a un administrador de Discord.',
    'guilds.noAccess': 'El bot está instalado, pero tu cuenta no tiene acceso al panel.',
    'shell.recentServers': 'Servidores recientes',
    'shell.brand': 'Bunny',
    'shell.brandInitial': 'B',
    'shell.tagline': 'Server Assistant',
    'shell.workspace': 'Espacio de trabajo',
    'shell.searchHint': 'Buscar o ejecutar un comando',
    'shell.openNavigation': 'Abrir menú de navegación',
    'shell.closeNavigation': 'Cerrar menú de navegación',
    'shell.navigation': 'Navegación principal',
    'shell.home': 'Inicio',
    'shell.build': 'Construir',
    'shell.access': 'Acceso',
    'shell.automate': 'Automatizar',
    'shell.activity': 'Actividad',
    'shell.expert': 'Herramientas avanzadas',
    'shell.helpTitle': '¿Necesitas ayuda?',
    'shell.helpCopy': 'Deja que Bunny te guíe',
    'shell.notifications': 'Notificaciones',
    'shell.account': 'Cuenta y accesos rápidos',
    'overview.title': 'Resumen del servidor',
    'overview.subtitle': 'Una vista operativa en tiempo real de este servidor de Discord.',
    'overview.structure': 'Estructura',
    'overview.roles': 'Roles',
    'overview.coverage': 'Cobertura de caché',
    'overview.connection': 'Conexión en tiempo real',
    'overview.openStructure': 'Abrir estructura',
    'overview.openDiagnostics': 'Abrir diagnósticos',
    'home.title': 'Inicio', 'home.subtitle': 'Crea y gestiona tu servidor de Discord fácilmente con Bunny.',
    'home.welcome': 'Bienvenido, {{name}}', 'home.heroTitle': 'Construye una comunidad que se sienta tuya.',
    'home.heroCopy': 'Bunny reúne la estructura, los accesos y los próximos cambios en un espacio agradable.',
    'home.primaryAction': 'Construir mi servidor', 'home.secondaryAction': 'Gestionar accesos',
    'home.quickTitle': 'Acciones rápidas', 'home.quickSubtitle': 'Las tareas más útiles, a un clic.',
    'home.action.channel': 'Crear un canal', 'home.action.channelCopy': 'Añade un lugar para conversar con tu comunidad.',
    'home.action.access': 'Gestionar accesos', 'home.action.accessCopy': 'Elige quién puede ver y participar.',
    'home.action.roles': 'Organizar roles', 'home.action.rolesCopy': 'Mantén responsabilidades claras y sencillas.',
    'home.action.automate': 'Iniciar un asistente', 'home.action.automateCopy': 'Deja que Bunny guíe tu próxima configuración.',
    'home.action.activity': 'Ver cambios', 'home.action.activityCopy': 'Consulta lo que está listo o en curso.',
    'home.action.open': 'Abrir',
    'home.healthTitle': 'Tu servidor de un vistazo', 'home.healthSubtitle': 'Solo lo que requiere tu atención.',
    'home.health.good.title': '¡Todo va bien!', 'home.health.good.copy': 'Tu servidor está listo para recibir a la comunidad.',
    'home.health.checking.title': 'Bunny está comprobando algunos detalles', 'home.health.checking.copy': 'Puedes seguir mientras llegan los últimos datos.',
    'home.health.attention.title': '{{count}} punto requiere tu atención', 'home.health.attention.copy': 'Abre el área sugerida para ver el siguiente paso.',
    'home.connection.online': 'En línea', 'home.connection.action': 'Requiere acción', 'home.connection.checking': 'Comprobando',
    'home.stat.channels': 'canales', 'home.stat.categories': 'categorías', 'home.stat.roles': 'roles', 'home.stat.connection': 'estado del servidor',
    'home.technicalDetails': 'Detalles técnicos', 'home.technicalSummary': 'Cobertura: {{coverage}} · Actualidad: {{freshness}}',
    'home.setupTitle': 'Primeros pasos', 'home.setupSubtitle': 'Un camino corto hacia un servidor acogedor.',
    'home.setup.identity': 'Personaliza tu servidor', 'home.setup.identityCopy': 'Nombre, imagen y descripción.',
    'home.setup.structure': 'Crea tus primeros espacios', 'home.setup.structureCopy': 'Canales y categorías para tu comunidad.',
    'home.setup.access': 'Configura los accesos', 'home.setup.accessCopy': 'Decide quién puede ver y participar.',
    'home.setup.automate': 'Añade una automatización útil', 'home.setup.automateCopy': 'Asistentes opcionales cuando estés preparado.',
    'home.continue': 'Seguir construyendo',
    'onboarding.title': 'Configuración inicial del servidor',
    'onboarding.subtitle': 'Bunny verifica Discord, importa la estructura real y comprueba qué puede hacer el bot de forma segura.',
    'onboarding.bot': 'Bot detectado en este servidor',
    'onboarding.identity': 'Identidad del configurador verificada',
    'onboarding.configurator': 'El configurador es propietario o administrador de Discord',
    'onboarding.permissions': 'Permisos del bot auditados',
    'onboarding.structure': 'Estructura inicial importada',
    'onboarding.audit': 'Auditoría inicial de capacidades completada',
    'onboarding.constraints': 'Límites y restricciones aplicables revisados',
    'onboarding.constraintsCount': '{{count}} funciones limitadas',
    'onboarding.configuration': 'Valores predeterminados del panel preparados',
    'onboarding.activation': 'Tenant activado',
    'onboarding.import': 'Importar y verificar estructura',
    'onboarding.importing': 'Sincronización inicial en cola. Esperando al worker de Discord…',
    'onboarding.activate': 'Activar este servidor',
    'onboarding.refresh': 'Actualizar comprobaciones',
    'onboarding.done': 'Listo',
    'onboarding.waiting': 'En espera',
    'onboarding.blocked': 'Bloqueado',
    'onboarding.counts': '{{channels}} canales / hilos · {{roles}} roles',
    'onboarding.limited': 'Algunas operaciones del bot no están disponibles. Bunny bloqueará cambios imposibles y mostrará el permiso que falta.',
    'onboarding.permissionDetails': 'Capacidades y permisos del bot',
    'onboarding.leastPrivilege': 'Bunny solicita solo los permisos necesarios para cada función. ADMINISTRATOR nunca se exige por comodidad.',
    'onboarding.requiredPermissions': 'Permisos requeridos y finalidad',
    'onboarding.permission.none': 'Esta comprobación no requiere permisos adicionales de Discord.',
    'onboarding.permission.manageChannels': 'Crear, renombrar, mover y configurar canales y categorías de Discord.',
    'onboarding.permission.manageRoles': 'Crear roles y gestionar overwrites sin solicitar ADMINISTRATOR.',
    'onboarding.permission.viewAuditLog': 'Relacionar los cambios de Discord con la actividad de Bunny.',
    'onboarding.permission.manageWebhooks': 'Gestionar webhooks solo cuando una función de webhook esté activada.',
    'onboarding.permission.viewChannel': 'Observar el canal de destino antes de actuar.',
    'onboarding.permission.sendMessages': 'Publicar un mensaje en el canal seleccionado.',
    'onboarding.permission.sendThreads': 'Publicar dentro del hilo seleccionado.',
    'onboarding.permission.manageThreads': 'Gestionar el hilo seleccionado.',
    'onboarding.permission.generic': 'Discord exige este permiso para la operación: {{permission}}.',
    'onboarding.operation.createChannel': 'Crear un canal', 'onboarding.operation.manageChannel': 'Gestionar un canal', 'onboarding.operation.reorderChannels': 'Reordenar canales',
    'onboarding.operation.manageOverwrites': 'Gestionar acceso a canales', 'onboarding.operation.createRole': 'Crear un rol', 'onboarding.operation.manageRole': 'Gestionar un rol',
    'onboarding.operation.reorderRoles': 'Reordenar roles', 'onboarding.operation.assignRole': 'Asignar un rol', 'onboarding.operation.sendMessage': 'Enviar un mensaje', 'onboarding.operation.manageThread': 'Gestionar un hilo',
    'onboarding.outcome.can': 'Disponible con los permisos observados actualmente.', 'onboarding.outcome.cannot': 'No disponible hasta que se conceda el permiso indicado.', 'onboarding.outcome.unknown': 'Bunny necesita un recurso concreto para verificar esta función.',
    'onboarding.cause.missingPermission': 'Permiso de Discord ausente: {{permission}}.', 'onboarding.cause.channelContext': 'Se necesita un canal de destino para una decisión exacta.', 'onboarding.cause.roleContext': 'Se necesita un rol de destino para comprobar la jerarquía.',
    'onboarding.cause.intentMissing': 'Falta un intent de Gateway requerido.', 'onboarding.cause.inactive': 'El tenant aún no está activo.', 'onboarding.cause.incomplete': 'La evidencia de Discord en caché está incompleta; actualiza la importación antes de actuar.',
    'onboarding.remediation': 'Concede solo el permiso indicado para esta función y actualiza las comprobaciones.',
    'onboarding.notAdmin': 'Solo el propietario del servidor o un miembro con ADMINISTRATOR en Discord puede realizar la configuración inicial.',
    'onboarding.gatewayMissing': 'El Gateway del bot aún no ha observado este servidor. Comprueba que el proceso del bot esté activo e instalado.',
    'onboarding.importRequired': 'Ejecuta la importación inicial para establecer un snapshot local completo.',
    'onboarding.permissionsPending': 'La evidencia de permisos del bot aún no está completa.',
    'onboarding.active': 'Este servidor está activo. Abriendo el panel…',
    'errors.onboarding.notReady': 'La configuración aún no está lista. Actualiza las comprobaciones y resuelve el bloqueo.',
  },
} as const

export type Phase2Locale = keyof typeof phase2Packs
export type Phase2MessageKey = keyof (typeof phase2Packs)['en']
