export const phase2Packs = {
  en: {
    'nav.overview': 'Overview',
    'guilds.empty': 'No eligible Discord server was found.',
    'guilds.subtitle': 'Servers where Discord Infrastructure Designer is installed are shown here.',
    'guilds.setup': 'Configure',
    'guilds.blocked': 'Setup requires the server owner or a Discord administrator.',
    'guilds.noAccess': 'The bot is installed, but your dashboard account has no access.',
    'shell.recentServers': 'Recent servers',
    'shell.workspace': 'Workspace',
    'shell.searchHint': 'Search or run a command',
    'overview.title': 'Server overview',
    'overview.subtitle': 'A live operational view of this Discord server.',
    'overview.structure': 'Structure',
    'overview.roles': 'Roles',
    'overview.coverage': 'Cache coverage',
    'overview.connection': 'Live connection',
    'overview.openStructure': 'Open structure',
    'overview.openDiagnostics': 'Open diagnostics',
    'onboarding.title': 'First server setup',
    'onboarding.subtitle': 'DID verifies Discord, imports the real structure, audits bot capabilities, then activates the tenant.',
    'onboarding.bot': 'Bot detected in this server',
    'onboarding.configurator': 'Configurator is owner or Discord administrator',
    'onboarding.permissions': 'Bot permissions audited',
    'onboarding.structure': 'Initial structure imported',
    'onboarding.audit': 'Initial capability audit complete',
    'onboarding.configuration': 'Dashboard defaults prepared',
    'onboarding.activation': 'Tenant activated',
    'onboarding.import': 'Import and verify structure',
    'onboarding.importing': 'Initial sync queued. Waiting for the Discord worker…',
    'onboarding.activate': 'Activate this server',
    'onboarding.refresh': 'Refresh checks',
    'onboarding.done': 'Ready',
    'onboarding.waiting': 'Waiting',
    'onboarding.blocked': 'Blocked',
    'onboarding.counts': '{{channels}} channels / threads · {{roles}} roles',
    'onboarding.limited': 'Some bot operations are unavailable. DID will block impossible mutations and show the exact missing permission.',
    'onboarding.notAdmin': 'Only the server owner or a member with Discord ADMINISTRATOR can perform the initial setup.',
    'onboarding.gatewayMissing': 'The bot Gateway has not observed this server yet. Check that the bot process is running and installed on this server.',
    'onboarding.importRequired': 'Run the initial import to establish a complete local snapshot.',
    'onboarding.permissionsPending': 'Bot permission evidence is not complete yet.',
    'onboarding.active': 'This server is active. Opening the dashboard…',
    'errors.onboarding.notReady': 'Setup is not ready yet. Refresh the checks and resolve the blocking item.',
  },
  fr: {
    'nav.overview': 'Vue d’ensemble',
    'guilds.empty': 'Aucun serveur Discord admissible trouvé.',
    'guilds.subtitle': 'Les serveurs sur lesquels Discord Infrastructure Designer est installé apparaissent ici.',
    'guilds.setup': 'Configurer',
    'guilds.blocked': 'La configuration initiale exige le propriétaire du serveur ou un administrateur Discord.',
    'guilds.noAccess': 'Le bot est installé, mais votre compte n’a pas accès au dashboard.',
    'shell.recentServers': 'Serveurs récents',
    'shell.workspace': 'Espace de travail',
    'shell.searchHint': 'Rechercher ou lancer une commande',
    'overview.title': 'Vue d’ensemble du serveur',
    'overview.subtitle': 'Une vue opérationnelle en temps réel de ce serveur Discord.',
    'overview.structure': 'Structure',
    'overview.roles': 'Rôles',
    'overview.coverage': 'Couverture du cache',
    'overview.connection': 'Connexion temps réel',
    'overview.openStructure': 'Ouvrir la structure',
    'overview.openDiagnostics': 'Ouvrir les diagnostics',
    'onboarding.title': 'Première configuration du serveur',
    'onboarding.subtitle': 'DID vérifie Discord, importe la structure réelle, audite les capacités du bot puis active le tenant.',
    'onboarding.bot': 'Bot détecté dans ce serveur',
    'onboarding.configurator': 'Configurateur propriétaire ou administrateur Discord',
    'onboarding.permissions': 'Permissions du bot auditées',
    'onboarding.structure': 'Structure initiale importée',
    'onboarding.audit': 'Audit initial des capacités terminé',
    'onboarding.configuration': 'Configuration par défaut du dashboard prête',
    'onboarding.activation': 'Tenant activé',
    'onboarding.import': 'Importer et vérifier la structure',
    'onboarding.importing': 'Synchronisation initiale mise en file. Attente du worker Discord…',
    'onboarding.activate': 'Activer ce serveur',
    'onboarding.refresh': 'Actualiser les vérifications',
    'onboarding.done': 'Prêt',
    'onboarding.waiting': 'En attente',
    'onboarding.blocked': 'Bloqué',
    'onboarding.counts': '{{channels}} salons / threads · {{roles}} rôles',
    'onboarding.limited': 'Certaines opérations du bot sont indisponibles. DID bloquera les mutations impossibles et indiquera précisément la permission manquante.',
    'onboarding.notAdmin': 'Seul le propriétaire du serveur ou un membre avec ADMINISTRATOR dans Discord peut effectuer la configuration initiale.',
    'onboarding.gatewayMissing': 'Le Gateway du bot n’a pas encore observé ce serveur. Vérifiez que le processus bot tourne et que le bot est installé sur ce serveur.',
    'onboarding.importRequired': 'Lancez l’import initial pour établir un snapshot local complet.',
    'onboarding.permissionsPending': 'Les preuves de permissions du bot ne sont pas encore complètes.',
    'onboarding.active': 'Ce serveur est actif. Ouverture du dashboard…',
    'errors.onboarding.notReady': 'La configuration n’est pas encore prête. Actualisez les contrôles et corrigez le point bloquant.',
  },
  de: {
    'nav.overview': 'Übersicht',
    'guilds.empty': 'Kein geeigneter Discord-Server gefunden.',
    'guilds.subtitle': 'Server, auf denen Discord Infrastructure Designer installiert ist, werden hier angezeigt.',
    'guilds.setup': 'Einrichten',
    'guilds.blocked': 'Die Ersteinrichtung erfordert den Serverbesitzer oder einen Discord-Administrator.',
    'guilds.noAccess': 'Der Bot ist installiert, aber Ihr Dashboard-Konto hat keinen Zugriff.',
    'shell.recentServers': 'Letzte Server',
    'shell.workspace': 'Arbeitsbereich',
    'shell.searchHint': 'Suchen oder Befehl ausführen',
    'overview.title': 'Serverübersicht',
    'overview.subtitle': 'Eine aktuelle Betriebsansicht dieses Discord-Servers.',
    'overview.structure': 'Struktur',
    'overview.roles': 'Rollen',
    'overview.coverage': 'Cache-Abdeckung',
    'overview.connection': 'Live-Verbindung',
    'overview.openStructure': 'Struktur öffnen',
    'overview.openDiagnostics': 'Diagnose öffnen',
    'onboarding.title': 'Erste Servereinrichtung',
    'onboarding.subtitle': 'DID prüft Discord, importiert die reale Struktur, auditiert Bot-Fähigkeiten und aktiviert dann den Tenant.',
    'onboarding.bot': 'Bot auf diesem Server erkannt',
    'onboarding.configurator': 'Konfigurator ist Besitzer oder Discord-Administrator',
    'onboarding.permissions': 'Bot-Berechtigungen geprüft',
    'onboarding.structure': 'Anfangsstruktur importiert',
    'onboarding.audit': 'Erstes Fähigkeitsaudit abgeschlossen',
    'onboarding.configuration': 'Dashboard-Standardwerte vorbereitet',
    'onboarding.activation': 'Tenant aktiviert',
    'onboarding.import': 'Struktur importieren und prüfen',
    'onboarding.importing': 'Initiale Synchronisierung eingereiht. Warten auf den Discord-Worker…',
    'onboarding.activate': 'Diesen Server aktivieren',
    'onboarding.refresh': 'Prüfungen aktualisieren',
    'onboarding.done': 'Bereit',
    'onboarding.waiting': 'Wartet',
    'onboarding.blocked': 'Blockiert',
    'onboarding.counts': '{{channels}} Kanäle / Threads · {{roles}} Rollen',
    'onboarding.limited': 'Einige Bot-Operationen sind nicht verfügbar. DID blockiert unmögliche Änderungen und zeigt die fehlende Berechtigung an.',
    'onboarding.notAdmin': 'Nur der Serverbesitzer oder ein Mitglied mit Discord-ADMINISTRATOR kann die Ersteinrichtung durchführen.',
    'onboarding.gatewayMissing': 'Der Bot-Gateway hat diesen Server noch nicht beobachtet. Prüfen Sie, ob der Bot-Prozess läuft und installiert ist.',
    'onboarding.importRequired': 'Starten Sie den Erstimport, um einen vollständigen lokalen Snapshot zu erstellen.',
    'onboarding.permissionsPending': 'Die Nachweise für Bot-Berechtigungen sind noch nicht vollständig.',
    'onboarding.active': 'Dieser Server ist aktiv. Dashboard wird geöffnet…',
    'errors.onboarding.notReady': 'Die Einrichtung ist noch nicht bereit. Aktualisieren Sie die Prüfungen und beheben Sie den blockierenden Punkt.',
  },
  es: {
    'nav.overview': 'Resumen',
    'guilds.empty': 'No se encontró ningún servidor de Discord elegible.',
    'guilds.subtitle': 'Aquí aparecen los servidores donde está instalado Discord Infrastructure Designer.',
    'guilds.setup': 'Configurar',
    'guilds.blocked': 'La configuración inicial requiere al propietario del servidor o a un administrador de Discord.',
    'guilds.noAccess': 'El bot está instalado, pero tu cuenta no tiene acceso al panel.',
    'shell.recentServers': 'Servidores recientes',
    'shell.workspace': 'Espacio de trabajo',
    'shell.searchHint': 'Buscar o ejecutar un comando',
    'overview.title': 'Resumen del servidor',
    'overview.subtitle': 'Una vista operativa en tiempo real de este servidor de Discord.',
    'overview.structure': 'Estructura',
    'overview.roles': 'Roles',
    'overview.coverage': 'Cobertura de caché',
    'overview.connection': 'Conexión en tiempo real',
    'overview.openStructure': 'Abrir estructura',
    'overview.openDiagnostics': 'Abrir diagnósticos',
    'onboarding.title': 'Configuración inicial del servidor',
    'onboarding.subtitle': 'DID verifica Discord, importa la estructura real, audita las capacidades del bot y activa el tenant.',
    'onboarding.bot': 'Bot detectado en este servidor',
    'onboarding.configurator': 'El configurador es propietario o administrador de Discord',
    'onboarding.permissions': 'Permisos del bot auditados',
    'onboarding.structure': 'Estructura inicial importada',
    'onboarding.audit': 'Auditoría inicial de capacidades completada',
    'onboarding.configuration': 'Valores predeterminados del panel preparados',
    'onboarding.activation': 'Tenant activado',
    'onboarding.import': 'Importar y verificar estructura',
    'onboarding.importing': 'Sincronización inicial en cola. Esperando al worker de Discord…',
    'onboarding.activate': 'Activar este servidor',
    'onboarding.refresh': 'Actualizar comprobaciones',
    'onboarding.done': 'Listo',
    'onboarding.waiting': 'En espera',
    'onboarding.blocked': 'Bloqueado',
    'onboarding.counts': '{{channels}} canales / hilos · {{roles}} roles',
    'onboarding.limited': 'Algunas operaciones del bot no están disponibles. DID bloqueará cambios imposibles y mostrará el permiso que falta.',
    'onboarding.notAdmin': 'Solo el propietario del servidor o un miembro con ADMINISTRATOR en Discord puede realizar la configuración inicial.',
    'onboarding.gatewayMissing': 'El Gateway del bot aún no ha observado este servidor. Comprueba que el proceso del bot esté activo e instalado.',
    'onboarding.importRequired': 'Ejecuta la importación inicial para establecer un snapshot local completo.',
    'onboarding.permissionsPending': 'La evidencia de permisos del bot aún no está completa.',
    'onboarding.active': 'Este servidor está activo. Abriendo el panel…',
    'errors.onboarding.notReady': 'La configuración aún no está lista. Actualiza las comprobaciones y resuelve el bloqueo.',
  },
} as const

export type Phase2Locale = keyof typeof phase2Packs
export type Phase2MessageKey = keyof (typeof phase2Packs)['en']
