export const phase4Packs = {
  en: {
    'access.eyebrow': 'Access management',
    'access.openPlans': 'Review validated plan',
    'access.planReady': 'The proposal is validated and ready for confirmation in Plans.',
    'access.blocked.user': 'Your dashboard delegation does not allow this change.',
    'access.blocked.bot': 'The Discord bot cannot safely perform this change.',
    'access.blocked.unknown': 'The required capability cannot currently be verified.',
    'access.blocked.managed': 'Discord manages this role; it cannot be edited here.',
    'access.blocked.hierarchy': 'The bot role must be strictly above the target role.',
    'roles.subtitle': 'Manage the real Discord role hierarchy without manipulating raw bitfields.',
    'roles.hierarchy': 'Role hierarchy',
    'roles.create': 'Create role',
    'roles.edit': 'Rename role',
    'roles.delete': 'Delete role',
    'roles.moveUp': 'Move up',
    'roles.moveDown': 'Move down',
    'roles.name': 'Role name',
    'roles.position': 'Position {{position}}',
    'roles.permissionsSummary': '{{count}} known permissions',
    'roles.unknownBits': 'Unknown permission bits: {{value}}',
    'roles.noSelection': 'Select a role to inspect its Discord permissions and available actions.',
    'roles.details': 'Role details',
    'roles.managedHelp': 'Managed by Discord or an integration',
    'roles.previewTitle': 'Impact before mutation',
    'roles.createImpact': 'Creates a new Discord role with no base permissions. Nothing is applied until the plan is confirmed.',
    'roles.renameImpact': 'Renames the selected Discord role. Members keep the same role assignment.',
    'roles.deleteImpact': 'Deletes the selected Discord role. Discord removes that role assignment from every member.',
    'roles.reorderImpact': 'Changes only the role hierarchy position. This can change which roles the bot or moderators can manage.',
    'roles.prepare': 'Prepare proposal',
    'roles.cancelEdit': 'Cancel',
    'roles.botCapability': 'Bot capability',
    'roles.botCan': 'Bot can manage this role',
    'roles.botBlocked': 'Bot cannot manage this role',
    'roles.botUnknown': 'Bot capability is unknown',
    'capability.badge.can': 'Can',
    'capability.badge.cannot': 'Cannot',
    'capability.badge.unknown': 'Unknown',
    'capability.badge.loading': 'Checking',
    'capability.badge.error': 'Error',
    'capability.loading': 'Checking the bot capability…',
    'capability.errorTitle': 'Capability check failed',
    'capability.queryError': 'The capability service could not be reached. This is a request error, not an unknown Discord capability.',
    'capability.retry': 'Retry',
    'capability.cause.missingManageRoles': 'The bot does not have the Manage Roles permission.',
    'capability.cause.botRoleNotAboveTarget': 'The bot’s highest role is not strictly above “{{role}}”.',
    'capability.cause.targetManaged': 'Discord or an integration manages this role.',
    'capability.cause.defaultRole': 'The @everyone role cannot be changed by this action.',
    'capability.cause.botRolesIncomplete': 'The hierarchy cannot be checked because the bot’s roles are not fully synchronized.',
    'capability.cause.roleSnapshotMissing': 'The hierarchy cannot be checked because the bot or target role is missing from the local Discord data.',
    'capability.cause.botIdentityUnknown': 'The installed bot identity is not available in the local Discord data.',
    'capability.cause.installationNotActive': 'The bot installation is not active for this server.',
    'capability.cause.requiredIntentMissing': 'A Discord Gateway intent required for this check is unavailable.',
    'capability.cause.discordDataIncomplete': 'The cached Discord snapshot is incomplete or no longer current.',
    'capability.cause.responseIncomplete': 'The capability response did not contain the requested bot operation.',
    'capability.cause.unclassified': 'The backend returned an unrecognized capability blocker.',
    'capability.remediation.grantManageRoles': 'Grant the bot the Manage Roles permission.',
    'capability.remediation.moveBotRoleAboveTarget': 'Move the bot role above “{{role}}”.',
    'capability.remediation.refreshDiscordData': 'Refresh the Discord data, then retry.',
    'capability.remediation.restoreInstallation': 'Restore the bot installation for this server.',
    'capability.remediation.restoreRequiredIntent': 'Restore the required Gateway intent, then refresh Discord data.',
    'permissions.subtitle': 'Answer human access questions in Simple mode, or inspect the exact Discord resolution in Expert mode.',
    'permissions.mode.simple': 'Simple mode',
    'permissions.mode.expert': 'Expert mode',
    'permissions.resource': 'Discord resource',
    'permissions.principalType': 'Who are you configuring?',
    'permissions.principal.role': 'A role',
    'permissions.principal.member': 'A member or bot',
    'permissions.principal.newcomer': 'A newcomer (diagnosis only)',
    'permissions.role': 'Discord role',
    'permissions.memberId': 'Member / bot Discord ID',
    'permissions.requestedPermission': 'Permission to explain',
    'permissions.diagnose': 'Why this access?',
    'permissions.diagnosis': 'Effective access diagnosis',
    'permissions.effectiveBits': 'Effective bits: {{value}}',
    'permissions.outcome': 'Outcome: {{value}}',
    'permissions.coverage': 'Coverage: {{value}}',
    'permissions.freshness': 'Freshness: {{value}}',
    'permissions.trace': 'Discord resolution trace',
    'permissions.traceStep': 'Step {{index}}',
    'permissions.source': '{{type}} {{id}}',
    'permissions.beforeAfter': '{{before}} → {{after}}',
    'permissions.overwriteBits': 'Allow {{allow}} · Deny {{deny}}',
    'permissions.adminWarning': 'ADMINISTRATOR bypasses channel overwrites. This access cannot be restricted here.',
    'permissions.warningGeneric': 'The permission engine reported a warning for this result.',
    'permissions.concepts': 'Human access intentions',
    'permissions.concept.view': 'See this resource',
    'permissions.concept.write': 'Write / send messages',
    'permissions.concept.manage': 'Manage the resource',
    'permissions.concept.voiceJoin': 'Join voice',
    'permissions.concept.voiceSpeak': 'Speak in voice',
    'permissions.concept.voiceStream': 'Stream in voice',
    'permissions.state.allow': 'Allow',
    'permissions.state.inherit': 'Inherit',
    'permissions.state.deny': 'Deny',
    'permissions.simpleHelp': 'Choose Allow, Inherit or Deny. DID compiles these intentions into real Discord permission bits.',
    'permissions.writeDiagnostic': 'Writing depends on the Discord channel/thread context; the compiled flags are shown before creating a plan.',
    'permissions.preview': 'Preview impact',
    'permissions.propose': 'Prepare permission proposal',
    'permissions.impact': 'Impact preview',
    'permissions.current': 'Current effective permissions',
    'permissions.proposedOverwrite': 'Proposed overwrite',
    'permissions.allowFlags': 'Allow: {{flags}}',
    'permissions.denyFlags': 'Deny: {{flags}}',
    'permissions.memberImpact': 'Member impact',
    'permissions.added': 'Added effective bits: {{value}}',
    'permissions.removed': 'Removed effective bits: {{value}}',
    'permissions.roleImpactNote': 'For a role target, DID previews the exact overwrite and current role resolution. Member-by-member effects are verified by the plan/apply pipeline.',
    'permissions.selectResource': 'Select a channel or category first.',
    'permissions.selectPrincipal': 'Select a role or enter a member/bot Discord ID.',
    'permissions.noIntent': 'Choose at least one Allow or Deny intention.',
    'permissions.botCan': 'Bot can manage overwrites here',
    'permissions.botBlocked': 'Bot cannot manage overwrites here',
    'permissions.botUnknown': 'Bot overwrite capability is unknown',
    'permissions.expertRoleFlags': 'Role base flags',
    'permissions.rawBitfield': 'Raw bitfield',
  },
  fr: {
    'access.eyebrow': 'Gestion des accès',
    'access.openPlans': 'Examiner le plan validé',
    'access.planReady': 'La proposition est validée et prête à être confirmée dans Plans.',
    'access.blocked.user': 'Votre délégation dans le dashboard n’autorise pas cette modification.',
    'access.blocked.bot': 'Le bot Discord ne peut pas effectuer cette modification en sécurité.',
    'access.blocked.unknown': 'La capacité nécessaire ne peut pas être vérifiée actuellement.',
    'access.blocked.managed': 'Ce rôle est géré par Discord ; il ne peut pas être modifié ici.',
    'access.blocked.hierarchy': 'Le rôle du bot doit être strictement au-dessus du rôle ciblé.',
    'roles.subtitle': 'Gérez la hiérarchie réelle des rôles Discord sans manipuler les bitfields.',
    'roles.hierarchy': 'Hiérarchie des rôles',
    'roles.create': 'Créer un rôle',
    'roles.edit': 'Renommer le rôle',
    'roles.delete': 'Supprimer le rôle',
    'roles.moveUp': 'Monter',
    'roles.moveDown': 'Descendre',
    'roles.name': 'Nom du rôle',
    'roles.position': 'Position {{position}}',
    'roles.permissionsSummary': '{{count}} permissions connues',
    'roles.unknownBits': 'Bits de permission inconnus : {{value}}',
    'roles.noSelection': 'Sélectionnez un rôle pour examiner ses permissions Discord et les actions disponibles.',
    'roles.details': 'Détails du rôle',
    'roles.managedHelp': 'Géré par Discord ou une intégration',
    'roles.previewTitle': 'Impact avant mutation',
    'roles.createImpact': 'Crée un nouveau rôle Discord sans permission de base. Rien n’est appliqué tant que le plan n’est pas confirmé.',
    'roles.renameImpact': 'Renomme le rôle Discord sélectionné. Les membres conservent leur attribution.',
    'roles.deleteImpact': 'Supprime le rôle Discord sélectionné. Discord retire ce rôle à tous les membres.',
    'roles.reorderImpact': 'Modifie uniquement sa position dans la hiérarchie. Cela peut changer les rôles que le bot ou les modérateurs peuvent gérer.',
    'roles.prepare': 'Préparer la proposition',
    'roles.cancelEdit': 'Annuler',
    'roles.botCapability': 'Capacité du bot',
    'roles.botCan': 'Le bot peut gérer ce rôle',
    'roles.botBlocked': 'Le bot ne peut pas gérer ce rôle',
    'roles.botUnknown': 'Capacité du bot inconnue',
    'capability.badge.can': 'Possible',
    'capability.badge.cannot': 'Impossible',
    'capability.badge.unknown': 'Inconnu',
    'capability.badge.loading': 'Vérification',
    'capability.badge.error': 'Erreur',
    'capability.loading': 'Vérification de la capacité du bot…',
    'capability.errorTitle': 'Échec de la vérification',
    'capability.queryError': 'Le service de capacités est inaccessible. Il s’agit d’une erreur de requête, pas d’une capacité Discord inconnue.',
    'capability.retry': 'Réessayer',
    'capability.cause.missingManageRoles': 'Le bot ne possède pas la permission Gérer les rôles.',
    'capability.cause.botRoleNotAboveTarget': 'Le rôle le plus haut du bot n’est pas strictement au-dessus de « {{role}} ».',
    'capability.cause.targetManaged': 'Ce rôle est géré par Discord ou une intégration.',
    'capability.cause.defaultRole': 'Le rôle @everyone ne peut pas être modifié par cette action.',
    'capability.cause.botRolesIncomplete': 'Impossible de vérifier la hiérarchie : les rôles du bot ne sont pas complètement synchronisés.',
    'capability.cause.roleSnapshotMissing': 'Impossible de vérifier la hiérarchie : le rôle du bot ou le rôle cible manque dans les données Discord locales.',
    'capability.cause.botIdentityUnknown': 'L’identité du bot installé n’est pas disponible dans les données Discord locales.',
    'capability.cause.installationNotActive': 'L’installation du bot n’est pas active sur ce serveur.',
    'capability.cause.requiredIntentMissing': 'Un intent Gateway Discord nécessaire à cette vérification est indisponible.',
    'capability.cause.discordDataIncomplete': 'Le snapshot Discord en cache est incomplet ou n’est plus actuel.',
    'capability.cause.responseIncomplete': 'La réponse de capacités ne contient pas l’opération bot demandée.',
    'capability.cause.unclassified': 'Le backend a renvoyé un blocage de capacité non reconnu.',
    'capability.remediation.grantManageRoles': 'Accordez la permission Gérer les rôles au bot.',
    'capability.remediation.moveBotRoleAboveTarget': 'Placez le rôle du bot au-dessus de « {{role}} ».',
    'capability.remediation.refreshDiscordData': 'Actualisez les données Discord, puis réessayez.',
    'capability.remediation.restoreInstallation': 'Rétablissez l’installation du bot sur ce serveur.',
    'capability.remediation.restoreRequiredIntent': 'Rétablissez l’intent Gateway requis, puis actualisez les données Discord.',
    'permissions.subtitle': 'Répondez à des questions d’accès humaines en mode Simple, ou inspectez la résolution Discord exacte en mode Expert.',
    'permissions.mode.simple': 'Mode simple',
    'permissions.mode.expert': 'Mode expert',
    'permissions.resource': 'Ressource Discord',
    'permissions.principalType': 'Pour qui configurez-vous l’accès ?',
    'permissions.principal.role': 'Un rôle',
    'permissions.principal.member': 'Un membre ou un bot',
    'permissions.principal.newcomer': 'Un nouvel arrivant (diagnostic uniquement)',
    'permissions.role': 'Rôle Discord',
    'permissions.memberId': 'ID Discord du membre / bot',
    'permissions.requestedPermission': 'Permission à expliquer',
    'permissions.diagnose': 'Pourquoi cet accès ?',
    'permissions.diagnosis': 'Diagnostic des permissions effectives',
    'permissions.effectiveBits': 'Bits effectifs : {{value}}',
    'permissions.outcome': 'Résultat : {{value}}',
    'permissions.coverage': 'Couverture : {{value}}',
    'permissions.freshness': 'Fraîcheur : {{value}}',
    'permissions.trace': 'Trace de résolution Discord',
    'permissions.traceStep': 'Étape {{index}}',
    'permissions.source': '{{type}} {{id}}',
    'permissions.beforeAfter': '{{before}} → {{after}}',
    'permissions.overwriteBits': 'Autoriser {{allow}} · Refuser {{deny}}',
    'permissions.adminWarning': 'ADMINISTRATOR contourne les overwrites de salon. Cet accès ne peut pas être limité ici.',
    'permissions.warningGeneric': 'Le moteur de permissions a signalé un avertissement pour ce résultat.',
    'permissions.concepts': 'Intentions d’accès',
    'permissions.concept.view': 'Voir cette ressource',
    'permissions.concept.write': 'Écrire / envoyer des messages',
    'permissions.concept.manage': 'Gérer la ressource',
    'permissions.concept.voiceJoin': 'Rejoindre le vocal',
    'permissions.concept.voiceSpeak': 'Parler en vocal',
    'permissions.concept.voiceStream': 'Diffuser en vocal',
    'permissions.state.allow': 'Autoriser',
    'permissions.state.inherit': 'Hériter',
    'permissions.state.deny': 'Refuser',
    'permissions.simpleHelp': 'Choisissez Autoriser, Hériter ou Refuser. DID compile ces intentions en vraies permissions Discord.',
    'permissions.writeDiagnostic': 'L’écriture dépend du contexte salon/thread Discord ; les flags compilés sont affichés avant la création du plan.',
    'permissions.preview': 'Prévisualiser l’impact',
    'permissions.propose': 'Préparer la proposition de permissions',
    'permissions.impact': 'Prévisualisation de l’impact',
    'permissions.current': 'Permissions effectives actuelles',
    'permissions.proposedOverwrite': 'Overwrite proposé',
    'permissions.allowFlags': 'Autoriser : {{flags}}',
    'permissions.denyFlags': 'Refuser : {{flags}}',
    'permissions.memberImpact': 'Impact sur le membre',
    'permissions.added': 'Bits effectifs ajoutés : {{value}}',
    'permissions.removed': 'Bits effectifs retirés : {{value}}',
    'permissions.roleImpactNote': 'Pour un rôle, DID prévisualise exactement l’overwrite et la résolution actuelle du rôle. Les effets membre par membre sont vérifiés par le pipeline plan/apply.',
    'permissions.selectResource': 'Sélectionnez d’abord un salon ou une catégorie.',
    'permissions.selectPrincipal': 'Sélectionnez un rôle ou saisissez l’ID Discord d’un membre/bot.',
    'permissions.noIntent': 'Choisissez au moins une intention Autoriser ou Refuser.',
    'permissions.botCan': 'Le bot peut gérer les overwrites ici',
    'permissions.botBlocked': 'Le bot ne peut pas gérer les overwrites ici',
    'permissions.botUnknown': 'Capacité du bot sur les overwrites inconnue',
    'permissions.expertRoleFlags': 'Flags de base du rôle',
    'permissions.rawBitfield': 'Bitfield brut',
  },
  de: {
    'access.eyebrow': 'Zugriffsverwaltung', 'access.openPlans': 'Validierten Plan prüfen', 'access.planReady': 'Der Vorschlag ist validiert und kann unter Pläne bestätigt werden.',
    'capability.badge.can': 'Möglich', 'capability.badge.cannot': 'Nicht möglich', 'capability.badge.unknown': 'Unbekannt', 'capability.badge.loading': 'Prüfung', 'capability.badge.error': 'Fehler',
    'capability.loading': 'Die Bot-Fähigkeit wird geprüft…', 'capability.errorTitle': 'Fähigkeitsprüfung fehlgeschlagen', 'capability.queryError': 'Der Fähigkeitsdienst ist nicht erreichbar. Dies ist ein Anfragefehler und keine unbekannte Discord-Fähigkeit.', 'capability.retry': 'Erneut versuchen',
    'capability.cause.missingManageRoles': 'Dem Bot fehlt die Berechtigung Rollen verwalten.', 'capability.cause.botRoleNotAboveTarget': 'Die höchste Bot-Rolle liegt nicht strikt über „{{role}}“.', 'capability.cause.targetManaged': 'Diese Rolle wird von Discord oder einer Integration verwaltet.', 'capability.cause.defaultRole': 'Die @everyone-Rolle kann mit dieser Aktion nicht geändert werden.', 'capability.cause.botRolesIncomplete': 'Die Hierarchie kann nicht geprüft werden, weil die Bot-Rollen nicht vollständig synchronisiert sind.', 'capability.cause.roleSnapshotMissing': 'Die Hierarchie kann nicht geprüft werden, weil die Bot- oder Zielrolle in den lokalen Discord-Daten fehlt.', 'capability.cause.botIdentityUnknown': 'Die Identität des installierten Bots ist in den lokalen Discord-Daten nicht verfügbar.', 'capability.cause.installationNotActive': 'Die Bot-Installation ist auf diesem Server nicht aktiv.', 'capability.cause.requiredIntentMissing': 'Ein für diese Prüfung erforderlicher Discord-Gateway-Intent ist nicht verfügbar.', 'capability.cause.discordDataIncomplete': 'Der zwischengespeicherte Discord-Snapshot ist unvollständig oder nicht mehr aktuell.', 'capability.cause.responseIncomplete': 'Die Fähigkeitsantwort enthält die angeforderte Bot-Operation nicht.', 'capability.cause.unclassified': 'Das Backend hat einen unbekannten Fähigkeitsblocker gemeldet.',
    'capability.remediation.grantManageRoles': 'Erteilen Sie dem Bot die Berechtigung Rollen verwalten.', 'capability.remediation.moveBotRoleAboveTarget': 'Verschieben Sie die Bot-Rolle über „{{role}}“.', 'capability.remediation.refreshDiscordData': 'Aktualisieren Sie die Discord-Daten und versuchen Sie es erneut.', 'capability.remediation.restoreInstallation': 'Stellen Sie die Bot-Installation auf diesem Server wieder her.', 'capability.remediation.restoreRequiredIntent': 'Stellen Sie den erforderlichen Gateway-Intent wieder her und aktualisieren Sie die Discord-Daten.',
    'access.blocked.user': 'Ihre Dashboard-Delegation erlaubt diese Änderung nicht.', 'access.blocked.bot': 'Der Discord-Bot kann diese Änderung nicht sicher ausführen.', 'access.blocked.unknown': 'Die erforderliche Fähigkeit kann derzeit nicht geprüft werden.', 'access.blocked.managed': 'Diese Rolle wird von Discord verwaltet und kann hier nicht bearbeitet werden.', 'access.blocked.hierarchy': 'Die Bot-Rolle muss strikt über der Zielrolle liegen.',
    'roles.subtitle': 'Verwalten Sie die echte Discord-Rollenhierarchie ohne rohe Bitfelder.', 'roles.hierarchy': 'Rollenhierarchie', 'roles.create': 'Rolle erstellen', 'roles.edit': 'Rolle umbenennen', 'roles.delete': 'Rolle löschen', 'roles.moveUp': 'Nach oben', 'roles.moveDown': 'Nach unten', 'roles.name': 'Rollenname', 'roles.position': 'Position {{position}}', 'roles.permissionsSummary': '{{count}} bekannte Berechtigungen', 'roles.unknownBits': 'Unbekannte Berechtigungsbits: {{value}}', 'roles.noSelection': 'Wählen Sie eine Rolle, um Discord-Berechtigungen und Aktionen zu prüfen.', 'roles.details': 'Rollendetails', 'roles.managedHelp': 'Von Discord oder einer Integration verwaltet', 'roles.previewTitle': 'Auswirkung vor Änderung', 'roles.createImpact': 'Erstellt eine neue Discord-Rolle ohne Basisberechtigungen. Vor Bestätigung des Plans wird nichts angewendet.', 'roles.renameImpact': 'Benennt die ausgewählte Discord-Rolle um. Zuweisungen bleiben erhalten.', 'roles.deleteImpact': 'Löscht die Rolle; Discord entfernt sie von allen Mitgliedern.', 'roles.reorderImpact': 'Ändert nur die Position in der Hierarchie und kann beeinflussen, welche Rollen verwaltet werden können.', 'roles.prepare': 'Vorschlag vorbereiten', 'roles.cancelEdit': 'Abbrechen', 'roles.botCapability': 'Bot-Fähigkeit', 'roles.botCan': 'Bot kann diese Rolle verwalten', 'roles.botBlocked': 'Bot kann diese Rolle nicht verwalten', 'roles.botUnknown': 'Bot-Fähigkeit unbekannt',
    'permissions.subtitle': 'Nutzen Sie menschliche Zugriffsfragen im einfachen Modus oder die genaue Discord-Auflösung im Expertenmodus.', 'permissions.mode.simple': 'Einfacher Modus', 'permissions.mode.expert': 'Expertenmodus', 'permissions.resource': 'Discord-Ressource', 'permissions.principalType': 'Für wen konfigurieren Sie?', 'permissions.principal.role': 'Eine Rolle', 'permissions.principal.member': 'Ein Mitglied oder Bot', 'permissions.principal.newcomer': 'Neues Mitglied (nur Diagnose)', 'permissions.role': 'Discord-Rolle', 'permissions.memberId': 'Discord-ID Mitglied / Bot', 'permissions.requestedPermission': 'Zu erklärende Berechtigung', 'permissions.diagnose': 'Warum dieser Zugriff?', 'permissions.diagnosis': 'Diagnose effektiver Berechtigungen', 'permissions.effectiveBits': 'Effektive Bits: {{value}}', 'permissions.outcome': 'Ergebnis: {{value}}', 'permissions.coverage': 'Abdeckung: {{value}}', 'permissions.freshness': 'Aktualität: {{value}}', 'permissions.trace': 'Discord-Auflösungsspur', 'permissions.traceStep': 'Schritt {{index}}', 'permissions.source': '{{type}} {{id}}', 'permissions.beforeAfter': '{{before}} → {{after}}', 'permissions.overwriteBits': 'Erlauben {{allow}} · Verweigern {{deny}}', 'permissions.adminWarning': 'ADMINISTRATOR umgeht Kanal-Overwrites. Dieser Zugriff kann hier nicht eingeschränkt werden.', 'permissions.warningGeneric': 'Die Berechtigungsengine meldet eine Warnung.', 'permissions.concepts': 'Zugriffsabsichten', 'permissions.concept.view': 'Ressource sehen', 'permissions.concept.write': 'Nachrichten schreiben/senden', 'permissions.concept.manage': 'Ressource verwalten', 'permissions.concept.voiceJoin': 'Sprachkanal beitreten', 'permissions.concept.voiceSpeak': 'Im Sprachkanal sprechen', 'permissions.concept.voiceStream': 'Im Sprachkanal streamen', 'permissions.state.allow': 'Erlauben', 'permissions.state.inherit': 'Erben', 'permissions.state.deny': 'Verweigern', 'permissions.simpleHelp': 'Wählen Sie Erlauben, Erben oder Verweigern. DID kompiliert dies in echte Discord-Bits.', 'permissions.writeDiagnostic': 'Schreiben hängt vom Discord-Kanal-/Thread-Kontext ab; die kompilierten Flags werden vor dem Plan angezeigt.', 'permissions.preview': 'Auswirkung prüfen', 'permissions.propose': 'Berechtigungsvorschlag vorbereiten', 'permissions.impact': 'Auswirkungsvorschau', 'permissions.current': 'Aktuelle effektive Berechtigungen', 'permissions.proposedOverwrite': 'Vorgeschlagenes Overwrite', 'permissions.allowFlags': 'Erlauben: {{flags}}', 'permissions.denyFlags': 'Verweigern: {{flags}}', 'permissions.memberImpact': 'Auswirkung auf Mitglied', 'permissions.added': 'Hinzugefügte effektive Bits: {{value}}', 'permissions.removed': 'Entfernte effektive Bits: {{value}}', 'permissions.roleImpactNote': 'Bei einer Rolle zeigt DID das genaue Overwrite und die aktuelle Rollenauflösung. Mitgliedseffekte werden im Plan/Apply-Pipeline verifiziert.', 'permissions.selectResource': 'Wählen Sie zuerst einen Kanal oder eine Kategorie.', 'permissions.selectPrincipal': 'Wählen Sie eine Rolle oder geben Sie eine Mitglied/Bot-ID ein.', 'permissions.noIntent': 'Wählen Sie mindestens eine Erlauben- oder Verweigern-Absicht.', 'permissions.botCan': 'Bot kann Overwrites hier verwalten', 'permissions.botBlocked': 'Bot kann Overwrites hier nicht verwalten', 'permissions.botUnknown': 'Bot-Overwrite-Fähigkeit unbekannt', 'permissions.expertRoleFlags': 'Basisflags der Rolle', 'permissions.rawBitfield': 'Rohes Bitfeld',
  },
  es: {
    'access.eyebrow': 'Gestión de accesos', 'access.openPlans': 'Revisar plan validado', 'access.planReady': 'La propuesta está validada y lista para confirmarse en Planes.',
    'capability.badge.can': 'Posible', 'capability.badge.cannot': 'No posible', 'capability.badge.unknown': 'Desconocido', 'capability.badge.loading': 'Comprobando', 'capability.badge.error': 'Error',
    'capability.loading': 'Comprobando la capacidad del bot…', 'capability.errorTitle': 'Falló la comprobación de capacidad', 'capability.queryError': 'No se puede acceder al servicio de capacidades. Es un error de solicitud, no una capacidad de Discord desconocida.', 'capability.retry': 'Reintentar',
    'capability.cause.missingManageRoles': 'El bot no tiene el permiso Gestionar roles.', 'capability.cause.botRoleNotAboveTarget': 'El rol más alto del bot no está estrictamente por encima de «{{role}}».', 'capability.cause.targetManaged': 'Discord o una integración gestiona este rol.', 'capability.cause.defaultRole': 'El rol @everyone no puede modificarse mediante esta acción.', 'capability.cause.botRolesIncomplete': 'No se puede comprobar la jerarquía porque los roles del bot no están completamente sincronizados.', 'capability.cause.roleSnapshotMissing': 'No se puede comprobar la jerarquía porque falta el rol del bot o el rol objetivo en los datos locales de Discord.', 'capability.cause.botIdentityUnknown': 'La identidad del bot instalado no está disponible en los datos locales de Discord.', 'capability.cause.installationNotActive': 'La instalación del bot no está activa en este servidor.', 'capability.cause.requiredIntentMissing': 'No está disponible un intent de Discord Gateway necesario para esta comprobación.', 'capability.cause.discordDataIncomplete': 'El snapshot de Discord en caché está incompleto o desactualizado.', 'capability.cause.responseIncomplete': 'La respuesta de capacidades no contiene la operación del bot solicitada.', 'capability.cause.unclassified': 'El backend devolvió un bloqueo de capacidad no reconocido.',
    'capability.remediation.grantManageRoles': 'Conceda al bot el permiso Gestionar roles.', 'capability.remediation.moveBotRoleAboveTarget': 'Mueva el rol del bot por encima de «{{role}}».', 'capability.remediation.refreshDiscordData': 'Actualice los datos de Discord y vuelva a intentarlo.', 'capability.remediation.restoreInstallation': 'Restaure la instalación del bot en este servidor.', 'capability.remediation.restoreRequiredIntent': 'Restaure el intent de Gateway necesario y actualice los datos de Discord.',
    'access.blocked.user': 'Su delegación del panel no permite este cambio.', 'access.blocked.bot': 'El bot de Discord no puede realizar este cambio de forma segura.', 'access.blocked.unknown': 'La capacidad necesaria no puede verificarse ahora.', 'access.blocked.managed': 'Discord gestiona este rol; no puede editarse aquí.', 'access.blocked.hierarchy': 'El rol del bot debe estar estrictamente por encima del rol objetivo.',
    'roles.subtitle': 'Gestione la jerarquía real de roles de Discord sin manipular bitfields.', 'roles.hierarchy': 'Jerarquía de roles', 'roles.create': 'Crear rol', 'roles.edit': 'Renombrar rol', 'roles.delete': 'Eliminar rol', 'roles.moveUp': 'Subir', 'roles.moveDown': 'Bajar', 'roles.name': 'Nombre del rol', 'roles.position': 'Posición {{position}}', 'roles.permissionsSummary': '{{count}} permisos conocidos', 'roles.unknownBits': 'Bits de permisos desconocidos: {{value}}', 'roles.noSelection': 'Seleccione un rol para inspeccionar sus permisos y acciones.', 'roles.details': 'Detalles del rol', 'roles.managedHelp': 'Gestionado por Discord o una integración', 'roles.previewTitle': 'Impacto antes de la mutación', 'roles.createImpact': 'Crea un nuevo rol de Discord sin permisos base. No se aplica nada hasta confirmar el plan.', 'roles.renameImpact': 'Renombra el rol seleccionado. Las asignaciones de miembros se conservan.', 'roles.deleteImpact': 'Elimina el rol; Discord lo retira de todos los miembros.', 'roles.reorderImpact': 'Cambia solo su posición jerárquica y puede afectar qué roles se pueden gestionar.', 'roles.prepare': 'Preparar propuesta', 'roles.cancelEdit': 'Cancelar', 'roles.botCapability': 'Capacidad del bot', 'roles.botCan': 'El bot puede gestionar este rol', 'roles.botBlocked': 'El bot no puede gestionar este rol', 'roles.botUnknown': 'Capacidad del bot desconocida',
    'permissions.subtitle': 'Use preguntas de acceso humanas en modo Simple o inspeccione la resolución exacta de Discord en modo Experto.', 'permissions.mode.simple': 'Modo simple', 'permissions.mode.expert': 'Modo experto', 'permissions.resource': 'Recurso de Discord', 'permissions.principalType': '¿Para quién configura el acceso?', 'permissions.principal.role': 'Un rol', 'permissions.principal.member': 'Un miembro o bot', 'permissions.principal.newcomer': 'Un recién llegado (solo diagnóstico)', 'permissions.role': 'Rol de Discord', 'permissions.memberId': 'ID de Discord del miembro / bot', 'permissions.requestedPermission': 'Permiso que explicar', 'permissions.diagnose': '¿Por qué este acceso?', 'permissions.diagnosis': 'Diagnóstico de permisos efectivos', 'permissions.effectiveBits': 'Bits efectivos: {{value}}', 'permissions.outcome': 'Resultado: {{value}}', 'permissions.coverage': 'Cobertura: {{value}}', 'permissions.freshness': 'Actualidad: {{value}}', 'permissions.trace': 'Traza de resolución de Discord', 'permissions.traceStep': 'Paso {{index}}', 'permissions.source': '{{type}} {{id}}', 'permissions.beforeAfter': '{{before}} → {{after}}', 'permissions.overwriteBits': 'Permitir {{allow}} · Denegar {{deny}}', 'permissions.adminWarning': 'ADMINISTRATOR omite los overwrites del canal. Este acceso no puede limitarse aquí.', 'permissions.warningGeneric': 'El motor de permisos ha indicado una advertencia.', 'permissions.concepts': 'Intenciones de acceso', 'permissions.concept.view': 'Ver este recurso', 'permissions.concept.write': 'Escribir / enviar mensajes', 'permissions.concept.manage': 'Gestionar el recurso', 'permissions.concept.voiceJoin': 'Entrar al canal de voz', 'permissions.concept.voiceSpeak': 'Hablar por voz', 'permissions.concept.voiceStream': 'Transmitir por voz', 'permissions.state.allow': 'Permitir', 'permissions.state.inherit': 'Heredar', 'permissions.state.deny': 'Denegar', 'permissions.simpleHelp': 'Elija Permitir, Heredar o Denegar. DID compila estas intenciones a permisos reales de Discord.', 'permissions.writeDiagnostic': 'La escritura depende del contexto de canal/hilo; los flags compilados se muestran antes de crear un plan.', 'permissions.preview': 'Previsualizar impacto', 'permissions.propose': 'Preparar propuesta de permisos', 'permissions.impact': 'Vista previa del impacto', 'permissions.current': 'Permisos efectivos actuales', 'permissions.proposedOverwrite': 'Overwrite propuesto', 'permissions.allowFlags': 'Permitir: {{flags}}', 'permissions.denyFlags': 'Denegar: {{flags}}', 'permissions.memberImpact': 'Impacto sobre el miembro', 'permissions.added': 'Bits efectivos añadidos: {{value}}', 'permissions.removed': 'Bits efectivos eliminados: {{value}}', 'permissions.roleImpactNote': 'Para un rol, DID muestra el overwrite exacto y la resolución actual. Los efectos por miembro se verifican en el pipeline plan/apply.', 'permissions.selectResource': 'Seleccione primero un canal o categoría.', 'permissions.selectPrincipal': 'Seleccione un rol o introduzca el ID de un miembro/bot.', 'permissions.noIntent': 'Elija al menos una intención Permitir o Denegar.', 'permissions.botCan': 'El bot puede gestionar overwrites aquí', 'permissions.botBlocked': 'El bot no puede gestionar overwrites aquí', 'permissions.botUnknown': 'Capacidad de overwrites del bot desconocida', 'permissions.expertRoleFlags': 'Flags base del rol', 'permissions.rawBitfield': 'Bitfield bruto',
  },
} as const
