const en = {
  'nav.wizards': 'Assistants',
  'wizard.progress': 'Assistant progress',
  'wizard.back': 'Back',
  'wizard.next': 'Next',
  'wizard.cancel': 'Leave',
  'wizard.cancelDiscard': 'Leave without saving',
  'wizard.cancelKeepDraft': 'Leave (draft kept)',

  'wizards.title': 'Assistants',
  'wizards.subtitle': 'Guided helpers that turn a question into an editable proposal — never a direct Discord change.',
  'wizards.catalog.available': 'Available',
  'wizards.catalog.unavailable': 'Not available yet',
  'wizards.catalog.scope': 'Scope',
  'wizards.catalog.produces': 'Produces',
  'wizards.catalog.prerequisites': 'Prerequisites',
  'wizards.catalog.complexity': 'Complexity',
  'wizards.catalog.start': 'Start',
  'wizards.catalog.accessSpace.title': 'Configure access to a space',
  'wizards.catalog.accessSpace.goal': 'Decide who can see, write to, or join a category, channel or the whole server.',
  'wizards.catalog.accessSpace.scope': 'One category, channel, logical group or the server, plus the roles that should see or write to it.',
  'wizards.catalog.accessSpace.produces': 'A DRAFT access Policy and, if needed, a validated role-creation plan.',
  'wizards.catalog.accessSpace.prerequisites': 'Being able to read policies for this server.',
  'wizards.catalog.accessSpace.complexity': 'About 5 minutes, 7 guided steps.',
  'wizards.catalog.templates.title': 'Build a template',
  'wizards.catalog.templates.goal': 'Turn an existing structure into a reusable template.',
  'wizards.catalog.templates.scope': 'A category or a set of channels.',
  'wizards.catalog.templates.produces': 'A portable template artifact.',
  'wizards.catalog.templates.prerequisites': 'None yet.',
  'wizards.catalog.templates.complexity': 'Not estimated yet.',
  'wizards.catalog.templates.unavailable': 'Planned for the Templates phase — this assistant is not built yet.',

  'wizard.roles.existing': 'Existing roles',
  'wizard.roles.managed': 'Managed',
  'wizard.roles.managedHelp': 'Managed by an integration — cannot be used as an audience.',
  'wizard.roles.empty': 'This server has no selectable role yet.',
  'wizard.roles.proposed': 'Roles to create',
  'wizard.roles.willBeCreated': 'Will be created',
  'wizard.roles.removeProposed': 'Remove',
  'wizard.roles.create': '+ Create a role',
  'wizard.roles.createName': 'Role name',
  'wizard.roles.createHelp': 'This only adds a proposal here. Nothing is created on Discord until you prepare its own plan.',
  'wizard.roles.confirmCreate': 'Add this proposal',
  'wizard.roles.suggested': 'Suggested role: {{name}} — will be created',
  'wizard.roles.useSuggestion': 'Use this suggestion',

  'wizard.accessSpace.title': 'Configure access to a space',
  'wizard.accessSpace.subtitle': 'Answer a few questions, review an editable proposal, then prepare a Policy DRAFT and its Plan. Nothing is ever applied to Discord from here.',
  'wizard.accessSpace.step.target': '1 · Target',
  'wizard.accessSpace.step.intent': '2 · Intent',
  'wizard.accessSpace.step.roles': '3 · Roles',
  'wizard.accessSpace.step.conflicts': '4 · Conflicts',
  'wizard.accessSpace.step.adjust': '5 · Adjust',
  'wizard.accessSpace.step.preview': '6 · Preview',
  'wizard.accessSpace.step.plan': '7 · Plan',
  'wizard.accessSpace.target.help': 'Choose the existing category, channel, logical group or the whole server this rule should apply to.',
  'wizard.accessSpace.target.placeholder': 'Choose a target…',
  'wizard.accessSpace.intent.help': 'Only intents compatible with the chosen target are offered.',
  'wizard.accessSpace.roles.help': 'Select every existing role that should be part of this audience.',
  'wizard.accessSpace.roles.suggestedName': 'Confirmed members',
  'wizard.accessSpace.roles.blockedByProposal': 'Cannot continue: the proposed role does not exist yet. Add at least one existing role, or prepare its own role plan first, then come back and select it.',
  'wizard.accessSpace.conflicts.help': 'These existing policies already target the same resource and may interact with your proposal.',
  'wizard.accessSpace.conflicts.empty': 'No other policy currently targets this resource.',
  'wizard.accessSpace.conflicts.disclaimer': 'This list is informative only. The exact conflicts and winning rule appear in the Preview / Impact step, computed by the same canonical resolver.',
  'wizard.accessSpace.preview.action': 'Create the draft and preview',
  'wizard.accessSpace.preview.refresh': 'Refresh preview',
  'wizard.accessSpace.preview.draftCreated': 'A Policy DRAFT was created. Discord was not changed.',
  'wizard.accessSpace.plan.previewFirst': 'Preview the draft first.',
  'wizard.accessSpace.plan.roleTitle': 'Role creation plan',
  'wizard.accessSpace.plan.roleHelp': 'The proposed role does not exist yet. Prepare a validated plan for it; it stays unapplied until you confirm it later.',
  'wizard.accessSpace.plan.prepareRole': 'Prepare the role plan',
  'wizard.accessSpace.plan.roleCreated': 'Role plan validated. No Discord role exists yet.',
  'wizard.accessSpace.plan.policyTitle': 'Policy plan',
  'wizard.accessSpace.plan.policyHelp': 'Compiles the Policy DRAFT into the canonical Plan. It still requires Preflight, confirmation and a separate Apply before anything changes on Discord.',
} as const

const fr: Record<keyof typeof en, string> = {
  'nav.wizards': 'Assistants',
  'wizard.progress': 'Progression de l’assistant',
  'wizard.back': 'Précédent',
  'wizard.next': 'Suivant',
  'wizard.cancel': 'Quitter',
  'wizard.cancelDiscard': 'Quitter sans enregistrer',
  'wizard.cancelKeepDraft': 'Quitter (brouillon conservé)',

  'wizards.title': 'Assistants',
  'wizards.subtitle': 'Des aides guidées qui transforment une question en proposition éditable — jamais en changement Discord direct.',
  'wizards.catalog.available': 'Disponible',
  'wizards.catalog.unavailable': 'Pas encore disponible',
  'wizards.catalog.scope': 'Portée',
  'wizards.catalog.produces': 'Produit',
  'wizards.catalog.prerequisites': 'Prérequis',
  'wizards.catalog.complexity': 'Complexité',
  'wizards.catalog.start': 'Démarrer',
  'wizards.catalog.accessSpace.title': 'Configurer l’accès à un espace',
  'wizards.catalog.accessSpace.goal': 'Décider qui peut voir, écrire ou rejoindre une catégorie, un salon ou tout le serveur.',
  'wizards.catalog.accessSpace.scope': 'Une catégorie, un salon, un groupe logique ou le serveur, ainsi que les rôles qui doivent le voir ou y écrire.',
  'wizards.catalog.accessSpace.produces': 'Une Policy d’accès en DRAFT et, si besoin, un plan de création de rôle validé.',
  'wizards.catalog.accessSpace.prerequisites': 'Pouvoir lire les politiques de ce serveur.',
  'wizards.catalog.accessSpace.complexity': 'Environ 5 minutes, 7 étapes guidées.',
  'wizards.catalog.templates.title': 'Construire un gabarit',
  'wizards.catalog.templates.goal': 'Transformer une structure existante en gabarit réutilisable.',
  'wizards.catalog.templates.scope': 'Une catégorie ou un ensemble de salons.',
  'wizards.catalog.templates.produces': 'Un artefact de gabarit portable.',
  'wizards.catalog.templates.prerequisites': 'Aucun pour l’instant.',
  'wizards.catalog.templates.complexity': 'Pas encore estimée.',
  'wizards.catalog.templates.unavailable': 'Prévu pour la phase Gabarits — cet assistant n’est pas encore construit.',

  'wizard.roles.existing': 'Rôles existants',
  'wizard.roles.managed': 'Géré',
  'wizard.roles.managedHelp': 'Géré par une intégration — ne peut pas être utilisé comme audience.',
  'wizard.roles.empty': 'Ce serveur n’a encore aucun rôle sélectionnable.',
  'wizard.roles.proposed': 'Rôles à créer',
  'wizard.roles.willBeCreated': 'Sera créé',
  'wizard.roles.removeProposed': 'Retirer',
  'wizard.roles.create': '+ Créer un rôle',
  'wizard.roles.createName': 'Nom du rôle',
  'wizard.roles.createHelp': 'Ceci ajoute uniquement une proposition ici. Rien n’est créé sur Discord tant que vous n’avez pas préparé son propre plan.',
  'wizard.roles.confirmCreate': 'Ajouter cette proposition',
  'wizard.roles.suggested': 'Rôle suggéré : {{name}} — sera créé',
  'wizard.roles.useSuggestion': 'Utiliser cette suggestion',

  'wizard.accessSpace.title': 'Configurer l’accès à un espace',
  'wizard.accessSpace.subtitle': 'Répondez à quelques questions, vérifiez une proposition éditable, puis préparez une Policy DRAFT et son Plan. Rien n’est jamais appliqué à Discord depuis cet écran.',
  'wizard.accessSpace.step.target': '1 · Cible',
  'wizard.accessSpace.step.intent': '2 · Intention',
  'wizard.accessSpace.step.roles': '3 · Rôles',
  'wizard.accessSpace.step.conflicts': '4 · Conflits',
  'wizard.accessSpace.step.adjust': '5 · Ajuster',
  'wizard.accessSpace.step.preview': '6 · Preview',
  'wizard.accessSpace.step.plan': '7 · Plan',
  'wizard.accessSpace.target.help': 'Choisissez la catégorie, le salon, le groupe logique ou le serveur existant auquel cette règle doit s’appliquer.',
  'wizard.accessSpace.target.placeholder': 'Choisir une cible…',
  'wizard.accessSpace.intent.help': 'Seules les intentions compatibles avec la cible choisie sont proposées.',
  'wizard.accessSpace.roles.help': 'Sélectionnez chaque rôle existant qui doit faire partie de cette audience.',
  'wizard.accessSpace.roles.suggestedName': 'Membres confirmés',
  'wizard.accessSpace.roles.blockedByProposal': 'Impossible de continuer : le rôle proposé n’existe pas encore. Ajoutez au moins un rôle existant, ou préparez d’abord son propre plan de rôle puis revenez le sélectionner.',
  'wizard.accessSpace.conflicts.help': 'Ces politiques existantes ciblent déjà la même ressource et peuvent interagir avec votre proposition.',
  'wizard.accessSpace.conflicts.empty': 'Aucune autre politique ne cible actuellement cette ressource.',
  'wizard.accessSpace.conflicts.disclaimer': 'Cette liste est uniquement informative. Les conflits exacts et la règle gagnante apparaissent à l’étape Preview / Impact, calculés par le même resolver canonique.',
  'wizard.accessSpace.preview.action': 'Créer le brouillon et prévisualiser',
  'wizard.accessSpace.preview.refresh': 'Actualiser la preview',
  'wizard.accessSpace.preview.draftCreated': 'Une Policy DRAFT a été créée. Discord n’a pas été modifié.',
  'wizard.accessSpace.plan.previewFirst': 'Prévisualisez d’abord le brouillon.',
  'wizard.accessSpace.plan.roleTitle': 'Plan de création du rôle',
  'wizard.accessSpace.plan.roleHelp': 'Le rôle proposé n’existe pas encore. Préparez un plan validé pour celui-ci ; il reste non appliqué tant que vous ne le confirmez pas plus tard.',
  'wizard.accessSpace.plan.prepareRole': 'Préparer le plan de rôle',
  'wizard.accessSpace.plan.roleCreated': 'Plan de rôle validé. Aucun rôle Discord n’existe encore.',
  'wizard.accessSpace.plan.policyTitle': 'Plan de la Policy',
  'wizard.accessSpace.plan.policyHelp': 'Compile la Policy DRAFT dans le Plan canonique. Un Preflight, une confirmation puis une Application séparée restent nécessaires avant tout changement sur Discord.',
}

const de: Record<keyof typeof en, string> = {
  'nav.wizards': 'Assistenten',
  'wizard.progress': 'Fortschritt des Assistenten',
  'wizard.back': 'Zurück',
  'wizard.next': 'Weiter',
  'wizard.cancel': 'Verlassen',
  'wizard.cancelDiscard': 'Verlassen ohne zu speichern',
  'wizard.cancelKeepDraft': 'Verlassen (Entwurf bleibt erhalten)',

  'wizards.title': 'Assistenten',
  'wizards.subtitle': 'Geführte Hilfen, die eine Frage in einen bearbeitbaren Vorschlag verwandeln — niemals in eine direkte Discord-Änderung.',
  'wizards.catalog.available': 'Verfügbar',
  'wizards.catalog.unavailable': 'Noch nicht verfügbar',
  'wizards.catalog.scope': 'Umfang',
  'wizards.catalog.produces': 'Ergebnis',
  'wizards.catalog.prerequisites': 'Voraussetzungen',
  'wizards.catalog.complexity': 'Komplexität',
  'wizards.catalog.start': 'Starten',
  'wizards.catalog.accessSpace.title': 'Zugriff auf einen Bereich konfigurieren',
  'wizards.catalog.accessSpace.goal': 'Festlegen, wer eine Kategorie, einen Kanal oder den gesamten Server sehen, beschreiben oder betreten darf.',
  'wizards.catalog.accessSpace.scope': 'Eine Kategorie, ein Kanal, eine logische Gruppe oder der Server sowie die Rollen, die ihn sehen oder darin schreiben sollen.',
  'wizards.catalog.accessSpace.produces': 'Eine Zugriffs-Policy im Entwurf und, falls nötig, einen validierten Rollen-Erstellungsplan.',
  'wizards.catalog.accessSpace.prerequisites': 'Richtlinien dieses Servers lesen können.',
  'wizards.catalog.accessSpace.complexity': 'Etwa 5 Minuten, 7 geführte Schritte.',
  'wizards.catalog.templates.title': 'Vorlage erstellen',
  'wizards.catalog.templates.goal': 'Eine bestehende Struktur in eine wiederverwendbare Vorlage verwandeln.',
  'wizards.catalog.templates.scope': 'Eine Kategorie oder eine Reihe von Kanälen.',
  'wizards.catalog.templates.produces': 'Ein portables Vorlagenartefakt.',
  'wizards.catalog.templates.prerequisites': 'Noch keine.',
  'wizards.catalog.templates.complexity': 'Noch nicht geschätzt.',
  'wizards.catalog.templates.unavailable': 'Für die Vorlagen-Phase geplant — dieser Assistent ist noch nicht gebaut.',

  'wizard.roles.existing': 'Vorhandene Rollen',
  'wizard.roles.managed': 'Verwaltet',
  'wizard.roles.managedHelp': 'Von einer Integration verwaltet — kann nicht als Zielgruppe verwendet werden.',
  'wizard.roles.empty': 'Dieser Server hat noch keine auswählbare Rolle.',
  'wizard.roles.proposed': 'Zu erstellende Rollen',
  'wizard.roles.willBeCreated': 'Wird erstellt',
  'wizard.roles.removeProposed': 'Entfernen',
  'wizard.roles.create': '+ Rolle erstellen',
  'wizard.roles.createName': 'Rollenname',
  'wizard.roles.createHelp': 'Dies fügt hier nur einen Vorschlag hinzu. Auf Discord wird nichts erstellt, bis Sie dafür einen eigenen Plan vorbereitet haben.',
  'wizard.roles.confirmCreate': 'Diesen Vorschlag hinzufügen',
  'wizard.roles.suggested': 'Vorgeschlagene Rolle: {{name}} — wird erstellt',
  'wizard.roles.useSuggestion': 'Diesen Vorschlag verwenden',

  'wizard.accessSpace.title': 'Zugriff auf einen Bereich konfigurieren',
  'wizard.accessSpace.subtitle': 'Beantworten Sie ein paar Fragen, prüfen Sie einen bearbeitbaren Vorschlag und bereiten Sie dann einen Policy-Entwurf und seinen Plan vor. Von hier aus wird nie etwas auf Discord angewendet.',
  'wizard.accessSpace.step.target': '1 · Ziel',
  'wizard.accessSpace.step.intent': '2 · Absicht',
  'wizard.accessSpace.step.roles': '3 · Rollen',
  'wizard.accessSpace.step.conflicts': '4 · Konflikte',
  'wizard.accessSpace.step.adjust': '5 · Anpassen',
  'wizard.accessSpace.step.preview': '6 · Vorschau',
  'wizard.accessSpace.step.plan': '7 · Plan',
  'wizard.accessSpace.target.help': 'Wählen Sie die vorhandene Kategorie, den Kanal, die logische Gruppe oder den gesamten Server, für den diese Regel gelten soll.',
  'wizard.accessSpace.target.placeholder': 'Ziel wählen…',
  'wizard.accessSpace.intent.help': 'Nur mit dem gewählten Ziel kompatible Absichten werden angeboten.',
  'wizard.accessSpace.roles.help': 'Wählen Sie jede vorhandene Rolle aus, die Teil dieser Zielgruppe sein soll.',
  'wizard.accessSpace.roles.suggestedName': 'Bestätigte Mitglieder',
  'wizard.accessSpace.roles.blockedByProposal': 'Fortfahren nicht möglich: Die vorgeschlagene Rolle existiert noch nicht. Fügen Sie mindestens eine vorhandene Rolle hinzu oder bereiten Sie zuerst deren eigenen Rollenplan vor und wählen Sie sie danach aus.',
  'wizard.accessSpace.conflicts.help': 'Diese vorhandenen Richtlinien zielen bereits auf dieselbe Ressource ab und können mit Ihrem Vorschlag interagieren.',
  'wizard.accessSpace.conflicts.empty': 'Derzeit zielt keine andere Richtlinie auf diese Ressource ab.',
  'wizard.accessSpace.conflicts.disclaimer': 'Diese Liste dient nur zur Information. Die genauen Konflikte und die gewinnende Regel erscheinen im Schritt Vorschau/Auswirkung, berechnet vom selben kanonischen Resolver.',
  'wizard.accessSpace.preview.action': 'Entwurf erstellen und Vorschau anzeigen',
  'wizard.accessSpace.preview.refresh': 'Vorschau aktualisieren',
  'wizard.accessSpace.preview.draftCreated': 'Ein Policy-Entwurf wurde erstellt. Discord wurde nicht verändert.',
  'wizard.accessSpace.plan.previewFirst': 'Sehen Sie sich zuerst die Vorschau des Entwurfs an.',
  'wizard.accessSpace.plan.roleTitle': 'Rollen-Erstellungsplan',
  'wizard.accessSpace.plan.roleHelp': 'Die vorgeschlagene Rolle existiert noch nicht. Bereiten Sie einen validierten Plan dafür vor; er bleibt unangewendet, bis Sie ihn später bestätigen.',
  'wizard.accessSpace.plan.prepareRole': 'Rollenplan vorbereiten',
  'wizard.accessSpace.plan.roleCreated': 'Rollenplan validiert. Es existiert noch keine Discord-Rolle.',
  'wizard.accessSpace.plan.policyTitle': 'Policy-Plan',
  'wizard.accessSpace.plan.policyHelp': 'Kompiliert den Policy-Entwurf in den kanonischen Plan. Preflight, Bestätigung und eine separate Anwendung sind weiterhin erforderlich, bevor sich auf Discord etwas ändert.',
}

const es: Record<keyof typeof en, string> = {
  'nav.wizards': 'Asistentes',
  'wizard.progress': 'Progreso del asistente',
  'wizard.back': 'Atrás',
  'wizard.next': 'Siguiente',
  'wizard.cancel': 'Salir',
  'wizard.cancelDiscard': 'Salir sin guardar',
  'wizard.cancelKeepDraft': 'Salir (se conserva el borrador)',

  'wizards.title': 'Asistentes',
  'wizards.subtitle': 'Ayudas guiadas que convierten una pregunta en una propuesta editable — nunca en un cambio directo en Discord.',
  'wizards.catalog.available': 'Disponible',
  'wizards.catalog.unavailable': 'Aún no disponible',
  'wizards.catalog.scope': 'Alcance',
  'wizards.catalog.produces': 'Produce',
  'wizards.catalog.prerequisites': 'Requisitos',
  'wizards.catalog.complexity': 'Complejidad',
  'wizards.catalog.start': 'Comenzar',
  'wizards.catalog.accessSpace.title': 'Configurar el acceso a un espacio',
  'wizards.catalog.accessSpace.goal': 'Decidir quién puede ver, escribir o unirse a una categoría, canal o todo el servidor.',
  'wizards.catalog.accessSpace.scope': 'Una categoría, un canal, un grupo lógico o el servidor, junto con los roles que deben verlo o escribir en él.',
  'wizards.catalog.accessSpace.produces': 'Una Policy de acceso en borrador y, si hace falta, un plan de creación de rol validado.',
  'wizards.catalog.accessSpace.prerequisites': 'Poder leer las políticas de este servidor.',
  'wizards.catalog.accessSpace.complexity': 'Unos 5 minutos, 7 pasos guiados.',
  'wizards.catalog.templates.title': 'Construir una plantilla',
  'wizards.catalog.templates.goal': 'Convertir una estructura existente en una plantilla reutilizable.',
  'wizards.catalog.templates.scope': 'Una categoría o un conjunto de canales.',
  'wizards.catalog.templates.produces': 'Un artefacto de plantilla portable.',
  'wizards.catalog.templates.prerequisites': 'Ninguno todavía.',
  'wizards.catalog.templates.complexity': 'Aún sin estimar.',
  'wizards.catalog.templates.unavailable': 'Previsto para la fase de Plantillas — este asistente aún no está construido.',

  'wizard.roles.existing': 'Roles existentes',
  'wizard.roles.managed': 'Gestionado',
  'wizard.roles.managedHelp': 'Gestionado por una integración — no se puede usar como audiencia.',
  'wizard.roles.empty': 'Este servidor aún no tiene ningún rol seleccionable.',
  'wizard.roles.proposed': 'Roles por crear',
  'wizard.roles.willBeCreated': 'Se creará',
  'wizard.roles.removeProposed': 'Quitar',
  'wizard.roles.create': '+ Crear un rol',
  'wizard.roles.createName': 'Nombre del rol',
  'wizard.roles.createHelp': 'Esto solo añade una propuesta aquí. No se crea nada en Discord hasta que prepares su propio plan.',
  'wizard.roles.confirmCreate': 'Añadir esta propuesta',
  'wizard.roles.suggested': 'Rol sugerido: {{name}} — se creará',
  'wizard.roles.useSuggestion': 'Usar esta sugerencia',

  'wizard.accessSpace.title': 'Configurar el acceso a un espacio',
  'wizard.accessSpace.subtitle': 'Responde algunas preguntas, revisa una propuesta editable y luego prepara una Policy en borrador y su Plan. Nunca se aplica nada a Discord desde aquí.',
  'wizard.accessSpace.step.target': '1 · Destino',
  'wizard.accessSpace.step.intent': '2 · Intención',
  'wizard.accessSpace.step.roles': '3 · Roles',
  'wizard.accessSpace.step.conflicts': '4 · Conflictos',
  'wizard.accessSpace.step.adjust': '5 · Ajustar',
  'wizard.accessSpace.step.preview': '6 · Vista previa',
  'wizard.accessSpace.step.plan': '7 · Plan',
  'wizard.accessSpace.target.help': 'Elige la categoría, el canal, el grupo lógico o el servidor existente al que debe aplicarse esta regla.',
  'wizard.accessSpace.target.placeholder': 'Elegir un destino…',
  'wizard.accessSpace.intent.help': 'Solo se ofrecen las intenciones compatibles con el destino elegido.',
  'wizard.accessSpace.roles.help': 'Selecciona cada rol existente que deba formar parte de esta audiencia.',
  'wizard.accessSpace.roles.suggestedName': 'Miembros confirmados',
  'wizard.accessSpace.roles.blockedByProposal': 'No se puede continuar: el rol propuesto aún no existe. Añade al menos un rol existente, o prepara primero su propio plan de rol y luego vuelve a seleccionarlo.',
  'wizard.accessSpace.conflicts.help': 'Estas políticas existentes ya afectan al mismo recurso y pueden interactuar con tu propuesta.',
  'wizard.accessSpace.conflicts.empty': 'Ninguna otra política afecta actualmente a este recurso.',
  'wizard.accessSpace.conflicts.disclaimer': 'Esta lista es solo informativa. Los conflictos exactos y la regla ganadora aparecen en el paso Vista previa / Impacto, calculados por el mismo resolver canónico.',
  'wizard.accessSpace.preview.action': 'Crear el borrador y previsualizar',
  'wizard.accessSpace.preview.refresh': 'Actualizar vista previa',
  'wizard.accessSpace.preview.draftCreated': 'Se creó una Policy en borrador. Discord no fue modificado.',
  'wizard.accessSpace.plan.previewFirst': 'Primero previsualiza el borrador.',
  'wizard.accessSpace.plan.roleTitle': 'Plan de creación del rol',
  'wizard.accessSpace.plan.roleHelp': 'El rol propuesto aún no existe. Prepara un plan validado para él; permanece sin aplicar hasta que lo confirmes más tarde.',
  'wizard.accessSpace.plan.prepareRole': 'Preparar el plan de rol',
  'wizard.accessSpace.plan.roleCreated': 'Plan de rol validado. Todavía no existe ningún rol de Discord.',
  'wizard.accessSpace.plan.policyTitle': 'Plan de la Policy',
  'wizard.accessSpace.plan.policyHelp': 'Compila la Policy en borrador en el Plan canónico. Aún se requieren un Preflight, una confirmación y una Aplicación separada antes de que algo cambie en Discord.',
}

export const phase4WizardPacks = { en, fr, de, es }
