export const phase3Packs = {
  en: {
    'structure.explorerEyebrow': 'Server explorer',
    'structure.explorerSubtitle': 'Browse the real Discord hierarchy, select resources and prepare safe structural changes.',
    'structure.summary.categories': '{{count}} categories',
    'structure.summary.channels': '{{count}} channels',
    'structure.summary.threads': '{{count}} threads',
    'structure.noMatch': 'No resource matches this search.',
    'structure.rootLabel': 'Server root',
    'structure.selection.none': 'Select a category, channel or thread to inspect it.',
    'structure.selection.help': 'Ctrl/Cmd-click adds or removes an item from the selection.',
    'structure.selection.actions': 'Selection actions',
    'structure.inspector.identity': 'Discord identity',
    'structure.inspector.discordId': 'Discord ID',
    'structure.inspector.type': 'Resource type',
    'structure.inspector.parent': 'Parent',
    'structure.inspector.position': 'Position',
    'structure.inspector.freshness': 'Freshness',
    'structure.inspector.observability': 'Observability',
    'structure.inspector.assertion': 'Data assertion',
    'structure.inspector.capability': 'Scoped capability',
    'structure.destinations.title': 'Destinations',
    'structure.destinations.subtitle': 'Drop inside this server to propose a move, or on another server to prepare a copy/clone.',
    'structure.destinations.thisServer': 'This server',
    'structure.destinations.otherServers': 'Other servers',
    'structure.destinations.loading': 'Loading destination structure…',
    'structure.destinations.unavailable': 'Destination structure is unavailable.',
    'structure.drop.root': 'Move to server root',
    'structure.drop.category': 'Move into {{name}}',
    'structure.drop.reorder': 'Place near {{name}}',
    'structure.drop.copy': 'Copy to {{name}}',
    'structure.drag.move': 'Move proposal',
    'structure.drag.copy': 'Copy / clone proposal',
    'structure.drag.release': 'Release to review the proposed action',
    'structure.drag.rightRelease': 'Release the right button to choose a valid drop action',
    'structure.tree.actions': 'Open actions for selection',
    'structure.tree.expand': 'Expand {{name}}',
    'structure.tree.collapse': 'Collapse {{name}}',
    'structure.showHiddenShort': 'Hidden/deleted',
    'structure.current': 'Current',
    'structure.stale': 'Stale',
    'structure.multiInspector': '{{count}} resources selected',
  },
  fr: {
    'structure.explorerEyebrow': 'Explorateur de serveur',
    'structure.explorerSubtitle': 'Parcourez la hiérarchie Discord réelle, sélectionnez des ressources et préparez des changements de structure sûrs.',
    'structure.summary.categories': '{{count}} catégories',
    'structure.summary.channels': '{{count}} salons',
    'structure.summary.threads': '{{count}} threads',
    'structure.noMatch': 'Aucune ressource ne correspond à cette recherche.',
    'structure.rootLabel': 'Racine du serveur',
    'structure.selection.none': 'Sélectionnez une catégorie, un salon ou un thread pour l’inspecter.',
    'structure.selection.help': 'Ctrl/Cmd-clic ajoute ou retire un élément de la sélection.',
    'structure.selection.actions': 'Actions de la sélection',
    'structure.inspector.identity': 'Identité Discord',
    'structure.inspector.discordId': 'ID Discord',
    'structure.inspector.type': 'Type de ressource',
    'structure.inspector.parent': 'Parent',
    'structure.inspector.position': 'Position',
    'structure.inspector.freshness': 'Fraîcheur',
    'structure.inspector.observability': 'Observabilité',
    'structure.inspector.assertion': 'Assertion de données',
    'structure.inspector.capability': 'Capacité sur la ressource',
    'structure.destinations.title': 'Destinations',
    'structure.destinations.subtitle': 'Déposez dans ce serveur pour proposer un déplacement, ou sur un autre serveur pour préparer une copie/un clonage.',
    'structure.destinations.thisServer': 'Ce serveur',
    'structure.destinations.otherServers': 'Autres serveurs',
    'structure.destinations.loading': 'Chargement de la structure de destination…',
    'structure.destinations.unavailable': 'Structure de destination indisponible.',
    'structure.drop.root': 'Déplacer à la racine du serveur',
    'structure.drop.category': 'Déplacer dans {{name}}',
    'structure.drop.reorder': 'Placer près de {{name}}',
    'structure.drop.copy': 'Copier vers {{name}}',
    'structure.drag.move': 'Proposition de déplacement',
    'structure.drag.copy': 'Proposition de copie / clonage',
    'structure.drag.release': 'Relâchez pour vérifier l’action proposée',
    'structure.drag.rightRelease': 'Relâchez le bouton droit pour choisir une action de dépôt valide',
    'structure.tree.actions': 'Ouvrir les actions de la sélection',
    'structure.tree.expand': 'Développer {{name}}',
    'structure.tree.collapse': 'Réduire {{name}}',
    'structure.showHiddenShort': 'Masqués/supprimés',
    'structure.current': 'À jour',
    'structure.stale': 'Obsolète',
    'structure.multiInspector': '{{count}} ressources sélectionnées',
  },
  de: {
    'structure.explorerEyebrow': 'Server-Explorer',
    'structure.explorerSubtitle': 'Durchsuchen Sie die echte Discord-Hierarchie, wählen Sie Ressourcen aus und bereiten Sie sichere Strukturänderungen vor.',
    'structure.summary.categories': '{{count}} Kategorien',
    'structure.summary.channels': '{{count}} Kanäle',
    'structure.summary.threads': '{{count}} Threads',
    'structure.noMatch': 'Keine Ressource entspricht dieser Suche.',
    'structure.rootLabel': 'Server-Wurzel',
    'structure.selection.none': 'Wählen Sie eine Kategorie, einen Kanal oder einen Thread zur Prüfung aus.',
    'structure.selection.help': 'Strg/Cmd-Klick fügt Elemente zur Auswahl hinzu oder entfernt sie.',
    'structure.selection.actions': 'Aktionen der Auswahl',
    'structure.inspector.identity': 'Discord-Identität',
    'structure.inspector.discordId': 'Discord-ID',
    'structure.inspector.type': 'Ressourcentyp',
    'structure.inspector.parent': 'Übergeordnet',
    'structure.inspector.position': 'Position',
    'structure.inspector.freshness': 'Aktualität',
    'structure.inspector.observability': 'Beobachtbarkeit',
    'structure.inspector.assertion': 'Datenzusicherung',
    'structure.inspector.capability': 'Ressourcenbezogene Fähigkeit',
    'structure.destinations.title': 'Ziele',
    'structure.destinations.subtitle': 'Innerhalb dieses Servers ablegen, um eine Verschiebung vorzuschlagen, oder auf einem anderen Server für Kopie/Klon.',
    'structure.destinations.thisServer': 'Dieser Server',
    'structure.destinations.otherServers': 'Andere Server',
    'structure.destinations.loading': 'Zielstruktur wird geladen…',
    'structure.destinations.unavailable': 'Zielstruktur ist nicht verfügbar.',
    'structure.drop.root': 'In die Server-Wurzel verschieben',
    'structure.drop.category': 'Nach {{name}} verschieben',
    'structure.drop.reorder': 'Nahe {{name}} platzieren',
    'structure.drop.copy': 'Nach {{name}} kopieren',
    'structure.drag.move': 'Verschiebevorschlag',
    'structure.drag.copy': 'Kopier-/Klonvorschlag',
    'structure.drag.release': 'Loslassen, um die vorgeschlagene Aktion zu prüfen',
    'structure.drag.rightRelease': 'Rechte Taste loslassen, um eine gültige Ablageaktion zu wählen',
    'structure.tree.actions': 'Aktionen für die Auswahl öffnen',
    'structure.tree.expand': '{{name}} erweitern',
    'structure.tree.collapse': '{{name}} reduzieren',
    'structure.showHiddenShort': 'Ausgeblendet/gelöscht',
    'structure.current': 'Aktuell',
    'structure.stale': 'Veraltet',
    'structure.multiInspector': '{{count}} Ressourcen ausgewählt',
  },
  es: {
    'structure.explorerEyebrow': 'Explorador del servidor',
    'structure.explorerSubtitle': 'Explore la jerarquía real de Discord, seleccione recursos y prepare cambios de estructura seguros.',
    'structure.summary.categories': '{{count}} categorías',
    'structure.summary.channels': '{{count}} canales',
    'structure.summary.threads': '{{count}} hilos',
    'structure.noMatch': 'Ningún recurso coincide con esta búsqueda.',
    'structure.rootLabel': 'Raíz del servidor',
    'structure.selection.none': 'Seleccione una categoría, un canal o un hilo para inspeccionarlo.',
    'structure.selection.help': 'Ctrl/Cmd-clic añade o elimina un elemento de la selección.',
    'structure.selection.actions': 'Acciones de la selección',
    'structure.inspector.identity': 'Identidad de Discord',
    'structure.inspector.discordId': 'ID de Discord',
    'structure.inspector.type': 'Tipo de recurso',
    'structure.inspector.parent': 'Padre',
    'structure.inspector.position': 'Posición',
    'structure.inspector.freshness': 'Actualidad',
    'structure.inspector.observability': 'Observabilidad',
    'structure.inspector.assertion': 'Aserción de datos',
    'structure.inspector.capability': 'Capacidad sobre el recurso',
    'structure.destinations.title': 'Destinos',
    'structure.destinations.subtitle': 'Suelte dentro de este servidor para proponer un movimiento, o en otro servidor para preparar una copia/clonado.',
    'structure.destinations.thisServer': 'Este servidor',
    'structure.destinations.otherServers': 'Otros servidores',
    'structure.destinations.loading': 'Cargando la estructura de destino…',
    'structure.destinations.unavailable': 'La estructura de destino no está disponible.',
    'structure.drop.root': 'Mover a la raíz del servidor',
    'structure.drop.category': 'Mover a {{name}}',
    'structure.drop.reorder': 'Colocar cerca de {{name}}',
    'structure.drop.copy': 'Copiar a {{name}}',
    'structure.drag.move': 'Propuesta de movimiento',
    'structure.drag.copy': 'Propuesta de copia / clonación',
    'structure.drag.release': 'Suelte para revisar la acción propuesta',
    'structure.drag.rightRelease': 'Suelte el botón derecho para elegir una acción de destino válida',
    'structure.tree.actions': 'Abrir acciones de la selección',
    'structure.tree.expand': 'Expandir {{name}}',
    'structure.tree.collapse': 'Contraer {{name}}',
    'structure.showHiddenShort': 'Ocultos/eliminados',
    'structure.current': 'Actual',
    'structure.stale': 'Obsoleto',
    'structure.multiInspector': '{{count}} recursos seleccionados',
  },
} as const
